### ISSUE TITLE
Vulkan Vertex Cache

### ISSUE THREAD

**Issue by DrChat** [xenia-project/xenia#1082]
We need an actual vertex cache - at the moment we have a "cache" that drops vertex data into a transient buffer that only persists for the current frame, i.e. **we re-upload vertex data every frame**.

## Problems
 * Vertex buffers **don't have to be aligned** to a page boundary
 * Vertex fetches are commonly larger than what is necessary
 * Vertex buffers may be accessed at an offset
   * GripShift: Fetch @ `0x1F050000` length `0x00100000`
   * followed by a fetch @ `0x1F050680` length `0x000FF980`
 * Most vertex buffers are very small (<64kb). Do we really need to cache these?

## Solution 1: Granular cache
 * We're going to use granular page-wide write watches.
   * This will put stress on the MMIO handler, so we will need to track it.
 * When a write watch is hit, flag *all* vertex buffers contained within as invalid.

## Solution 2: Mirrored Regions
 * **This may not work!** Vulkan storage buffers require an implementation-defined alignment, which is not guaranteed when mirroring data.
 * We do have access to the game's allocation table. We could peek at that, and upload pages associated with this allocation (+ adjacent allocations?)
   * From testing a few AAA titles and small games, no vertex buffers seem to cross any allocation boundaries. This makes sense - the game can't control where allocations are placed.
   * It also looks like some games aren't even pooling vertex buffers - instead allocating physical memory per buffer and passing the same arguments it used to create the buffer to the gpu fetch.
   * Others (Banjo Kazooie / Tooie) allocate a 2MB region and pool all vertex data inside
     * Geo Wars 3 allocates 100MB(!) for vertex data (+ other data?)
   * **Alignment**: is this going to be an issue? I've noted weird behavior from Banjo Kazooie/Tooie when extending the transient cache to swallow the 2MB range.
 * What granularity works best with watches? 128kb? 64kb? 16kb?
 * What about endianness of the data?
   * Doesn't matter! Swap dwords as all vertex data sizes *must* be a multiple of 4 bytes! Special formats (e.g. r16g16[f]) will be handled in SPIR-V.
   * Index buffers are a bit special and can't be cached alongside vertex buffers (or rather, *accessed* in the same cache as vertex buffers, because we're most certainly going to upload a few index buffers).

---
### UploadVertexBuffer
 1) Cache hit? Still valid? Return from cache.
 2) Upload to staging -> GPU
 3) Track in cache and register write watches if unwatched.

**Comment by LuismaSP89** [comment]
A vertex cache for VK would be a dream come true, but i think Xenia needs to recruit more developers to do the pending jobs. It´s a shame that Rpcs3 are maintained more frequently than Xenia because of his patreon. Is not fair that all the burden is now only on you, DrChat. I just wish i knew programming, i only can test games :S

**Comment by zemzema** [comment]
But maybe we can use some logic from rpcs3, like.
https://github.com/RPCS3/rpcs3/blob/7e32e7343a5f61d224770bb74e1428bf95ae4ad8/rpcs3/Emu/RSX/VK/VKFormats.cpp

**Comment by Triang3l** [comment]
Physical memory mirroring has been implemented in the Direct3D 12 backend, the cache is not needed anymore.
