### ISSUE TITLE
How to control the game? 

### ISSUE THREAD

**Issue by lsl312** [xenia-project/xenia#1084]
I tried keyboard control.WASD can control, but the other keys on the keyboard is useless.The game I play is Plants vs. Zombies
![123](https://user-images.githubusercontent.com/32743682/36102335-fb7ad758-1046-11e8-9f45-0725c94afd88.PNG)

**Comment by PikminGuts92** [comment]
You need an XInput controller plugged in.

**Comment by Parovozik** [comment]
I think just this game not works correctly on current Xenia. Try Bomberman Live, Asterix at the Olympic Games, Ice Age 3, G-Force, Hydro Thunder Hurrican, Spongebob Plankton's Robotic Revenge, Brave, Legend of Kay, LEGO Indiana Jones, LEGO Batman 1, Iron Man 2, Way of the Samurai 3, Ben 10 Ultimate Alien.
Xenia uses as default xbox360 controller (any x-input, even dualshock 4 though DS4_Windows software) or Keyboard if not found any x-input controllers.

**Comment by lsl312** [comment]
Thanks for the help

At 2018-02-13 09:09:16, "Parovozik" <notifications@github.com> wrote:


I think just this game not works correctly on current Xenia. Try Bomberman Live, Asterix at the Olympic Games, Ice Age 3, G-Force, Hydro Thunder Hurrican, Spongebob Plankton's Robotic Revenge, Brave, Legend of Kay, LEGO Indiana Jones, LEGO Batman 1, Iron Man 2, Way of the Samurai 3, Ben 10 Ultimate Alien.
Xenia uses as default xbox360 controller (any x-input, even dualshock 4 though DS4_Windows software) or Keyboard if not found any x-input controllers.

**Comment by DrChat** [comment]
What's happening here? Is the winkey input driver not working, or do you not know how to use it?

**Comment by DrChat** [comment]
Closed; inactive.
