### ISSUE TITLE
Rework Vulkan Fence Usage

### ISSUE THREAD

**Issue by DrChat** [xenia-project/xenia#1090]
There's a bunch of odd issues related to the way we're reusing fences at the moment.
Implement a round-robin style of fences, each tied to the frontbuffer/backbuffer.

**Comment by Parovozik** [comment]
Most often the "device is lost" simply indicates that the video memory has run out, this message is displayed in those games where a memory leak occurs. But I also met this error sometimes in games where there was no memory leak.

**Comment by DrChat** [comment]
There's a lot of causes for the message - but I'm seeing specific error from the validation layers.

**Comment by DrChat** [comment]
Will probably do this as part of the Qt branch - a lot of swap-related functionality has been improved there.

**Comment by Triang3l** [comment]
Using monotonically growing submission indices now — not applicable anymore.
