### ISSUE TITLE
start up problem.

### ISSUE THREAD

**Issue by GamerlordX** [xenia-project/xenia#1094]
Their is an issue where no matter what i do the .exe file wont open anything... i've checked task manager to see if anything was going on... and for a split second every time i launch Xenia it will show it and then an error app shows (doesn't show on desktop it just apears for a second in task manager) and then both apps would close.
![image](https://user-images.githubusercontent.com/37028556/36939740-0d382496-1f2e-11e8-9838-df8017ff7d74.png)

**Comment by Razzile** [comment]
could you run [HwInfo64 ](https://www.hwinfo.com/download.php) and screenshot the output

**Comment by DrChat** [comment]
Closed; too vague. Check #help on Discord.
