### ISSUE TITLE
Texture format (transparency glitch)

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1098]
For some games textures without transparency where it should be.
Maybe uses incorrect format textures?
For example games as RDR (trees, grass), Midnight Club LA (grass), Naruto games (trees, grass), GTA San Andreas (vegetable, wires), MK vs DCU (trees, effects), Asterix at the Olympic games (effects) and more.
![xenia naruto storm generation mkv_snapshot_02 21_ 2018 03 04_17 34 21](https://user-images.githubusercontent.com/19775644/36948553-a6c7384e-1fed-11e8-9a6b-b335912a1e63.jpg)
![fragment of mk 003 mp4_snapshot_02 14_ 2018 03 04_17 24 42](https://user-images.githubusercontent.com/19775644/36948554-aa481eca-1fed-11e8-80b9-b1712cad1fc2.jpg)
![desktop 2018 03 04 - 17 48 29 01 mp4_snapshot_00 35_ 2018 03 04_20 48 33](https://user-images.githubusercontent.com/19775644/36948556-acf47bdc-1fed-11e8-926f-d1e0467737d0.jpg)

**Comment by Parovozik** [comment]
Here trouble with compressed textures DXT 4_5 which converted for Vulkan as VK_FORMAT_BC3.
```
/* k_DXT1                   */ {VK_FORMAT_BC1_RGBA_UNORM_BLOCK},
/* k_DXT2_3                 */ {VK_FORMAT_BC2_UNORM_BLOCK},
/* k_DXT4_5                 */ {VK_FORMAT_BC3_UNORM_BLOCK},
```
![bandicam 2018-03-14 09-44-11-796](https://user-images.githubusercontent.com/19775644/37388897-4acc3c96-2773-11e8-90ca-407430468663.jpg)
I tried replaced on other formats, and came to the conclusion that everything is correct here, and the error occurs already in the rendering (the error is that the alpha channel is not used).
For example BC4 instead BC3 for DXT4 textures
![bandicam 2018-03-14 10-11-11-394](https://user-images.githubusercontent.com/19775644/37389050-d5bc5ac0-2773-11e8-9b74-a93fb2576a88.jpg)

**Comment by DrChat** [comment]
Hmm... Similar issue to [Banjo Kazooie](xenia-project/game-compatibility#206)?

**Comment by Parovozik** [comment]
I see Banjo rendering correct now (remember screenshot with eggs)
![bandicam 2018-03-10 23-37-21-844](https://user-images.githubusercontent.com/19775644/37567219-bfd95ed8-2ad4-11e8-9002-c895044b81cd.jpg)

**Comment by Parovozik** [comment]
I tried Banjo. Eggs uses texture format k_8888.
Alpha channel used but slightly glitch with close other obects and depend on view angel. Transparent turn on 1st egg and 2nd too but only one of them:
# here is correct:
![bandicam 2018-03-19 00-12-26-393](https://user-images.githubusercontent.com/19775644/37571871-a4ee1a2a-2b13-11e8-8ff0-7e8a9c9f5f35.jpg)
# here is incorrect:
![bandicam 2018-03-19 00-52-03-571](https://user-images.githubusercontent.com/19775644/37571885-cb818c62-2b13-11e8-9cf8-e787f4208d14.jpg)

**Comment by DrChat** [comment]
Banjo Tooie's issue is that the game isn't properly enabling alpha tests. Most likely a JIT issue.

**Comment by LuismaSP89** [comment]
This issue is present too in Bayonetta
![2](https://user-images.githubusercontent.com/12205048/40141233-9de3302e-5955-11e8-9d31-03fe4a10f88b.jpg)
![1](https://user-images.githubusercontent.com/12205048/40141234-9e042e32-5955-11e8-9fbc-106aae9152a9.jpg)

**Comment by LuismaSP89** [comment]
Some transparency glitches solved in latest Xenia build, (Bayonetta plants for example)

**Comment by win98and95** [comment]
Now fixed with https://github.com/xenia-project/xenia/commit/9dd62c1e1553cf89bb7e3c4779163ec404b9599f

**Comment by Triang3l** [comment]
Yes, alpha to coverage is implemented on Direct3D.

**Comment by Margen67** [comment]
This was fixed in D3D12, but not Vulkan.

**Comment by Triang3l** [comment]
> Forgive my ignorance, but how exactly can I fix this? I have been having this problem with gta iv and it is quite annoying. (i use vulkan)

Alpha-to-coverage hasn't been implemented in the Vulkan backend yet, use Direct3D 12 for now.
