### ISSUE TITLE
OpenGL was fully broken

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1114]
I understand that now the main Vulkan api.
I just want to report that I discovered a problem that appeared a month ago and OpenGL became completely broken (the emulator itself starts up, but the attempt to launch any game will immediately cause a critical error)
The last working build at (https://github.com/benvanik/xenia/commit/e54c24e1505e597ed29a133f162686e13d7294c5)
The next one already has this problem (https://github.com/benvanik/xenia/commit/b17d6f5088976b5aed12e45d44bf5c73d91bc41d).
Was changed file to path 'src-xenia-base-memory.cc'. If use 'base-memory.cc' from (https://github.com/benvanik/xenia/commit/e54c24e1505e597ed29a133f162686e13d7294c5) to any new build, example last (https://github.com/benvanik/xenia/commit/c5dbcc7e80bfa6b859a13799baf540495fec63d4) then OpenGL again works. 
So, if for some reason you are interested to see how OpenGL works (or compare it with emulator work on Vulkan api), you can use this method, replacing 1 file :yum: 
Crash logs from last master (https://github.com/benvanik/xenia/commit/c5dbcc7e80bfa6b859a13799baf540495fec63d4):
[xenia OGL cr1.log](https://github.com/benvanik/xenia/files/1809994/xenia.OGL.cr1.log)
[xenia OGL cr2.log](https://github.com/benvanik/xenia/files/1809995/xenia.OGL.cr2.log)
[xenia OGL cr3.log](https://github.com/benvanik/xenia/files/1809997/xenia.OGL.cr3.log)

**Comment by raynebc** [comment]
I built 6b8a34c9 a week and a half ago from the then-latest Git source and was able to launch a game with OpenGL with functionality comparable to 4 months prior.

**Comment by Parovozik** [comment]
Just look
# Feb 14 OGL:
![bandicam 2018-03-14 09-25-35-515](https://user-images.githubusercontent.com/19775644/37386634-5aa5f07a-276a-11e8-98e3-dc34d92d9126.jpg)
# March 4 OGL:
![bandicam 2018-03-14 09-26-39-519](https://user-images.githubusercontent.com/19775644/37386649-65f71350-276a-11e8-8c0b-16de2bd32d34.jpg)
# And more interesting OGL vs Vulkan last build (this last level of game and here OGL still win):
![bandicam 2018-03-14 09-27-11-174](https://user-images.githubusercontent.com/19775644/37386691-8c8c25e6-276a-11e8-9a2a-3dad290a73ae.jpg)
![bandicam 2018-03-14 09-28-16-360](https://user-images.githubusercontent.com/19775644/37386696-92babf5e-276a-11e8-952c-07496efa9d79.jpg)

**Comment by raynebc** [comment]
I'm just pointing out that your claim about trying to emulate ANY game with OpenGL results in "critical error" is not the case.  The emulation of some/many games is probably unchanged over the past several months of commits.

**Comment by raynebc** [comment]
https://github.com/xenia-project/game-compatibility/issues/720#issuecomment-370292522

This is a game that worked with OpenGL on a build newer than February 15.  So you are incorrect.  It's not worth arguing about, just correct your information and move on.

**Comment by Parovozik** [comment]
If OGL works for you this does not mean that no one has problems with it

**Comment by raynebc** [comment]
The point you are missing is that OpenGL is not completely broken and unusable for all games as you claimed.

**Comment by Irixion** [comment]
Opening titles that previously worked with GL no longer work now. While GL is "deprecated" it is actually more accurate than Vulkan is at this point in time.

**Comment by LuismaSP89** [comment]
I can confirm this issue, the latest build that worked with Opengl was "Feb 14 2018" after that, all games I have, crash when I try to open under Opengl. Vulkan has no problem.

**Comment by raynebc** [comment]
I was able to emulate Bandfuse in OpenGL with yesterday's Xenia code base.  It rendered to only one quarter of the emulator window, but it did not crash.  At most, this crash issue only affects some games/hardware.

**Comment by DrChat** [comment]
Closed; OpenGL is deprecated.

**Comment by raynebc** [comment]
Hopefully Vulkan rendering gets up to par.
