### ISSUE TITLE
AMD Videocards

### ISSUE THREAD

**Issue by akiohirata** [xenia-project/xenia#1115]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

guitar hero 5 
[xenia.log](https://github.com/benvanik/xenia/files/1822673/xenia.log)

ufc 2013
[xenia.log](https://github.com/benvanik/xenia/files/1822674/xenia.log)

It's my pc or the emulator really are focuses in nvidia and don't actually support the amd video cards? because every time i try to run a game in vulkan in any build, the game doesn't load and crash, in a old build with a "fix" that have been apply, the game load but give a error in a short period of time, and GL4 aren't work anymore, in the pass at less the game can be loaded, but now it does not even work, both of then don't load a game and need that "fix" to run. Sorry for bad english

**Comment by shadowbrony33** [comment]
The doesn't work on the newer builds and I can't find what exactly is the problem is on AMD either.
We  really need @DrChat  to find a fix.

**Comment by zemzema** [comment]
It's seems that he is really busy guy, no new commit in last two weeks.

**Comment by DrChat** [comment]
Closed; too vague. Check the #help channel on Discord.
