### ISSUE TITLE
[VK] Texture Format k_1_5_5_5 incorrect render

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1117]
I explored Scott Pilgrim game and found that the texture format k_1_5_5_5 is inverted to Vulcan api. For GL4 all correct. Trouble what VK_Format do have inverted format for k_1_5_5_5.
Requires special section for it provide convert from A1BGR5 to A1RGB5.
Can use (i think) format VK_FORMAT_R5G5B5A1_UNORM_PACK16 or other, but anyway requires conversion.
More info:
![1](https://user-images.githubusercontent.com/19775644/37689584-f9974a3e-2cb6-11e8-905c-32473616904e.jpg)
Source:
![2](https://user-images.githubusercontent.com/19775644/37689725-d22a1e8a-2cb7-11e8-8407-fdb23cb6cea0.jpg)
# OGL default (GL_RGBA):
![bandicam 2018-03-21 02-47-58-467](https://user-images.githubusercontent.com/19775644/37689797-4b38e4dc-2cb8-11e8-81f5-b16ddcebebab.jpg)
# OGL inverted (GL_BGRA):
![bandicam 2018-03-21 02-46-30-002](https://user-images.githubusercontent.com/19775644/37689823-6d70c024-2cb8-11e8-885c-78fe70236919.jpg)
# Vulkan default (VK_FORMAT_A1R5G5B5_UNORM_PACK16):
![bandicam 2018-03-21 02-49-02-294](https://user-images.githubusercontent.com/19775644/37689893-be4cbc8c-2cb8-11e8-90dc-537ae8aab478.jpg)

**Comment by Parovozik** [comment]
Games which uses 1_5_5_5 textures:
- Scott Pilgrim
- Castlevania SOTN
- Jet Set Radio (Trees)
- Puzzle Fighter (Characters)
- Simpsons Arcade

**Comment by DrChat** [comment]
Nice catch.
A stupid hack that immediately comes to mind is we could swap the channels in the sampler setup, just so we wouldn't have to deal with actual conversion.

**Comment by gibbed** [comment]
I wouldn't necessarily call that a hack if we want to avoid swapping the actual texture data in-place.

**Comment by Margen67** [comment]
@gibbed tested with https://github.com/xenia-project/xenia/commit/988877f42848e14855f7b678a2eaf7aaa507b716. Still not fixed:
![scott](https://user-images.githubusercontent.com/3462541/39951792-2a8aaf1a-5542-11e8-82ae-11335120d830.png)

**Comment by gibbed** [comment]
How about with a510bc3c782bafb0cc7e18c580a647b14a5cb52f?

**Comment by Margen67** [comment]
Scott Pilgrim vs The World is fixed with https://github.com/xenia-project/xenia/commit/a510bc3c782bafb0cc7e18c580a647b14a5cb52f.
![fixed](https://user-images.githubusercontent.com/3462541/39952467-396f457c-554c-11e8-87e6-7360f132e415.png)

**Comment by gibbed** [comment]
Great.
