### ISSUE TITLE
[VK] Texture formats k_8_8_8_8_A

### ISSUE THREAD

**Issue by zemzema** [xenia-project/xenia#1120]
I'm not sure but i have done some comparing between Vulkan and OpenGL formats, and it's seems that format OGL4.5 SRGB8_ALPHA8 is same as VK_FORMAT_R8G8B8A8_SRGB (k_8_8_8_8_A).

If I'm mistaking sorry...

**Comment by DrChat** [comment]
I'm not sure what you're getting at - have you seen any games using `k_8_8_8_8_A`?

**Comment by jobs-git** [comment]
you can borrow rpcs3 format, they were able to figure it out.

**Comment by zemzema** [comment]
Now I'm not sure which game it was, I need to check compatibility list log files that I was post, to try to find that.

**Comment by zemzema** [comment]
No, I did't find log in which I found K_8_8_8_8_A... maybe I made mistake with line like this:

w> 00000004 Warning: Uploading blank texture at address 0x13EC0000 (length: 0x000F0000, format: k_8_8_8_8)
