### ISSUE TITLE
A crash occurs when Xenia opens the xex file.

### ISSUE THREAD

**Issue by Colossus312** [xenia-project/xenia#1126]
The program of the xenia from My Computer does not work properly. At the moment of executing the file, a window will appear in which the program stops and ends after 1 or 2 seconds.
I ran the same game on a computer like 2 years ago, but that worked fine.
The OS has not changed.
In the environment of gpu=gl4, the computer is temporarily freezing for a while with the white screen when reading the file, the end window is visible
In vulkan's environment, one frame of the logo floating at the start of the game is displayed and an end window is displayed.
Of course naturally only sound comes out with gpu=null, but it works normally without error.
It is a computer that I am using without formatting.
If the old version of the xenia data is a problem, please tell me how to clean it.
I tried xenia in many versions and another game rom file, but same issue

This my computer specs.
Intel i7-6700k
Ram ddr4-3200 64GB
Graphic Nvidia Titan X(pascal)
Os Window 10 64bit

The game name is Sonic The Hedgehog(2006)
It is a compatible game in xenia

This is log (Vulkan)
[xenia.log](https://github.com/benvanik/xenia/files/1955439/xenia.log)

(gpu=gl4)
[xenia.log](https://github.com/benvanik/xenia/files/1955442/xenia.log)

**Comment by shadowbrony33** [comment]
What driver version are you using?

**Comment by Colossus312** [comment]
I'm using the 397.31 version.

**Comment by DrChat** [comment]
Closed; too vague - check on the #help channel on Discord
