### ISSUE TITLE
AMD R9 380 and Vulkan 1.1

### ISSUE THREAD

**Issue by tydowntyty** [xenia-project/xenia#1139]
[//]: # (Describe what's going wrong:)

Xenia tells me my AMD R9 380's vulkan is not supported in the latest version of Xenia. I also saw some recent updates added Vulkan 1.1. Does the R9 380 not support Vulkan 1.1?

[//]: # (Describe what should happen:)

Do I need to update my drivers. Are there going to be Vulkan 1.0 builds in the future? Am I able to make Vulkan 1.0 builds?

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by zemzema** [comment]
I'm having R7 360, and doesn't have any problem with last update. Try update drivers.
