### ISSUE TITLE
GPU Primitive Type k2DCopyRectListVX

### ISSUE THREAD

**Issue by DrChat** [xenia-project/xenia#1143]
Figure out what the heck these are.
https://github.com/xenia-project/xenia/blob/9653c0bafc586ecdc64a5aa8821bdfebeef45d3b/src/xenia/gpu/xenos.h#L39-L42

**Comment by gibbed** [comment]
What games are using this?

**Comment by DrChat** [comment]
BK N&B uses this, dunno about others

**Comment by Triang3l** [comment]
16 (line patch), 17 (triangle patch) and 18 (quad patch), when tessellation is enabled, are used for tessellation patches where the patch index (rather than control patch indices, unlike for normal primitive types in Viva Piñata and Call of Duty 3) is passed to the vertex shader.

**Comment by Triang3l** [comment]
Tessellation is not yet implemented in the new Vulkan backend (#2028), but this is done in the D3D12 one.
