### ISSUE TITLE
k_DXT5A format

### ISSUE THREAD

**Issue by zemzema** [xenia-project/xenia#1144]
I notice in Xenia log that k_DXT5A is VK_FORMAT_UNDEFINED.  I'm not sure can this be of some help.

https://github.com/BinomialLLC/crunch
https://sites.google.com/site/richgel99/luma_chroma_texture_compression

And one of the logs:
[nba2k.zip](https://github.com/xenia-project/xenia/files/1996725/nba2k.zip)

**Comment by gibbed** [comment]
See if 988877f42848e14855f7b678a2eaf7aaa507b716 helps?

**Comment by zemzema** [comment]
Ok, you fix the problem I notice graphic correction, first time I can see some dialog menu in game.
