### ISSUE TITLE
Check k_DXT1 format

### ISSUE THREAD

**Issue by zemzema** [xenia-project/xenia#1148]
Common error:

G> 00000004 Uploading texture @ 0x1BD3F000 (128x128, length: 0x0000C000, format: k_DXT1)
w> 00000004 Failed to convert texture
w> 00000004 Failed to setup one or more texture bindings
G> 00000004 Uploading texture @ 0x13AED000 (256x256, length: 0x00030000, format: k_DXT1)
w> 00000004 Failed to convert texture
w> 00000004 Failed to setup one or more texture bindings

[xenia.zip](https://github.com/xenia-project/xenia/files/1997510/xenia.zip)

**Comment by gibbed** [comment]
Don't open a general issue unless you directly know it pertains to multiple games.
