### ISSUE TITLE
ShaderDumpxe:\CompareBackEnds) failed - no root found

### ISSUE THREAD

**Issue by zemzema** [xenia-project/xenia#1149]
This is the standard error message in lots of games:
ShaderDumpxe:\CompareBackEnds) failed - no root found

Affected:
[https://github.com/xenia-project/game-compatibility/issues/848](https://github.com/xenia-project/game-compatibility/issues/848)
[https://github.com/xenia-project/game-compatibility/issues/897](https://github.com/xenia-project/game-compatibility/issues/897)
[https://github.com/xenia-project/game-compatibility/issues/96](https://github.com/xenia-project/game-compatibility/issues/96)
[https://github.com/xenia-project/game-compatibility/issues/884](https://github.com/xenia-project/game-compatibility/issues/884)
[https://github.com/xenia-project/game-compatibility/issues/833](https://github.com/xenia-project/game-compatibility/issues/833)
[https://github.com/xenia-project/game-compatibility/issues/826](https://github.com/xenia-project/game-compatibility/issues/826)
...

**Comment by gibbed** [comment]
Not an error that matters.
