### ISSUE TITLE
Vulkan problem maybe?

### ISSUE THREAD

**Issue by zemzema** [xenia-project/xenia#1153]
Something have happened with Bayonetta, and I think it's related to Vulkan modification in last couple of days.

Please check images from before, and now, you also have images with log file attached.

[https://github.com/xenia-project/game-compatibility/issues/96](https://github.com/xenia-project/game-compatibility/issues/96)

**Comment by gibbed** [comment]
Stop creating game-specific issues on the Xenia repository.
