### ISSUE TITLE
Performance degradation due to texture churn caused by lookup failures

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-project/xenia#1157]
The fps are very low since the latest commits (I don´t know which one causses it)

* [Vulkan] Fix a PrepareResolve call the last commit forgot.
* [GPU] Use the pitch field in tfetch constants
* [Vulkan] Workaround for rapid fence reuse causing a memory leak

Build from 2018/05/15 has no problems.

**Comment by gibbed** [comment]
It's the memory leak workaround.

**Comment by LuismaSP89** [comment]
@gibbed I don´t know, but fps fall down from 60fps to 5fps (Bayonetta) 

If I can help or provide something you need to improve this (log, test, etc) please let me know.

**Comment by zemzema** [comment]
Confirming, there is a huge slow down. (tested with AMD card)

**Comment by legoj15** [comment]
Although there are slowdowns, a lot of games that would crash after a few minutes now don't crash

**Comment by Parovozik** [comment]
Same for me all new builds from [May 15+] works is very slow
Example 'Spyro Dawn of the Dragon' run at 50-60fps on old builds and 15-20fps on all new builds. This almost for all games now. Sometimes up to 10x slower. And some games cause critical glitches and hang up the whole pc (full freeze without any errors, after only reboot pc).

**Comment by gibbed** [comment]
@Parovozik For the system hang, use beta driver **397.96** if you're on Nvidia.

**Comment by gibbed** [comment]
Issue is caused by the changes that begin with https://github.com/xenia-project/xenia/commit/191dc30bee2489153dd5f3570a280dffdbff2ebf.

I eventually replaced this code, but the issue remains. Due to the changes, textures are being unnecessarily reuploaded to the GPU constantly enough to affect performance.

**Comment by gibbed** [comment]
Resolved or partially resolved as of https://github.com/xenia-project/xenia/commit/bbebfd49c88417384c974284c222d9e574ea45a5.

Requires further testing.

**Comment by Margen67** [comment]
@gibbed Performance is back to normal after your commits.

**Comment by LuismaSP89** [comment]
@gibbed Not only solved, also I think this improves many other games. A lot of users noticed this great improvement in the latest videos of youtube for Xenia.
