### ISSUE TITLE
Intel(R) HD Graphics 620 is supported, right?

### ISSUE THREAD

**Issue by Killerviolin** [xenia-project/xenia#1168]
I checked the list of graphics cards/integrated graphics that can run Vulkan, yet when I open Xenia it says this - 
"unable to initialize Vulkan graphics subsystem. Ensure you have the latest drivers for your GPU and that it supports Vulkan. See http://xenia.jp/faq/ for more information and a list of supported GPUs."

I don't know what to do. On the list, it says that my integrated graphics are supported, yet I cannot use xenia for the reason listed above. I think my drivers are up to date, but if they aren't, how do I update them?

Thanks!

**Comment by gibbed** [comment]
Xenia as of recently requires Vulkan 1.1 support. Are your drivers up to date?

**Comment by Killerviolin** [comment]
I believe that I have some sort of windows update to perform. I went to device manager, display adaptors, then clicked on the graphics card thing and searched for automatic driver updates. It said none were found, but then I clicked on "search for updated drivers on windows update" and it found something. I doubt it will work (that's just my luck) but it's worth a shot I suppose.

**Comment by gibbed** [comment]
Using Windows update in general, will not get you up-to-date drivers. You'd need to look at your vendor's website (in this case, Intel) for the relevant drivers.

**Comment by Killerviolin** [comment]
So, in other words, I'd have to buy something?

**Comment by gibbed** [comment]
What? no.

https://downloadcenter.intel.com/product/80939/Graphics-Drivers

**Comment by Killerviolin** [comment]
If I'm being completely honest, I don't know much about computers. I've tried to download the top thing in the link you sent me, but it says that it's not verified or whatever and that I should download one from my vendor (it's an HP laptop, but it runs on Intel 5)

**Comment by DrChat** [comment]
Intel HD Graphics 620 *is* supported, but you have to download the latest drivers straight from Intel.
Going to close this, and you can continue discussion in #help on the [Discord](https://discord.gg/Q9mxZf9).
