### ISSUE TITLE
Your documentation

### ISSUE THREAD

**Issue by GreNIX** [xenia-project/xenia#1169]
Is absolute garbage.  I was able to piece together a working build, out of what seems to be sheer luck.  For the love of Stallman, fix your awful docs. 

[//]: # (Describe what's going wrong:) Your docs

[//]: # (Describe what should happen:) 

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by gibbed** [comment]
If you feel there is a problem, perhaps you should actually describe the issue instead of making insults.
