### ISSUE TITLE
Consider Opening a Patreon Account.

### ISSUE THREAD

**Issue by YeimiK** [xenia-project/xenia#1179]
We should consider opening a Patreon for te project since Emulation of Xbox 360 Consoles is a goal lots of people are waiting for i'm sure they would help. And the money would be good for purchasing equipments and stuff necessary for testing. And of course having in count (and im not saying its the same) the huge proggress RPCS3 gained since they first opened up their Patrean account I'm shure It would improve things out with this Project Aswell...

**Comment by Triang3l** [comment]
https://www.patreon.com/xenia_project/overview
Maybe it needs more visibility though, it's neither on xenia.jp's main page nor in README.md.

**Comment by YeimiK** [comment]
I can Fix That.
