### ISSUE TITLE
Unable to initialize Vulkan despite up-to-date drivers supporting Vulkan

### ISSUE THREAD

**Issue by Imaynotbehere4long** [xenia-project/xenia#1184]
Ever since the 5/12 build (possibly sooner), Xenia crashes on startup with the message "Unable to initialize Vulkan graphics subsystem. Ensure you have the latest drivers for you GPU and that it supports Vulkan." However, my graphics card is an NVIDIA GeForce GTX 1060 6GB (yes, it's on the list of supported graphics cards). I even updated my GPU's drivers and it still crashes with that same message. To top it all off, the 4/21 build (which also exclusively uses Vulkan) runs just fine, so I'm not sure what happened between updates. I double checked with the current master build and the error still occurs.

I couldn't find any duplicates of my error here, so if this issue has been solved or if anyone has any idea what's going wrong, please let me know.

Log file:

i> 00001528 Build: detached / 5f16e462823e8be371385c7fbca8d9f71e113a06 on Jun  8 2018
i> 00001528 Initializing Vulkan 1.1.0...
i> 00001528 Found 3 global layers:
i> 00001528 - VK_LAYER_NV_optimus (spec: 1.0.65, impl: 0.0.1)
i> 00001528   NVIDIA Optimus layer
i> 00001528 - VK_LAYER_VALVE_steam_overlay (spec: 1.0.3, impl: 0.0.1)
i> 00001528   Steam Overlay Layer
i> 00001528 - VK_LAYER_LUNARG_standard_validation (spec: 1.0.65, impl: 0.0.1)
i> 00001528   LunarG Standard Validation Layer
i> 00001528 Found 11 global extensions:
i> 00001528 - VK_EXT_debug_report (0.0.9)
i> 00001528 - VK_EXT_display_surface_counter (0.0.1)
i> 00001528 - VK_KHR_get_physical_device_properties2 (0.0.1)
i> 00001528 - VK_KHR_get_surface_capabilities2 (0.0.1)
i> 00001528 - VK_KHR_surface (0.0.25)
i> 00001528 - VK_KHR_win32_surface (0.0.6)
i> 00001528 - VK_KHX_device_group_creation (0.0.1)
i> 00001528 - VK_KHR_external_fence_capabilities (0.0.1)
i> 00001528 - VK_KHR_external_memory_capabilities (0.0.1)
i> 00001528 - VK_KHR_external_semaphore_capabilities (0.0.1)
i> 00001528 - VK_NV_external_memory_capabilities (0.0.1)
i> 00001528 Verifying layers and extensions...
i> 00001528 - optional extension VK_EXT_debug_marker not found
i> 00001528 - enabling extension VK_KHR_surface (0.0.25)
i> 00001528 - enabling extension VK_KHR_win32_surface (0.0.6)
i> 00001528 Initializing application instance...
!> 00001528 vkCreateInstance returned VK_ERROR_INCOMPATIBLE_DRIVER
!> 00001528 Instance initialization failed; cannot find a compatible Vulkan installable client driver (ICD)
!> 00001528 Failed to create instance
!> 00001528 Failed to initialize vulkan instance
X> 00001528 Unable to initialize Vulkan graphics subsystem.
Ensure you have the latest drivers for your GPU and that it supports Vulkan. See http://xenia.jp/faq/ for more information and a list of supported GPUs.

**Comment by gibbed** [comment]
Only thing I can suggest is a clean installation of the latest drivers.

**Comment by legoj15** [comment]
If you're running xenia on a laptop with NVidia Optimus enabled, try right clicking on xenia.exe and "Run with graphics processor -> High-performance NVIDIA processor". If that doesn't work (or doesn't apply to you) then do a clean install of the latest drivers, my 1060 6GB works fine with xenia on current drivers

**Comment by Imaynotbehere4long** [comment]
"Run with graphics processor" doesn't show up when I right-click Xenia, and I literally installed the latest drivers for my GPU yesterday (Device Manager -> Display Adapters -> NVIDIA GeForce GTX 1060 6GB -> right click -> update drivers). I even restarted my computer after the update and Xenia still won't run.

**Comment by Imaynotbehere4long** [comment]
Thanks, it works now!
