### ISSUE TITLE
Vulkan BufferCache capacity too small for some games

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1187]
Tested on (https://github.com/xenia-project/xenia/commit/2314f25fb7252bb9054fd7c863e1a57bee90282d)
Missing graphics for some games will repaired if increase buffer from default '256' to '512'
Source: xenia-gpu-vulkan vulkan_command_processor.cc
`33 constexpr size_t kDefaultBufferCacheCapacity = 256 * 1024 * 1024;`
`33 constexpr size_t kDefaultBufferCacheCapacity = 512 * 1024 * 1024;`
Maybe the root of the problem is elsewhere, but it gives an effect (as an option it can be added as an option in the emulator settings.) :yum: 
# Screenshots:
![bandicam 2018-06-13 15-53-10-046](https://user-images.githubusercontent.com/19775644/41354823-a0d35bc2-6f28-11e8-9b6e-24ea3100594f.jpg)
![bandicam 2018-06-13 15-57-57-675](https://user-images.githubusercontent.com/19775644/41354826-a3b46d18-6f28-11e8-815f-1dda22ecf642.jpg)
![bandicam 2018-06-13 15-53-16-866](https://user-images.githubusercontent.com/19775644/41354856-b8789b2a-6f28-11e8-8916-5659c52def5c.jpg)
![bandicam 2018-06-13 15-58-05-430](https://user-images.githubusercontent.com/19775644/41354836-a9df8a7e-6f28-11e8-96ea-b9e4a9b505d1.jpg)
![bandicam 2018-06-13 15-54-44-572](https://user-images.githubusercontent.com/19775644/41354878-c94d062a-6f28-11e8-801c-287a30cbbab1.jpg)
![bandicam 2018-06-13 15-59-44-143](https://user-images.githubusercontent.com/19775644/41354883-cc1efe4e-6f28-11e8-80a6-eced7355cc61.jpg)

**Comment by zemzema** [comment]
@Parovozik, which software did you use for statistic in top left corner?

**Comment by Razzile** [comment]
@zemzema I believe that is the afterburner overlay. not 100% sure though

**Comment by Parovozik** [comment]
@zemzema  MSI Afterburner + RTSS (all included to AB installer)

**Comment by Parovozik** [comment]
Xbox360 uses 512MB shared memory (as RAM and as VRAM together). Maybe 512 volume is correct here, and just games not uses all size, but only part of him (300 or 400). Because i see what all games which i tried (many games) still works is correctly with 512 cache. Slightly reduce performance only for games when was is missing drawing (i think this normal, because uses more graphics details now) :yum:

**Comment by niko1point0** [comment]
Is this still relevant? A lot has changed in the past year

**Comment by jombo23** [comment]
I believe vulkan support is temporarily suspended whilst the d3d12 renderer is being developed. However, its supposed to be revisited later.

**Comment by Triang3l** [comment]
Closing as irrelevant anymore since the buffer cache approach, on a high level, has been deprecated in favor of a generalized GPU-side guest memory mirror.
