### ISSUE TITLE
Some trouble with 'min_mip_levels' commit

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1198]
Last working build without this trouble 1.0.1375 (https://github.com/xenia-project/xenia/commit/b5a88d1a7d9d8c565bbba819714982058c0e7b73)
Next build have it 1.0.1376 (https://github.com/xenia-project/xenia/commit/2c7043bd9825fb5e54c4ee92bc82ece2a4db8a2f) (and all next+)
# logs
[Bad_Company_1375.log](https://github.com/xenia-project/xenia/files/2139472/Bad_Company_1375.log)
[Bad_Company_1376.log](https://github.com/xenia-project/xenia/files/2139473/Bad_Company_1376.log)
# screenshots
![bandicam 2018-06-27 04-05-47-305](https://user-images.githubusercontent.com/19775644/41947655-7696989e-79c1-11e8-820f-3ac6714af8f1.jpg)
![bandicam 2018-06-27 04-04-42-159](https://user-images.githubusercontent.com/19775644/41947657-7941dbbc-79c1-11e8-81e7-83f6de5e8fe9.jpg)

**Comment by x1nixmzeng** [comment]
Has @gibbed seen this?

**Comment by Parovozik** [comment]
@x1nixmzeng i hope :)

**Comment by Margen67** [comment]
Game-specific issues don't belong here.
