### ISSUE TITLE
initialize Vulkan graphics subsystem error

### ISSUE THREAD

**Issue by AmrSaadMEGA** [xenia-project/xenia#1199]
When opening Xenia.exe this appears 

---------------------------
Xenia Error
---------------------------
Unable to initialize Vulkan graphics subsystem.
Ensure you have the latest drivers for your GPU and that it supports Vulkan. See http://xenia.jp/faq/ for more information and a list of supported GPUs.
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
Knowing that my graphics card and vulkan are initialized and working perfectly with other games and emulators

System specs : 

Windows 10
Amd radeon r7 m265
intel core i7 4500u
4GB RAM

**Comment by CapnJackDaniels** [comment]
Update your drivers. This happened to me too, just go to the AMD website and download the latest drivers.

**Comment by AmrSaadMEGA** [comment]
Ok i will give a try

**Comment by AmrSaadMEGA** [comment]
THANX it's working!
