### ISSUE TITLE
Unable to mount disc image file;file not found or corrupt

### ISSUE THREAD

**Issue by Russkiarmy** [xenia-project/xenia#1200]
i don't have a logfile, but i have an iso disc file image for Need For Speed most wanted and when i try to open it with xenia it tells me the disc image file is not found or corrupt. i've tried both using the regular file and the zip version and neither will work. i have no idea what's going wrong.

**Comment by tjd2** [comment]
I think you downloaded it from some pirate sites. If not then sorry.
Extract it with wx360 and you should be fine.
