### ISSUE TITLE
One of buffers get to incorrect scaling

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1202]
I sometimes see games with specific graphics issue. Usually this some effects layer (fog, clouds, particles, fire...)
Games for test (they have it trouble):
- The Incredible Hulk 
- Ace Combat 6 (https://github.com/xenia-project/game-compatibility/issues/419)
- Legend of the Guardians
- Iron Man 2 (https://github.com/xenia-project/game-compatibility/issues/995)

# Screenshots for example
![xenia_ironman2](https://user-images.githubusercontent.com/19775644/42114646-6c9999d4-7bf8-11e8-8ce4-fd8daaf59acd.jpg)
![xenia_hulk](https://user-images.githubusercontent.com/19775644/42076241-f0fd8090-7b7c-11e8-9bbc-16caa2cce34f.jpg)
![xenia_ace_combat_6](https://user-images.githubusercontent.com/19775644/42076463-f0940fa6-7b7d-11e8-9d96-e44df825deac.jpg)
![xenia_guardians](https://user-images.githubusercontent.com/19775644/42076575-5e6e6ba2-7b7e-11e8-8845-43429e76c452.jpg)

**Comment by tjd2** [comment]
Does not it affect Perfect Dark Zero?
I am calling it "Minecraft Farlands Effect"
https://user-images.githubusercontent.com/29800872/37174026-a245d156-2315-11e8-8322-7da732c723eb.png``
