### ISSUE TITLE
Vulkan_command_processor received a small mistake

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/xenia#1203]
Hi. I investigated some changes in recent months and found one small mistake. If this is reversed, then the emulator works much better. I think it's because of this that extra cycles of waiting are included when it is not necessary.
**Source: \src\xenia\gpu\vulkan\vulkan_command_processor.cc**
Block lines 556 - 564
Current:
```
556    vkWaitForFences(*device_, 1, &current_batch_fence_, VK_TRUE, -1);
557    if (cache_clear_requested_) {
558    cache_clear_requested_ = false;
559
560    buffer_cache_->ClearCache();
561    pipeline_cache_->ClearCache();
562    render_cache_->ClearCache();
563    texture_cache_->ClearCache();
564    }
```
Fixed:
```
556    
557    if (cache_clear_requested_) {
558    vkWaitForFences(*device_, 1, &current_batch_fence_, VK_TRUE, -1);
559    cache_clear_requested_ = false;
560    buffer_cache_->ClearCache();
561    pipeline_cache_->ClearCache();
562    render_cache_->ClearCache();
563    texture_cache_->ClearCache();
564    }
```

**Comment by tjd2** [comment]
I remember something caused major slowdown in Banjo Kazooie Nuts and Bolts, but it was fixed. Do you have any example games, that work better?

**Comment by Parovozik** [comment]
99.9% games.
this is clearly visible if your CPU is not fast enough. Improvements will be visible, in those games that are not at full speed (and there is no emphasis in the GPU).

**Comment by tjd2** [comment]
I am going to test it with Banjo Kazooie nuts and bolts today

**Comment by Realex-fire** [comment]
This change was made intentionally and is not an error:
https://github.com/xenia-project/xenia/commit/f591f2dace8e31f57799c5494c378952a959f535

**Comment by Parovozik** [comment]
This is a crutch, which is no longer needed. Because absolutely does not affect the problem with a memory leak!

**Comment by Realex-fire** [comment]
I just tested it on STH and the leak still happens and ends with a full memory overflow.
![test](https://user-images.githubusercontent.com/4948786/42136224-8af7f81e-7d81-11e8-99ae-7355a9d42f7c.JPG)

**Comment by tjd2** [comment]
It fixes memory leak on some games. For example Banjo Kazooie Nuts and Bolts without this "fix" crashes after few minutes. It should be togglable on and off, because it really fixes some games

**Comment by DrChat** [comment]
This is intentional to work around the "memory leak" issue. This will be removed in the Qt branch, eventually.
