### ISSUE TITLE
Assertion false failed

### ISSUE THREAD

**Issue by pfc** [xenia-project/xenia#1205]
[//]: # (Describe what's going wrong:)
After compiling xenia it fails to run.  I've no clue where to even begin troubleshooting this.
OS: Arch
CPU: AMD 1950x
GPU: NVIDIA 1080ti

[//]: # (If applicable, provide a callstack here - esp. for crashes)
$ xenia
xenia: ../src/xenia/base/threading_posix.cc:305: xe::threading::PosixSemaphore::PosixSemaphore(int, int): Assertion `false' failed.
Aborted (core dumped)

**Comment by 3vi1** [comment]
I discovered this issue today, trying to compile with Ubuntu Disco.  Why was this closed?  Will it not need to be fixed for the Linux porting?  

xenia/base/threading_posix.cc:305: xe::threading::PosixSemaphore::PosixSemaphore(int, int): Assertion `false' failed.
