### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by rogerfedererufficial** [xenia-project/xenia#1212]
a year ago I tried top spin 4 and as you know it does not work but the screen appeared. One day I tried again only that there was a black screen and I only heard the audio. It also happened with fifa street. I formatted the computer a few days ago and I tried smash court tennis 3 that did not start. All normal as long as I try top spin 3 and the audio part but the screen remains black. I have an AMD Radeon R5 M430 2gb and I do not know how to play on the vulkan. I tried to enter the openGL code but it always started with the vulkan. Can you explain to me how I can solve? (without sending other links)

**Comment by tgsm** [comment]
looks like there was a regression that made those games not work properly.

as for the OpenGL backend, that doesn't work because it was removed over three months ago.

**Comment by DrChat** [comment]
Gonna drop this issue because it's very nonspecific and can be a symptom of any number of larger problems.

**Comment by Tanooki12** [comment]
Same is happening for me right now on Banjo-Kazooie Nuts and Bolts. Audio but no picture.
