### ISSUE TITLE
Trying to run OpenGL patch for Xenia, but any game I try loading immediately crashes

### ISSUE THREAD

**Issue by Ibrahim9999** [xenia-project/xenia#1215]
I know the OpenGL patch is deprecated, however I'm trying to get this to work on my computer. I attached the log file, I have no emulator coding knowledge so I have no idea what any of the things inside the file means. I made sure I have all the updated drivers (I think), so I don't think that is the problem. Thank you for your time!

[xenia.log](https://github.com/xenia-project/xenia/files/2382507/xenia.log)

**Comment by Razzile** [comment]
OpenGL isn't just deprecated, it was removed completely many months ago

**Comment by DrChat** [comment]
OpenGL no longer supported - try Vulkan or D3D12 :)
