### ISSUE TITLE
Website Compatibility List

### ISSUE THREAD

**Issue by tzizi** [xenia-project/xenia#1216]
The Compatibility list for the website uses Github API calls, which both takes a very long time to load, and causes API rate limiting.

Would it be possible instead to have a script that would monitor issues, and commit to the `gh-pages` branch of a repository?

**Comment by gibbed** [comment]
That's on my TODO list personally, but low priority currently.

**Comment by Margen67** [comment]
This was removed by #1391/#1392 due to it not working most of the time.
