### ISSUE TITLE
[UX] Graphics API selection

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1224]
Can you please make a user-friendly way for the user to select which API they want to use, between DirectX and Vulkan?

**Comment by Triang3l** [comment]
Currently there's no need for this as the existing Vulkan renderer of Xenia has reached a dead end and is far behind the new Direct3D 12 renderer in regards to feature completeness. They're not just two different wrappers of the host API, they're completely different GPU emulation implementations.

**Comment by niko1point0** [comment]
Is there any chance that Vulkan will return for Linux and Android in the future?

**Comment by 0x8080** [comment]
Android will certainly never be a targeted platform @niko1point0 , and yes all the work currently done on the D3D12 builds will be moved to Vulkan at some point in the future

**Comment by Triang3l** [comment]
Yes, but there are no plans to do that very soon, currently GPU emulation itself needs to be improved.
