### ISSUE TITLE
GTA IV Can't load save 

### ISSUE THREAD

**Issue by win98and95** [xenia-project/xenia#1229]
[Video](https://www.youtube.com/watch?v=kCSoOhHTDoY)

![1](https://user-images.githubusercontent.com/37698908/46882506-20b68f80-ce79-11e8-9638-357be139b80b.jpg)
![2](https://user-images.githubusercontent.com/37698908/46882504-20b68f80-ce79-11e8-9911-5a645f31d644.jpg)
![3](https://user-images.githubusercontent.com/37698908/46882505-20b68f80-ce79-11e8-84ba-9db4c9f49a37.jpg)

**Comment by DrChat** [comment]
Go ahead and report this in the game-compat repo: xenia-project/game-compatibility#427
