### ISSUE TITLE
[Feature Request] Easy Kinect Idea

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1232]
For testing Kinect Games, can you make it so we can move a virtual hand by clicking where we want the hand to be on the screen?

**Comment by DrChat** [comment]
This is likely not possible. Pretty sure the Kinect feeds in body position data, nothing that can be related to on-screen positions.

**Comment by Gorilli09** [comment]
How about using a webcam as a Kinect or an official Kinect for Windows?

**Comment by andrewbelling** [comment]
> How about using a webcam as a Kinect or an official Kinect for Windows?

## tl;dr: no.
It's not feasible, Kinect uses depth data that a standard webcam can't typically produce, to do this Xenia would somehow need to estimate depth data based on the webcam image in real-time which is typically not able to be done unless you have a high-end GPU that could do that in real-time.

_Also @Gorilli09, please don't make replies to closed issues that are 6 years old :)_
