### ISSUE TITLE
[Feature Request] Save states and load states

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1233]
In many retro emulators, such as PCSX2 (PlayStation 2) there is the ability to save and load "states" which is an exact state of a game. Can this feature be implemented in Xenia? Even if  the emulator has to lag for a few seconds, it would be a great feature to have.

It would make Xenia stand out as superior to RPCS3

**Comment by Margen67** [comment]
Save states have already been implemented, but are broken: #665
