### ISSUE TITLE
Blackscreen no video

### ISSUE THREAD

**Issue by daisyanne1380** [xenia-project/xenia#1242]
I tried a few game on the working list and all of them seem to have black screen but i can hear music and the options seem to work. I can see menu items that pop out like save and creating save file but not the actual game.
Im using:
intel I9-7940
gtx 1080ti

**Comment by PotatoAndSickle** [comment]
Update to the latest version

**Comment by Triang3l** [comment]
Game compatibility, while constantly being improved, is also getting broken constantly, as methods of emulation of parts of the console are often changed and experimented with to increase overall accuracy, however, different games do things differently, and we can't cover all cases. Please provide details about each game — including xenia.log, screenshots, the version of Xenia used — in the [game compatibility tracker](https://github.com/xenia-project/game-compatibility).

**Comment by Triang3l** [comment]
Game compatibility, while constantly being improved, is also getting broken constantly, as methods of emulation of parts of the console are often changed and experimented with to increase overall accuracy, however, different games do things differently, and we can't cover all cases. Please provide details about each game — including xenia.log, screenshots, the version of Xenia used — in the [game compatibility tracker](https://github.com/xenia-project/game-compatibility).

**Comment by Triang3l** [comment]
Game compatibility, while constantly being improved, is also getting broken constantly, as methods of emulation of parts of the console are often changed and experimented with to increase overall accuracy, however, different games do things differently, and we can't cover all cases. Please provide details about each game — including xenia.log, screenshots, the version of Xenia used — in the [game compatibility tracker](https://github.com/xenia-project/game-compatibility).
