### ISSUE TITLE
XAudio2_9.dll error

### ISSUE THREAD

**Issue by some-username-here1** [xenia-project/xenia#1246]
### Describe what's going wrong:
![xaudio2_9 dll](https://user-images.githubusercontent.com/34193156/47385828-f017f680-d6bf-11e8-8f29-8d7d8cc0af7a.png)
(I'm on Windows 8.1, trust me)

### Describe what should happen:
Xenia starting up without any errors

Relating to #267, happening with commit 00adfca (Oct. 23, 2018)

**Comment by gibbed** [comment]
I checked the latest master build and it isn't linking against XAudio 2.9, so you must have downloaded the D3D12 branch, which requires Windows 10.

**Comment by some-username-here1** [comment]
But even with the main download link from the website itself, I still get the same error

**Comment by legoj15** [comment]
I just downloaded the supposed "Windows 8.1+" build from xenia.jp, and ran a game, and it is in fact defaulting to D3D12.

**Comment by gibbed** [comment]
https://ci.appveyor.com/project/benvanik/xenia/branch/master/job/2428j078un6rgcl6/artifacts

The correct latest build for master branch (as of this comment).

**Comment by some-username-here1** [comment]
Thanks!
