### ISSUE TITLE
Xenia vulcan build not listed as a download on the website

### ISSUE THREAD

**Issue by MegaMech** [xenia-project/xenia#1248]
The website claims that Xenia works and is built for windows 8 and up. But the latest version of Xenia has vulcan support or DX11/9 (If that was ever a thing) removed. The build that you can download from the website does not work on windows 8.1 as claimed. No build history is available.

If you don't want people downloading Xenia from other websites maybe make the build history available to everyone or leave both versions of Xenia available for people who refuse to downgrade to windows 10.

**Comment by gibbed** [comment]
The website linking to D3D12 merge builds is unintentional.

Full build history is available, you're not looking in the right place.

https://ci.appveyor.com/project/benvanik/xenia/history

Grab the latest build for `-master`.

**Comment by MegaMech** [comment]
I don't really see any place to download the executable using that.

**Comment by gibbed** [comment]
![#1](https://user-images.githubusercontent.com/85170/47670329-e50b0d80-db7a-11e8-919c-288af66b4c3d.png) ![#2](https://user-images.githubusercontent.com/85170/47670336-e805fe00-db7a-11e8-8fa6-86d0db22dc45.png) ![#3](https://user-images.githubusercontent.com/85170/47670338-eb00ee80-db7a-11e8-9f25-05b2675ae0fc.png) ![#4](https://user-images.githubusercontent.com/85170/47670343-eccab200-db7a-11e8-861b-8f14063e96be.png)

**Comment by gibbed** [comment]
I've now fixed this issue on the website itself, it won't pull PR artifacts anymore.

**Comment by MegaMech** [comment]
Thanks!
I had looked at that page before but couldn't figure it out.
