### ISSUE TITLE
[Vulkan] Black Screen on Halo 3

### ISSUE THREAD

**Issue by DrP2016** [xenia-project/xenia#1258]
I have tried a few prebuild Vulkan releases and a selfbuild version, but in all the screen stays black. I tested with Halo 3. The sound seems to work perfectly and the game recognizes buttonspresses too.

Hardware:
-Ryzen 2700X
-16 GB RAM
-500 GB SSD
-GTX1080
-ASUS X470F

I tried to Upload the LogFile, but it is almost 16MB big, just for the 1-2 Minutes i had it running. So i uploaded as much as i could to a single [PasteBin](https://pastebin.com/EDyWNJSi)

Edit: I also tried the DX12 releases, and all of them DONT have this problem

**Comment by Triang3l** [comment]
The Vulkan renderer lacks many important features required to run Halo 3, such as the entire EDRAM emulation, rendering to textures with non-32-aligned width, 3D/array textures, Shader Model 3 behavior of multiplication instructions for 0.0 * Infinity. It's abandoned and has a flawed architecture, pretty much needs a total rewrite.
