### ISSUE TITLE
Big Problem with DirectX 12 Memory Leaks

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1270]
I tested the game Call of Duty Modern Warfare 3. I went to Solo Survival on the Underground map. I ran this test on two different Xenia builds

On the Vulkan Build 1.0.1568, I could play the game for over an hour, and GPU Memory peaked at 482mb

On the DirectX 12 Build 1.0.1567, I could play the game for only 10 minutes. Literally GPU Memory kept rising, at a rate consistent of around 10mb per second. Eventually the GPU Memory filled up (2gb), and started overflowing into my CPU Memory (8gb). Eventually, both were filled, and the game crashed

Please fix this problem

-------------------------------------------------------------------------------------------------------

[ Edit ]
After posting this issue, I tested more games for an hour; I tested Sonic Unleashed, Spyro Dawn of the Dragon, Burnout Revenge, Skate 3, Rio, and other Call of Duty games

Does this DirectX 12 Build ever delete allocated GPU memory? I never once saw GPU memory decrease, even after quitting levels

**Comment by Triang3l** [comment]
Currently it never deallocates textures, but I'm planning to add least-recently-used caching.

**Comment by niko1point0** [comment]
Okay. Thank you
