### ISSUE TITLE
Xb format and xb lint do not properly fix build issues on spaces

### ISSUE THREAD

**Issue by goedzo** [xenia-project/xenia#1277]
When creating the pr for #1276 i found out the hard way that spaces / tabs are not found when running the xb format command before or after a commit. 

I had to manually commit the pr, look to the build logs on yarvis that it failed and then recommit to fix two indent spaces. 

Or we should remove this spaces indent check from the build itself or make sure that these are found with lint and format. 

You can use #5ec6349 for validation of the issue to see the difference and failures.

**Comment by jgoyvaerts** [comment]
You need to run xb format on staged changes, not on commited changes. The command help (when typing xb) clearly mentions it.

Xb lint has the same behavior (only checks staged changes), but the help doesn't clearly state that.

If you had read contributing.md like I told you, you would have noticed a link to https://github.com/xenia-project/xenia/blob/master/docs/style_guide.md

In the [chapter buildbot](https://github.com/xenia-project/xenia/blob/master/docs/style_guide.md#buildbot-verification) verification it mentions that the buildbot runs xb format --all. 

I ran xb format --all on your commit 86af144dd and it successfully reformatted your file, so there's no bug, just user error

**Comment by jgoyvaerts** [comment]
Also, in the last 4 days you have opened 5 pull requests and 1 issue, 4 of those pull requests have been closed with various comments explaining you what's wrong.

Consider reading some more about the project or hanging out in the discord before opening any other rushed PRs/Issues

**Comment by goedzo** [comment]
Can you explain why I cannot run this command?

xb format -all
usage: xenia-build [-h]
                   {setup,pull,premake,build,genspirv,gentests,test,gputest,clean,nuke,lint,format,style,tidy,devenv}
                   ...
xenia-build: error: unrecognized arguments: -all

**Comment by goedzo** [comment]
xb format --all 

What a nice one to use here :).
I will consider going to bad earlier next time instead of getting this done at 3 am.

Fyi, I don't even have a clue what staged changes are, so I need to read up on GIT here.
