### ISSUE TITLE
Xenia 1609 broke all my saved data

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1281]
In Xenia 1593, I was able to play multiple games, such as Call of Duty MW3, Sonic Unleashed, and Spyro Dawn of the Dragon. All of these games had functional save/load systems.

Now in Xenia 1609 (and all versions beyond), none of my saved data is detected.
The data was not deleted, because I can open Xenia 1593 and it works like usual.

Please fix the problem.
Thank you.

**Comment by gibbed** [comment]
Xenia now stores save data in Documents by default on Windows. If you prefer the old behavior, you can create a portable.txt next to xenia.exe (doesn't matter the contents of the file) to get that back.
