### ISSUE TITLE
Xenia 1625 DirectX won't open any XEXs

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1282]
I have two versions of Xenia. I have 1609 DirectX 12, which works fine, but version 1625 won't open any XEX. What happens is I click "Open", then I click on default.xex that I want, and the program closes. 1609 still works fine

Edit:
I just tried Xenia 1624 (Vulkan) and it works fine, but 1625 does not work

**Comment by TheCubeMaster019** [comment]
xexp loading is currently broken. if there's a "default.xexp" in the same directory as default.xex, xenia won't load it. if you have a default.xexp in the same directory, try renaming it and report back, please.

**Comment by niko1point0** [comment]
There is no xexp in the directory

**Comment by TheCubeMaster019** [comment]
Alright, could you post a log?

**Comment by niko1point0** [comment]
[xenia.log](https://github.com/xenia-project/xenia/files/2612464/xenia.log)

**Comment by TheCubeMaster019** [comment]
I haven't seen this before, so I can't help you there... Hopefully someone else who knows what's happening will step in.

**Comment by niko1point0** [comment]
Ok. Thank you

**Comment by niko1point0** [comment]
I'm not sure why, but all my games suddenly started working again. I did not change any settings, it just suddenly started working. Maybe the log can help fix problems in the future though

**Comment by Triang3l** [comment]
Rick has fixed recently broken XEX loading code in f7501750d960dc049ca535f4f36cd706a1698c94.
