### ISSUE TITLE
Big slowdown in games after 9a588412 "[D3D12] ROV: Use MSAA instead of SSAA"

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-project/xenia#1287]
Games have a slowdown after the build 9a588412 "[D3D12] ROV: Use MSAA instead of SSAA" and not only that, they look worse. Eternal sonata also has some graphical artifacts with this build. (Third image, in the "New game" text) There´s some white noise in this new build.

Tested games with slowdowns: Bayonetta and eternal sonata (Comparing 9a588412 vs previous build 9709a230)

9a588412:
![new1](https://user-images.githubusercontent.com/12205048/48985787-1b04c880-f10c-11e8-866a-32707ea7cd37.jpg)

9709a230:
![old2](https://user-images.githubusercontent.com/12205048/48985789-20faa980-f10c-11e8-8ccb-960d27f32bca.jpg)

9a588412:
![new2](https://user-images.githubusercontent.com/12205048/48985793-2eb02f00-f10c-11e8-9ebe-94b643926a7b.jpg)

9709a230:
![old](https://user-images.githubusercontent.com/12205048/48985794-3374e300-f10c-11e8-9b56-a4fae8bd082a.jpg)

**Comment by Margen67** [comment]
It looks worse because MSAA is a downgrade from SSAA, but is more accurate.

**Comment by LuismaSP89** [comment]
> 
> 
> It looks worse because MSAA is a downgrade from SSAA, but is more accurate.

Yes, I know that MSAA is a downgrade, but it needs less graphic power than SSAA, it makes no sense the slowdown, so maybe the code is not perfectly implemented yet. I don´t know if is "more accurate" but SSAA looks better in all games.

**Comment by Margen67** [comment]
If you want games to look better just wait for resolution scaling.

**Comment by LuismaSP89** [comment]
The main reason of this issue is the slowdown introduced in that build, not only the downgrade of the visuals or the graphical artifacts.

**Comment by LuismaSP89** [comment]
Nvidia GTX 970

**Comment by LuismaSP89** [comment]
@Triang3l Ok, I found where the issue is.

The problem is with the nvidia graphics card having enabled the (Antiliasing - Transparency) option other than multisample. If you select supersample (no matters if 2x, 4x or 8x) the graphical problems and the big slowdown comes in.

So, in short, supersample options in the antialiasing - transparency options of the nvidia control panel have problems after build 9a58841 causing graphical artifacts and huge slowdown. If you disable this option for xenia, or only enables multisample, all works as it should.

I´ll keep this open if you need to change something to solve this, or you can close by yourself, feel free to do that.

Thanks a lot for your help and keep making Xenia the awesome emulator that it is ; )

**Comment by Triang3l** [comment]
@LuismaSP89 We don't support any of those overrides because the way Xenia writes things to render target is extremely customized, especially in the ROV path where we aren't using the fixed-function output-merger hardware at all.
