### ISSUE TITLE
Diablo 3 does not accept inputs in menu

### ISSUE THREAD

**Issue by Ghostotakoi** [xenia-project/xenia#1290]
Does not matter what key i press i menu the "Press any button" does nothing just blink and don´t go ingame. i tried with keyboard and xinput controllers and same.
![screenshot_20181126185127](https://user-images.githubusercontent.com/20958581/49050127-ecd8c480-f1af-11e8-8c58-8d233f8cccdb.png)

**Comment by tetration** [comment]
I think this issue is supposed to be in the Xenia game compatibility
repository issues not here.
But anyways, are you using an official Xbox USB/Wireless controller or a
generic one?

**Comment by Ghostotakoi** [comment]
ok in latest build it was fixed, @tetration i use an usb xbox controller but also i tried keyboard
