### ISSUE TITLE
Many games not booting in D3D12_1656

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1292]
I tried Skate 3, Sonic Unleashed, and Spyro Dawn of the Dragon. Those games work fine in 1656

Many games do not work. When booting, I was asked about firewall settings. Could that be related to the problem? All of these games booted in version 1640

Here are the games that do not work, they all have black screens and crash in 1656:
[COD 4_mp XEX.log](https://github.com/xenia-project/xenia/files/2621253/COD.4_mp.XEX.log)
[COD 5 default_mp XEX.log](https://github.com/xenia-project/xenia/files/2621260/COD.5.default_mp.XEX.log)
[COD 6 Modern Warfare 2 default_mp.log](https://github.com/xenia-project/xenia/files/2621264/COD.6.Modern.Warfare.2.default_mp.log)
[COD 7 Black Ops.log](https://github.com/xenia-project/xenia/files/2621265/COD.7.Black.Ops.log)
[COD 8 Modern Warfare 3.log](https://github.com/xenia-project/xenia/files/2621266/COD.8.Modern.Warfare.3.log)

**Comment by niko1point0** [comment]
The games were fixed in 1658

**Comment by FateForWindows** [comment]
Hey, just a suggestion but it would be nice to try to use the commit id from now on instead of the build version, e.g. 919882dd instead of 1657 since Github will automatically link to the commit in question.

**Comment by niko1point0** [comment]
Ok. Thank you
