### ISSUE TITLE
Diablo III does not save

### ISSUE THREAD

**Issue by Ghostotakoi** [xenia-project/xenia#1294]
Diablo III does not save, i have played like 3 hours and when i close the emulator i realized it does not save, so i waste 3 hours... so sad, but well i hope it can be fixed soon.

**Comment by Margen67** [comment]
https://github.com/xenia-project/game-compatibility/

**Comment by tqrek** [comment]
[Uploading xenia.log…]()
diablo 3 no autosave no sound game bug hope you fixe this soon..
