### ISSUE TITLE
Idea to boost performance

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1297]
This is a last-resort idea for debugging purposes. Could there be an option where a user can set a maximum number of draw calls? This may boost FPS for many users

For example, the code could be something like this:

int drawCount = 0;
int maxDrawCount = 100;

if(drawCount < maxDrawCount)
{
       drawCount++;
       vkCmdDraw // for Vulkan
       ID3D12GraphicsCommandList::Draw // DirectX12
}

**Comment by Triang3l** [comment]
You won't be able to see anything most likely as the games are rarely rendered to the primary back buffer itself, and the composition stage of the frame won't be reached in this case.
