### ISSUE TITLE
Xenia Experimental 2x Resolution Scale bugs

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1303]
AppVeyor Build: 1.0.1666-d3d12
Didn't know how to find Github Build Version, sorry

A lot of games work fine, like Sonic Unleashed, Spyro Dawn of the Dragon, and Call of Duty 4.
However, Call of Duty Modern Warfare 3 can only render menus and loading screens. After entering gameplay, the HUD draws, but everything else is a black screen.

If anyone else has bugs with the 2x Resolution Scale, please post them so that our favorite developers can perfect this new feature.

![capture3](https://user-images.githubusercontent.com/7824443/49586609-79088b80-f916-11e8-8691-0740392ae568.PNG)

**Comment by Parovozik** [comment]
This works on x1 as default. Which key for initial 2x? Now any keys for command line not works for me.
I see "resolution_scale_2x_ = false" in source code and label "direct3d 12 - rov 2x" (for title of xenia window)
@niko1point0 i see your title as "direct3d 12 - rov" and think what there still x1 scale
Tell me how to use the keys now to run? Thx

**Comment by win98and95** [comment]
@niko1point0 
@Parovozik 
Append --d3d12_resolution_scale=2 to the executable path in your shortcut to the latest version of Xenia. Your GPU must support tiled resources and rasterizer-ordered views.

**Comment by niko1point0** [comment]
Wow, that was a silly mistake of me. 

I just added --d3d12_resolution_scale=2, and ran Modern Warfare 3 again. I got the exact same results as the screenshots above, still a black screen

I tested Sonic Unleashed with 2x resolution, there were some occasional white flashes on the screen. However, all vertex explosions that used to happen have now stopped happening.

Spyro Dawn of the Dragon runs mostly identical when ROV 2x is enabled and disabled

Call of Duty 4 runs fine with ROV 2x disabled.
With ROV 2x enabled, it runs mostly fine, but black polygons flash on the screen while aiming and shooting

**Comment by Crimsom13** [comment]
downloaded the build haven't seen a single game that runs in 2x scale.

**Comment by altiereslima** [comment]
Scale 2x does not work on RADEON R9 390

**Comment by TheCubeMaster019** [comment]
@altiereslima that's because the Radeon R9 390 does not support rasterized-order-views, or ROV.

**Comment by altiereslima** [comment]
> @altiereslima that's because the Radeon R9 390 does not support rasterized-order views, or ROV.

Ok

**Comment by LuismaSP89** [comment]
Eternal sonata: A kind of flashing of the half bottom screen all the time, else is perfect. This doesn´t happen in 1x.

Bayonetta: Entire screen black-flashing sometimes.

Resident evil 6: When ingame, only the HUD is rendered correctly, all is a blackscreen with exploding vertices. The game in 1x runs near perfect. (Except for a few minor bugs like characters with no face in cutscenes, and no laser-dot can be seen in the weapons)

All games runs incredibily slow with 2x: I can run cemu in 4k and rpcs3 too, I assume this is because this PR is only experimental and not perfectly implemented yet.

**Comment by xbox360pad** [comment]
Oh, damn it! I really wanted this feature. Unfortunately I bought an RX card last week and my card is not compatible. Only Vega cards are compatible on the AMD side. 

Will we be able to increase the resolution of games in the future with older graphics cards? Or is it only possible with cards that support Directx 12_1?

**Comment by Winchester7314** [comment]
Sonic the Hedgehog 2006 has weird shadow/light bugs that cause flickers with ROV 2x enabled.
