### ISSUE TITLE
"profile has been tampered with

### ISSUE THREAD

**Issue by bsalmeda** [xenia-project/xenia#1305]
Everytime it asks me to log in or skip, signing in doesnt worl, and when i use skip it says "gamer profile tampered with".

**Comment by Margen67** [comment]
In case it wasn't obvious enough:

# **`DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!`**

**Comment by gibbed** [comment]
It doesn't belong here unless you know specifically what is wrong with Xenia, ie function `X` is doing `Y` thing bad. If all you know is "game don't work" then it goes in game compatibility issues.

**Comment by zmp2000** [comment]
sadas

**Comment by domri7876** [comment]
I'm trying to play the Forza Motorsports titles and keep getting the "It appears your profile has been tampered with" popup before the emulator freezes.

**Comment by Fercb** [comment]
It appears your profile has been tampered with.

**Comment by Fercb** [comment]
> xenia's profile implementation right now is very barebones and incomplete. It's likely something that hasn't been implemented yet is required for this game. Which game is it btw?

Its Forza Motorsport 3.
