### ISSUE TITLE
The Start of an installer script

### ISSUE THREAD

**Issue by cbuteau** [xenia-project/xenia#1311]
[vulkan-master.zip](https://github.com/xenia-project/xenia/files/2701167/vulkan-master.zip)

Nothing is wrong.
I took this installer as far as I am going to take it.
I am sending it to you guys to whatever and deleting it out of my source tree...
so I can sync without errors.

I had it in <srcroot>\installers\vulkan-master.nsi

It is Nullsoft Scriptable Installer which should align with avoiding conflict.

Good luck...work looks promising.

you can mark this issue completed upon reading it.

**Comment by simontime** [comment]
![Thonk](https://user-images.githubusercontent.com/40786398/50326731-eab01e80-053f-11e9-8099-7d4eb64a03ee.png)

**Comment by tetration** [comment]
??????????????

**Comment by simontime** [comment]
It's just confusing...

>

**Comment by sharkboy1006** [comment]
yes we need a installer for 10 mb, including a exe and 2 other files.

**Comment by Prism019** [comment]
To be honest, you don't even need to include xenia.pdb if you're not doing debugging of xenia itself (most people), so it'd just be xenia.exe and the LICENSE.

**Comment by cbuteau** [comment]
Thank god...I didn't think it was confusing...
I started something I did not finish and I was letting it go.

Good Luck you guys you are doing good work.
