### ISSUE TITLE
Xenia crashes or stops responding if I try to switch to another game while it was already running a game

### ISSUE THREAD

**Issue by tetration** [xenia-project/xenia#1313]
Xenia crashes if I try to switch to another game when a game was already running. Now your guys might be wondering. Why did I post such kind of bug in here? Well because this behavior has not only happened when I was running Saints Row and tried to switch to Bejeweled 2, but also when I was running Fable 2 and tried to switch to Saints Row or when I was running Burnout Revenge and tried to switch to Bejeweled 2 and vice versa. I've replicated this bug with all the games I currently own, that are stored on my HD. Thus this leads me to my hypothesis, that this bug is likely to occur with any 360 games being emulated on Xenia.  It seems that the emulator has trouble switching between all Xbox 360 games if you try to switch without relaunching it.
 
Until Xenia's team fix this issue, the only way to safely switch between games is to always close the emulator and launch it again.

**Other observations:**

-It seems that the emulator sometimes just freezes instead of crashing.

Below I will be providing a crash dump when I was running Burnout Revenge and tried to switch to Saints Row
[xenia.log](https://github.com/xenia-project/xenia/files/2707327/xenia.log)

**Replicating the bug:**

In case your guys would like to replicate the bug in order to investigate it further all you have to do is to start running a game and then try to switch to another game. It seems that it doesn't matter which games you try to switch in between the emulator will always crash, give a black screen and stop responding or stop responding if you try to switch between games in the same session without relaunching the emulator.

**Comment by tetration** [comment]
People are using the confusing emoji on my thread. But seriously how was I supposed to guess that it was a duplicate of #665 ? Safe Thread Termination Support is not a very friendly name. Seriously when I was searching if this bug was already reported I would've never guessed someone would've already reported this bug with the name "Safe Thread Termination support".

I would suggest your guys to rename the original thread which is called "Safe Thread Termination Support"  to "Xenia crashes or stops responding if I try to switch to another game while it was already running a game" in order to avoid others to start new threads about the same bug in the foreseeable future.

**Comment by DrChat** [comment]
Yeah - this issue is already covered by that one. Xenia is unable to safely terminate at the moment due to the fact that we use HLE.
Main problem being that guest threads can hold host locks, and we need to be able to coerce the threads to release those locks before killing them.
