### ISSUE TITLE
Xenia just shows "The Guest has crashed", no matter what game I boot.

### ISSUE THREAD

**Issue by lcr29** [xenia-project/xenia#1319]
Just as the title says.
Here's the log:
[xenia.log](https://github.com/xenia-project/xenia/files/2789425/xenia.log)

**Comment by lcr29** [comment]
Tried the latest build, same problem.
[xenia.log](https://github.com/xenia-project/xenia/files/2789430/xenia.log)
Log from said build.

**Comment by Triang3l** [comment]
Totally not how issues should be reported (and the crash in Saints Row is well-known, check the issues in the game compatibility repo). The Vulkan renderer is not actively updated, by the way.

**Comment by lcr29** [comment]
lol amazing, i tried that command too and it does the same shit

**Comment by Triang3l** [comment]
--protect_zero=false? It's still an ugly hack, imagine if dereferencing a null pointer was not an error, that's what it does.

**Comment by win98and95** [comment]
There's an issue with sound device from my experience 
If there's no sound device (headphone,speakers, etc) plugged into your PC 
Xenia will crash no matter what game you try to load.

**Comment by lcr29** [comment]
> There's an issue with sound device from my experience.
> If there's no sound device (headphone,speakers, etc) plugged into your PC
> Xenia will crash no matter what game you try to load.

Guess it doesn't like the ancient speakers I use.

**Comment by ZolaKluke** [comment]
Do you get this icon on your taskbar?
![image](https://user-images.githubusercontent.com/6497775/51681440-adf0af00-2038-11e9-80eb-6cd12c03aa33.png)

**Comment by win98and95** [comment]
What game are you trying to run?
There's a lot of games that crashes on startup.

**Comment by lcr29** [comment]
> Do you get this icon on your taskbar?
> ![image](https://user-images.githubusercontent.com/6497775/51681440-adf0af00-2038-11e9-80eb-6cd12c03aa33.png)
Yes, of course.  Everything looks fine.


> What game are you trying to run?
> There's a lot of games that crashes on startup.
Saints Row

**Comment by ZolaKluke** [comment]
So if your speaker icon is like that then there is your issue you have no sound device or drivers

**Comment by win98and95** [comment]
what windows version are you running?

**Comment by Margen67** [comment]
#1967
