### ISSUE TITLE
yeet

### ISSUE THREAD

**Issue by humanmanyeet** [xenia-project/xenia#1320]

**Comment by humanmanyeet** [comment]
For d3d12 at least. For Vulkan It has MAJOR slowdown

**Comment by Margen67** [comment]
In case you somehow missed it even though it's literally the first thing you see when creating an issue:
# DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
# a game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
# A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
# For specific games, visit https://github.com/xenia-project/game-compatibility/issues

**Comment by ZolaKluke** [comment]
It's still strange to see vertex explosions in Sonic 06 last time I checked there were none
