### ISSUE TITLE
Improper Vulkan implementation of D3DDevice->Clear

### ISSUE THREAD

**Issue by niko1point0** [xenia-project/xenia#1325]
I compiled a triangle program with the Xbox 360 SDK

~~removed~~

This line of code is supposed to turn the background into a blue color. It works on the Xbox 360 Console, it works on the D3D12 build of Xenia, but it does not work on the Vulkan build of Xenia
~~Xbox360_Test1.zip~~

I uploaded the XEX file so that anyone can test it

**Comment by gibbed** [comment]
Utilizing the XDK for research is not acceptable.

**Comment by niko1point0** [comment]
I'm sorry, I did not know that XDK was against the rules. @gibbed could you tell me why it is not allowed? Microsoft released it publicly for free

**Comment by Triang3l** [comment]
@niko1point0 Microsoft never released it for free, it was leaked a few times. The reasons are explained in .github/CONTRIBUTING.md.

**Comment by gibbed** [comment]
If you can provide evidence that Microsoft has provided the Xbox 360 SDK publicly and freely available then please do so. But until we know otherwise, it's verboten as Triang3l has mentioned.

**Comment by niko1point0** [comment]
Thank you @Triang3l @gibbed, I understand now

**Comment by niko1point0** [comment]
https://sourceforge.net/projects/openxdk/

This is an open-source alternative. Could I use this instead?

**Comment by gibbed** [comment]
Certainly!

**Comment by niko1point0** [comment]
I figured it out, OpenXDK is for Xbox Original. My bad

**Comment by gibbed** [comment]
The point stands however, if you're able to replicate this issue in a sample compiled with an open source SDK for Xbox 360, then it's acceptable.

**Comment by niko1point0** [comment]
Thank you @gibbed
