### ISSUE TITLE
Xenia builds for Sonic 06 can't initialize Vulkan's graphic subsystem

### ISSUE THREAD

**Issue by nuskadamo** [xenia-project/xenia#1331]
first of all, i'm not sure if i should post this here since its a build made for a specific game, but the problem isn't about the game itself, so i'll suppose thats up to the mods to decide

still, i downloaded everything from this suggested video, https://www.youtube.com/watch?v=emUH6uFyOVg , followed the tutorial, but it tells me that it's unable to iniziatize Vulkan's graphic subsystem, a problem i don't have with the vanilla xenia
so i try to see if my GPU is compatible, it is, so i try to update the drivers (from the card's website too), nothing changes.
so a popular solution i found tells me to look for a certain file at System 32, but its nowhere
and now i'm kinda out of clues

**Comment by win98and95** [comment]
DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
IF YOU NEED HELP JOIN OUR [DISCORD](https://discord.me/xenia-emulator)!

**Comment by Triang3l** [comment]
No support is provided for custom builds. For Vulkan in general, you may also need to download the runtime from LunarG. Anyway, don't use the Vulkan renderer, it lacks like more than a half of graphics features of the console.
