### ISSUE TITLE
Download page not working?

### ISSUE THREAD

**Issue by missingpants** [xenia-project/xenia#1332]
https://xenia.jp/download/

Tried it with both the vulkan and d3d12. I have a windows10 with a 1080TI. 
Whenever I click on either of the links it just says the page isn't working and gives me an HTTP error 503
Did I miss a step or...?

**Comment by Prism019** [comment]
It works fine for me... AppVeyor may have had a hiccup, try again.

**Comment by missingpants** [comment]
> It works fine for me... AppVeyor may have had a hiccup, try again.

Tried it a dozen times. Same thing.

**Comment by win98and95** [comment]
Try these links
Vulkan
https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration:%20Release&pr=false
D3D12 https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-d3d12.zip?branch=d3d12&job=Configuration:%20Release&pr=false

**Comment by missingpants** [comment]
> Try these links
> Vulkan
> https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration:%20Release&pr=false
> D3D12 https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-d3d12.zip?branch=d3d12&job=Configuration:%20Release&pr=false

Same issue

**Comment by BenNottelling** [comment]
@missingpants Sounds like you have an issue on your end with you internet configuration
Here are the zip files from those links
[xenia-master.zip](https://github.com/xenia-project/xenia/files/2867491/xenia-master.zip)
[xenia-d3d12.zip](https://github.com/xenia-project/xenia/files/2867492/xenia-d3d12.zip)

**Comment by Prism019** [comment]
It may also be that a node in AppVeyor's CDN is down. It may come back up in a few hours, a day at most, I'd say.

**Comment by FateForWindows** [comment]
AppVeyor's CDN seems to be up and working fine for me. Just like to throw my two cents into here.

**Comment by Prism019** [comment]
Hmm, yeah. AppVeyor's status page reported no problems... It's probably on your end then, like Ben said.

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/53413857-942de900-39a3-11e9-8414-5f662ffb0782.png)
hmm works fine still

**Comment by FateForWindows** [comment]
This should probably be closed...
