### ISSUE TITLE
Custom Controls Support

### ISSUE THREAD

**Issue by someguy736** [xenia-project/xenia#1333]
I don't think anyone has suggested this yet (at least I couldn't find anything asking for it), but a custom controls dialog or .conf file would be very much appreciated. The keyboard controls are a little awkward as they stand now.

Also some way to use generic gamepads would be appreciated to. I tried x360ce but I couldn't get it to work at all.

**Comment by BenNottelling** [comment]
I used a gamesir controller and it worked just fine, so I believe any generic Xbox 360/one controller should work fine

**Comment by ZolaKluke** [comment]
I think by generic controller they mean like logitech

**Comment by NimbusSkye** [comment]
I second this. At the moment, a nice workaround involves key rebinding via registry editing, although you will have to restart each time you want to reset your keyboard layout.

**Comment by niko1point0** [comment]
I would also like custom controls

**Comment by mirh** [comment]
Until the new UI is out, you can use [x360ce](https://github.com/x360ce/x360ce).

**Comment by someguy736** [comment]
> Until the new UI is out, you can use [x360ce](https://github.com/x360ce/x360ce).

I already tried x360ce and it didn't work for me (which I mentioned in the original post....) because my gamepad must be incompatible.
