### ISSUE TITLE
audio bug 

### ISSUE THREAD

**Issue by Mangou0** [xenia-project/xenia#1340]
sometimes it works but often i cant hear anything except Music

**Comment by win98and95** [comment]
No game specific issue.
Please close thanks.

**Comment by chris-hawley** [comment]
Do you have any specific details? There are thousands of games across the Xbox 360 line up. Inside each game are multiple levels with many audio trigger events and sometimes thousands of unique audio files. "Sometimes it works" is like saying I live in the building and expecting you to know what specific building i'm talking about. We need specific details like "Load x game and go into y level and then you will experience z audio defect" 

We do know that surround sound audio is incorrectly handled in most cases. 
Also, check this site so you don't file a bug that we already know exists 
https://xenia.jp/compatibility/

**Comment by Mangou0** [comment]
Sorry rdr forgot

lör 9 mars 2019 kl. 19:44 skrev chris hawley <notifications@github.com>:

**Comment by chris-hawley** [comment]
> We need specific details like "Load x game and go into y level and then you will experience z audio defect"

**Comment by Margen67** [comment]
If it's specific to a certain game it belongs in the game compatibility issue tracker, not here.

**Comment by win98and95** [comment]
Oh and also what API were you using? So we can track down the issue.

**Comment by Mangou0** [comment]
And it seem to occur when I shoot the revolver and then I can only hear
music. It’s really enjoying. But if I play for a while (like 5 h just
having it on while I do other stuff) it will disappear

lör 9 mars 2019 kl. 19:48 skrev chris hawley <notifications@github.com>:

**Comment by Margen67** [comment]
https://github.com/xenia-project/game-compatibility/issues/108

**Comment by Triang3l** [comment]
No need for this kind of issues. If you want to create an issue about audio, post ideas regarding XMA decoding and optimization, audio processor interface reverse engineering and things like that.
