### ISSUE TITLE
Hi Win98 did you know hydro is queen

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [xenia-project/xenia#1343]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by win98and95** [comment]
Hello. You should read [this](https://github.com/xenia-project/xenia/raw/master/.github/ISSUE_TEMPLATE.md) before going any further. Thanks.

**Comment by ReaperOfSouls1909** [comment]
don't you try and counter troll me!

**Comment by ReaperOfSouls1909** [comment]
💩
