### ISSUE TITLE
problems with a game

### ISSUE THREAD

**Issue by XxsjrapsxX** [xenia-project/xenia#1344]
im having problem with this naruto game it has a giant x through it for some reason 
![image](https://user-images.githubusercontent.com/44506272/54482571-fc8e1e80-481b-11e9-8e05-c0827b24f7a3.png)

**Comment by EpicFoxx64** [comment]
Don't make issues about specific games. Put this into compatibility. If the game doesn't exist yet create a new one while following the template

**Comment by dinkstr** [comment]
Try using the Vulcan version of Xenia.

**Comment by Margen67** [comment]
@dinkstr It's spelt Vulkan.

**Comment by win98and95** [comment]
You should close this issue.

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/54485045-d46ce280-4850-11e9-97d6-e42b92112337.png)

**Comment by ReaperOfSouls1909** [comment]
![tumblr_o6vju5eXgp1ulw796o1_500](https://user-images.githubusercontent.com/18043258/54485056-15fd8d80-4851-11e9-9002-18ac0715d2d4.gif)

**Comment by XxsjrapsxX** [comment]
> Try using the Vulcan version of Xenia.

i cant my laptop has a amd firepro which has no support for vulkan

**Comment by XxsjrapsxX** [comment]
even if i do have support for it where would i get the vulkan drivers as i do not have them

**Comment by Margen67** [comment]
@XxsjrapsxX GitHub is not tech support. Close your issue.

**Comment by win98and95** [comment]
If you want help join our discord.
https://discord.gg/Q9mxZf9
