### ISSUE TITLE
I can't play sonic unlished

### ISSUE THREAD

**Issue by vinicius13000** [xenia-project/xenia#1345]
because when I press start and press save the game stops capturing my controller
I saw  the same problem but that solution can't be applied for my inssue
because my AMD rx550 doesn't have support for vulkan

**Comment by 0x8080** [comment]
1. Make sure you're using the latest drivers from[AMD]( https://www.amd.com/en/support) because GCN 4.0 does support Vulkan and the default driver windows uses are fucking garbage

2. Use the d3d12 branch of Xenia

**Comment by ReaperOfSouls1909** [comment]
did you know end users are like poop they can't float cause they are so full of shit most times for never reading and yes not floating isn't heathy

**Comment by win98and95** [comment]
Is this why a [Discord](https://discord.gg/Q9mxZf9) exists?

**Comment by vinicius13000** [comment]
I'm Brasilian and I don't speak english well but I know when i'm in a toxic community
Please i ask the help of you the holders of the knowledge
my driver is up to date
![Anotação 2019-03-23 185236](https://user-images.githubusercontent.com/48868721/54872055-df69ca80-4d9c-11e9-98b2-6b86078c9f89.jpg)
when i press any button the mesage disappears and the game stops responding to the gamepad

**Comment by win98and95** [comment]
Github issue are not a place for help.
If you need help join our [Discord](https://discord.gg/Q9mxZf9) server.

**Comment by Triang3l** [comment]
The right place for game-related issues is the xenia/game-compatibility repository (search for Sonic Unleashed in the issue tracker there). We're aware though that both the dialog pop-ups and profiles are implemented in a terribly broken way.
