### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by PG3DDatabase** [xenia-project/xenia#1346]
the program wont install

**Comment by EpicFoxx64** [comment]
Don't need to install xenia. It's just click and play.

**Comment by EpicFoxx64** [comment]
If you're trying to open xenia and nothing happens it means you don't have the minimum requirements

**Comment by PG3DDatabase** [comment]
what i mean is that in the video i need to download it and then pressing
file, open and then the game i want but i dont get to open the .exe file


Op za 23 mrt. 2019 om 23:45 schreef EpicFoxx64 <notifications@github.com>:

**Comment by win98and95** [comment]
Github is not a place for help.
If you need help join our [Discord](https://discord.gg/Q9mxZf9) server.

**Comment by Triang3l** [comment]
You need Windows 10, a Direct3D 11-compatible graphics card and a CPU with AVX instruction set support (for Intel, that's Core i-series).
