### ISSUE TITLE
Halo 3 Beta?

### ISSUE THREAD

**Issue by sethandthecrew** [xenia-project/xenia#1347]
I really don't know where to summit a game to get it compatible on the emulator so i hoping if anyone could get these builds of Halo 3 would be good enough.

Thanks.

**Comment by ZolaKluke** [comment]
The normal Halo 3 doesn't work so I doubt these beta builds would, also Xenia doesn't do game specific fixes they will fix an issue system wide which may help Halo 3. Also DON'T POST LINKS TO GAME DOWNLOADS

**Comment by sethandthecrew** [comment]
Thanks, i made a few mistakes. i wont post links again. also i saw i vid of Epsilon on Xenia btw

**Comment by win98and95** [comment]
Can you close this issue and submit these to the game compatibility list?
