### ISSUE TITLE
Vulkan only shows white 3d graphic

### ISSUE THREAD

**Issue by psennermann** [xenia-project/xenia#1349]
On my system (Win10, Intel i7 7700, Nvidia GTX1060 3gb), the Vulkan plugin renders everything white, except 2d screens (down below I posted an image of the intro of RDR so you can see that 2d graphic is almost fine, while 3d graphics is always white like it is when you try to play the game).
The build is: Build: detached / 84b8b444cf2c2544e959c6fc83dd35fa9cd4b14a on Apr  5 2019

Dx12 instead shows everything fine

![image](https://user-images.githubusercontent.com/6342467/55683043-55dcff80-593b-11e9-8e71-6266dca0dafb.png)

**Comment by EpicFoxx64** [comment]
Don't create new issues and stuff thats already known. If you wanna help, add stuff to the compatibilty https://github.com/xenia-project/game-compatibility/issues/108

**Comment by psennermann** [comment]
Well there wasn't yet an issue about the broken Vulkan plugin, so I thought it would be right to have at least one...

**Comment by win98and95** [comment]
Revert this commit https://github.com/xenia-project/xenia/commit/8064926999b0cdd7633dab3a5423149ffb8b83dc 
![image](https://pbs.twimg.com/media/D2Wr3Y6UcAcQ32a.jpg)

**Comment by Triang3l** [comment]
The old renderer barely has any functionality for framebuffer/eDRAM emulation, do not use it. The Direct3D renderer is a full architectural rewrite, not just a small backend plugin.
