### ISSUE TITLE
halo 3 crash information

### ISSUE THREAD

**Issue by chris-hawley** [xenia-project/xenia#1355]
i'm putting this here so we can persist the information outside of discord.

What's happening: Halo 3 crashes.

Where: On Sierra 117, if you start at the beginning and run to the end, it'll crash at rally point bravo. 
 On Crow's nest, if you start at mission start, it'll crash back in the hallway after clearing the hanger. 

Each time I run it through the debugger, the crash happens at different points so i'm thinking that it's as a result of undefined behavior and/or memory corruption somewhere. I compiled Xenia with Spectre mitigations and that causes the crash to happen sooner so maybe that means it picks up on the problem earlier. I don't know how to proceed on debugging this since it's not always in the same spot.

So far, the debugger as shown the crash in the logging system, switching contexts (in window kernel) and callimpl. Since all of those happen numerous time a second, i'm not sure what kind of corner case wouldn't be found fairly quickly and only occur at certain points.

**Comment by ReservedRegister** [comment]
This the same as https://github.com/xenia-project/xenia/issues/1342

**Comment by chris-hawley** [comment]
Is it though? This bug report seems different from that one.

**Comment by ReservedRegister** [comment]
It was first to be assumed as a memory leak now its confirmed its not and its a treads invalidation issue which is the same issue as this because I know what you mean, look at the YouTube videos.

**Comment by emoose** [comment]
Per-game stuff goes in the game-compatibility repo, so for Halo 3 that'd be in https://github.com/xenia-project/game-compatibility/issues/178

You should maybe attach the xenia.log too, if you have one.

**Comment by chris-hawley** [comment]
@ReservedRegister the other one needs to be updated to more explicitly state the problem. I'll just copy and paste my bug into that one and close this one.

**Comment by ReservedRegister** [comment]
The title is changed and I did say that memory leak did not fix it.
