### ISSUE TITLE
xbox 360 software is aged. free to use.  software is free after x years. that is why xbox one is

### ISSUE THREAD

**Issue by smartxann** [xenia-project/xenia#1359]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by ReservedRegister** [comment]
I think you did not finish your sentence.

**Comment by smartxann** [comment]
Nevermind.  Legal construction is license to use.
