### ISSUE TITLE
Enable full xbla games / license_mask_ptr=1 not working

### ISSUE THREAD

**Issue by elhecht** [xenia-project/xenia#1360]
According to the faq (https://www.reddit.com/r/xenia/wiki/faq) to enable full xbla games i need to modifiy file **xam_content.cc** and change **license_mask_ptr = 0** to **license_mask_ptr = 1**

I tried out with the latest version on branch d3d12, but games are still in trial/demo mode.

**Comment by ZolaKluke** [comment]
The proper change for it is **mask_ptr = 0xFFFFFFFF**, your better off asking questions like this on the Xenia discord server though, just to let you know for next time

**Comment by win98and95** [comment]
Tell that to @Margen67 😹

**Comment by elhecht** [comment]
OK, changing mask_ptr to 0xFFFFFFFF makes the game now full playable. Thanks, and see you next time on discord ;-)
