### ISSUE TITLE
Consider updating Capstone to 4.0

### ISSUE THREAD

**Issue by TranzRail** [xenia-project/xenia#1364]
Version 4.0 includes the following (in relation to Xenia):

- Change cs_ppc_op.imm type from int32_t to int64_t.
- Add new groups: PPC_GRP_ICBT, PPC_GRP_P8ALTIVEC, PPC_GRP_P8VECTOR & PPC_GRP_QPX.
- Lots of new instructions (QPX among them)

See changelog [here](http://www.capstone-engine.org/Version-4.0-changelog).

**If attempting to do so, even in the lab, you'll need to see this [here](https://github.com/aquynh/capstone/issues/1315).**

**Comment by gibbed** [comment]
Those changes don't seem relevant to us, but that doesn't mean we can't upgrade to 4.0 at some point.

**Comment by Margen67** [comment]
Fixed by #1387
