### ISSUE TITLE
Red Dead redemption Vulkan White screen

### ISSUE THREAD

**Issue by thxcyber** [xenia-project/xenia#1375]
Hii my sys requirment are 
Intel i5 4690k 
Nvidia gtx 970 asus stix oc edition 4gb
16gb ram
Xenia vulkan version are full of white screens

**Comment by maxton** [comment]
This repository is not for game-specific issues. Also, this issue was already discussed at #1338. Vulkan is out of date.

**Comment by Triang3l** [comment]
The Vulkan renderer is unsupported and heavily outdated, and does a very approximate attempt at emulating actually writing pixels to images and the screen. If any things work on it, it's largely because of luck.
