### ISSUE TITLE
gpu no load when playing RDR ( d3d12 )

### ISSUE THREAD

**Issue by zwkylkx** [xenia-project/xenia#1376]
cpu : ryzen 5 1600
gpu : gtx 1060 6gd5
![UNtitle](https://user-images.githubusercontent.com/51225320/58718839-ef3b0600-8400-11e9-968e-a14b71b99115.png)

**Comment by win98and95** [comment]
GitHub is not a place for support.
Join our discord server for support.
https://discord.gg/5g93S8H

**Comment by zwkylkx** [comment]
> GitHub不是支持的地方。
> 加入我们的不和谐服务器寻求帮助/支持。
> https://discord.gg/5g93S8H

ok,thanks

**Comment by Razzile** [comment]
This is most likely a bug with Windows incorrectly reporting GPU usage. A tool like MSI afterburner may be more accurate

**Comment by zwkylkx** [comment]
> This is most likely a bug with Windows incorrectly reporting GPU usage. A tool like MSI afterburner may be more accurate

but fps lower than 10

**Comment by Margen67** [comment]
> 
> 
> GitHub is not a place for support.
> Join our discord server for help/support.
> https://discord.gg/5g93S8H

**Comment by Triang3l** [comment]
> 
> 
> > This is most likely a bug with Windows incorrectly reporting GPU usage. A tool like MSI afterburner may be more accurate
> 
> but fps lower than 10

CPU: 33%.
