### ISSUE TITLE
Controller mapping!!!

### ISSUE THREAD

**Issue by Mechanical-sanity** [xenia-project/xenia#1378]
Xenia needs a good controller mapper. I have a generic pc controller, but I can't use it to play xenia. so can someone add some good controller mapping?

**Comment by Ulquiorr4-Cifer** [comment]
Use [x360ce](https://github.com/x360ce/x360ce) to make your controller appear as xbox360 controller, that way it will work with xenia

**Comment by Margen67** [comment]
Duplicate of #1333
