### ISSUE TITLE
UserProfile::SaveSetting directory issue

### ISSUE THREAD

**Issue by BiatuAutMiahn** [xenia-project/xenia#1381]
When saving profile settings, if target file is a directory, this function will fail.

**Comment by Jeremy517** [comment]
@BiatuAutMiahn Do you have steps to reproduce this issue?  What game were you trying?

**Comment by BiatuAutMiahn** [comment]
`Conten/<TitleID>/profile/User/63E83FFF` create a folder called `63E83FFF` instead of letting Xenia create a file there. 

I tried this because I found out that Xenia was creating a file inside of cache0 called autosave, when instead it should have been a directory. However that issue was fixed by #1403

**Comment by Jeremy517** [comment]
I'm a little confused.  Are you saying that you manually created a directory there?

**Comment by BiatuAutMiahn** [comment]
Yes, as a test.

**Comment by Jeremy517** [comment]
That isn't a bug, it is user error.  You are randomly manually messing with Xenia content directory.  What is stored in that directory isn't ever a directory, it is just a file containing the contents of a buffer.

**Comment by BiatuAutMiahn** [comment]
I understand the purpose of the directory, I discovered this behaviour during debugging halo 3 and the cache1 directory. I was just pointing out that if for whatever reason, if a directory existed instead of a file, this function would fail. (Just as cache1://autosave being created as a file instead of a directory did)
