### ISSUE TITLE
GAME CRASH

### ISSUE THREAD

**Issue by kainzus** [xenia-project/xenia#1390]
the superman returns game close the xenia i dont know why doesnt work is a game very old 2006

**Comment by jacob1218** [comment]
Xenia is still being worked on, so some games don't work yet. Post your xenia.log file here

**Comment by Margen67** [comment]
In case you missed it:
> # DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
> a game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
> A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
> For specific games, visit https://github.com/xenia-project/game-compatibility/issues
>THIS IS NOT A SUPPORT FORUM! For support go here:
>Xenia Discord (#help) - https://discord.me/xenia-emulator
> /r/xenia (questions thread) - https://www.reddit.com/r/xenia/
