### ISSUE TITLE
Performance increase dependent on launch method!?!?

### ISSUE THREAD

**Issue by DickieUK** [xenia-project/xenia#1393]
Hi All,

Can someone please verify if they get the same results or if there is a known reason for the below behavior?

Example;

I have Burnout Revenge in a folder as BurnoutRev.000 & BurnoutRev.dvd.

If i double-click BurnoutRev.000, select Xenia.exe when windows asks me to select an application to open the file (for the first time), the game will run all FMV smoothly, and i will see improved FPS and Input response during gameplay, with the addition of a small amount of artifact across the top of the screen.... 

If i launch the game from within Xenia, the FMV lags behind the audio, and my FPS is lower and response. Can anyone else confirm/explain this??

**Comment by SmajloSlovakian** [comment]
It looks like it doesn't work for me.
