### ISSUE TITLE
problem with dragonball Z ultimate and raging blast

### ISSUE THREAD

**Issue by digilie420** [xenia-project/xenia#1412]
everytime i open xenia and go to file and open my game: "dragonball Z ultimate tenkachi", i can skip the intro with the start button on my gamepad but if i go to the main menu and they say: "press the start button"
![Schermopname (3)](https://user-images.githubusercontent.com/53193099/61993653-24657c80-b06f-11e9-960d-4e29dbd1482c.png)
. i can't do it 

the same with the game dragonball Z raging blast 2

**Comment by digilie420** [comment]
ow sorry

**Comment by illusion98** [comment]
THIS IS NOT A SUPPORT FORUM! For support go here:
Xenia Discord (#help) - https://discord.me/xenia-emulator
 DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
