### ISSUE TITLE
Graphis Device lost(probaby due to an internal error) xenia dx12

### ISSUE THREAD

**Issue by EmulationChannel** [xenia-project/xenia#1422]
Graphis Device lost(probaby due to an internal error) Games Red Dead Redemptiom and Red Dead Redemption Undead Nightmare https://github.com/xenia-project/xenia/commit/5af61b56d2b0ae809f345fab875ffde0e94cb353
[xenia.zip](https://github.com/xenia-project/xenia/files/3469583/xenia.zip)
https://streamable.com/l16hd
![SharedScreenshot10](https://user-images.githubusercontent.com/52056267/62498633-44571780-b7b6-11e9-872d-61459225758a.jpg)
![SharedScreenshot7](https://user-images.githubusercontent.com/52056267/62498637-47520800-b7b6-11e9-87da-5fa723d8e700.jpg)

**Comment by EmulationChannel** [comment]
invalid @Margen67 ?????

**Comment by EmulationChannel** [comment]
This is trouble and serious

**Comment by Margen67** [comment]
Game-specific issues belong on the game-compatibility issue tracker.

**Comment by EmulationChannel** [comment]
this friendless compatible issue and issues in build xenia API DX12

**Comment by Margen67** [comment]
https://github.com/xenia-project/game-compatibility/issues/108

**Comment by Triang3l** [comment]
This may be caused by a million reasons, so invalid.
