### ISSUE TITLE
Xenia silently fails with invalid launch parameters

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#1445]
Currently, xenia doesn't give any sort of error or indication that an invalid launch parameter was used, and just closes itself.
This leads to end-users asking why their outdated/invalid launch parameters don't work.

**Comment by x1nixmzeng** [comment]
What launch paramters does xenia require to boot? Fallback options should be enough rather than opening showing an error message

**Comment by Margen67** [comment]
Falling back to the default would only be a good idea if xenia gives you an indication that it did so.

**Comment by Razzile** [comment]
should xenia just ignore invalid launch parameters or should it actually error out. or maybe a middle ground where it prints a warning but continues?

**Comment by Margen67** [comment]
@Razzile If you fall back without letting the user know then they'll still get confused.

**Comment by gibbed** [comment]
Should be resolved since #1634 is now merged.
