### ISSUE TITLE
not loading games with dx12

### ISSUE THREAD

**Issue by Lexpartizan** [xenia-project/xenia#1456]
Vulkan working, load games, but graphics pure and slow.
If i try load games with dx12 (all settings default), xenia crashed without explanation .
If i try debug with MS Visual Studio 2017, i have this message:

Unhandled exception at 0x00007FF993B6C630 (nvwgf2umx DLL.dll) in xenia.exe: 0xC0000005: read access violation at 0x0000000000000000., happened

Early releases, six months ago, dx12 worked for me. I attached working release, but new releases crushed.
[EmuCR-xenia-d3d12-2019-05-13.zip](https://github.com/xenia-project/xenia/files/3547290/EmuCR-xenia-d3d12-2019-05-13.zip)

**Comment by Triang3l** [comment]
Try updating the GPU driver, what GPU do you have though? Nvidia driver should be very stable, never had any issues on 1070 (though had total system freezes on 850M, but that was worked around, and that wasn't a null pointer access either).

**Comment by Lexpartizan** [comment]
When I get back from work, I will make a video of this process to confirm.
CPU -Ryzen 2600
GPU nvidia 1050. Drivers not latest, but everything work stable.

**Comment by Lexpartizan** [comment]
Another releases later than May 2019 do not work either.

**Comment by Lexpartizan** [comment]
Video
https://youtu.be/RYYHVoHxhkA

**Comment by Parovozik** [comment]
> 
> 
> Another releases later than May 2019 do not work either.

Most likely your Windows is outdated. You uses 1607, 1809 or 1903 core update?

**Comment by Lexpartizan** [comment]
Yes, my win10 ver 1607.

**Comment by Lexpartizan** [comment]
Pirate edition my reason.

**Comment by TGLTClutch** [comment]
Piracy -_- ... Also you can get windows 10 for free using media creation tool with all features. There will just be a "Activate Windows" watermark on the bottom right.

**Comment by Lexpartizan** [comment]
What for? Pirate Repack more useful and familiar. Again, this problem is the first in 20 years of using pirated versions of Windows.

**Comment by Margen67** [comment]
You're using outdated versions of Windows 10 and NVIDIA drivers. What do you expect?

**Comment by Parovozik** [comment]
> 
> 
> Yes, my win10 ver 1607.
Its your reason. You need minimum 1809 core update of Windows for latest Xenia revisions.

**Comment by Lexpartizan** [comment]
Thanks.
