### ISSUE TITLE
Full screen 16:10 problem

### ISSUE THREAD

**Issue by pitkevich80** [xenia-project/xenia#1460]
Hmmmmm is it possible to fix problem for 16:10 monitors? 
Maybe add some black bars ? When i make full screen, everything is going tall. (Long). 
For example everything circle become oval. That really bad.

**Comment by illusion98** [comment]
Your solution is to 
1. Set your desktop resolution to be in 16:9 aspect ratio.
2. Implement `DXGI_SCALING_ASPECT_RATIO_STRETCH` into the D3D12 renderer

**Comment by pitkevich80** [comment]
everything is going blur for me if make 16:9 monitor.  ;)

**Comment by illusion98** [comment]
Set the scaling mode? 
![](https://cdn.discordapp.com/attachments/308207592482668545/617671873152417793/wQTwOh4.png)

**Comment by pitkevich80** [comment]
yup, no matter option. Only 16:10 work perfectly for me. 
other options blur

**Comment by pitkevich80** [comment]
one moment , i will check some

**Comment by pitkevich80** [comment]
so should add DXGI_SCALING_ASPECT_RATIO_STRETCH under d3d12 xenia config?

**Comment by pitkevich80** [comment]
or what is mean "DXGI_SCALING_ASPECT_RATIO_STRETCH" ??

**Comment by pitkevich80** [comment]
hmm "desktop resolution to be in 16:9 aspect ratio." doesn't help too. 
Still launch with stretched full screen. (same like before).

**Comment by Margen67** [comment]
That option won't help since xenia doesn't use exclusive fullscreen.
You can't add `DXGI_SCALING_ASPECT_RATIO_STRETCH` to the config. You would need to code it in.
Also, stop spamming posts. Use the edit button.

**Comment by pitkevich80** [comment]
Ok, got it.

**Comment by Margen67** [comment]
Superseded by #1477.
