### ISSUE TITLE
Parameter "license_mask" not working on xenia

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-project/xenia#1471]
The parameter "license_mask" when is set to "license_mask = - 1" enable the full xbla games, but this is not working at least for some games. This can be seen for example in "Syberia" game. The game is showing the "enable full game" when the main menu is reached. This was tested long time ago with a hacked build in order to activate the full games, but in this case, this param is not working on xenia.

**Comment by Prism019** [comment]
There isn't supposed to be a space between - and 1... it's supposed to be `license_mask = -1`

**Comment by LuismaSP89** [comment]
Sorry. It's just a typo when I writed the issue. I have the = -1 but it doesn't work.

**Comment by illusion98** [comment]
Have you tried `1`?

**Comment by LuismaSP89** [comment]
Nope, I think = 1 is not a valid parameter. At least in the xenia faq and the options page:

https://github.com/xenia-project/xenia/wiki/FAQ

https://github.com/xenia-project/xenia/wiki/Options

**Comment by Margen67** [comment]
```license_mask = 0                        	# Set license mask for activated content: 0 - disable all licenses / 1 - enable the first license - usually the full version license in Xbox Live Arcade games / -1 or 0xFFFFFFFF - enable all possible licenses.```

**Comment by LuismaSP89** [comment]
Strange... it works too for other games? I tester undead nightmare in RDR but it needs internet connection to be enabled.

Ps: I'll test the = 1 paremeter when I arrive home. Thanks for the help.

**Comment by LuismaSP89** [comment]
And maybe the faq and the options page must be updated to show the = 1 parameter.

**Comment by LuismaSP89** [comment]
Ok, can confirm that the parameter "= 1" works fine with syberia, but other games such as RDR undead nightmare prompts for a internet connection in order to activate.

**Comment by Margen67** [comment]
This section has been updated to accomodate for this https://github.com/xenia-project/xenia/wiki/Options#run-games-as-fullactivated
