### ISSUE TITLE
D3D12 artifacts under ROV[SOLVED]

### ISSUE THREAD

**Issue by backgamon** [xenia-project/xenia#1475]
On all games with ROV there are artifacts on 3D models:
https://youtu.be/W905n1ESuMs
-------------------------

With the 2x render i have less:
https://youtu.be/i8l6BuOCHgE

-------------------------
And with RTV/DSV no more artifacts:
https://youtu.be/AjobbkVzSu8

Windows 10 x64 1903
Gigabyte RTX 2070 OC - 436.15
Asus Maximus X Formula
32Gb  Trident Z RGB DDR4 3466Mhz(at 3200Mhz).

**Comment by EpicFoxx64** [comment]
Rtx cards have issues with xenia after driver version 419.xx

**Comment by gandalfthewhite19890404** [comment]
Need to find another (not Xenia, maybe application or game) test-case and submit bug to NVIDIA.

**Comment by backgamon** [comment]
Currently i don't have,except Xenia, same or approaching problem .

**Comment by ZolaKluke** [comment]
The same issues happens on RTX cards on the PSP emulator called PPSSPP so most likely a Nvidia bug

**Comment by gandalfthewhite19890404** [comment]
Emulators are bad test-cases for NVIDIA.

**Comment by backgamon** [comment]
> 
> 
> The same issues happens on RTX cards on the PSP emulator called PPSSPP so most likely a Nvidia bug

I just checked somes games on PPSSPP, and i don't have any artifacts :/

**Comment by Razzile** [comment]
I can also confirm that RTX drivers are the cause. I went from a GTX 980 Ti to an RTX 2070S and the artifacts only appear on the latter

**Comment by gandalfthewhite19890404** [comment]
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/316371/rasterizer-order-views-rtxdriver42531-causes-issu/

**Comment by Squall-Leonhart** [comment]
Break down the code to a minimized test case

**Comment by gandalfthewhite19890404** [comment]
Here is some info - https://devtalk.nvidia.com/default/topic/1060807/opengl/-windows-possible-driver-bug-fragment-shader-interlock-has-almost-no-effect-on-rtx-gpu-driver/

**Comment by KBouder** [comment]
Can confirm, have RTX 2070 and have same issues, affect all games that I've tested except Geometry Wars 2, maybe because of the way that they render their graphics? Hard to say.

**Comment by KBouder** [comment]
Is this something that NVidia has/should fix, or is this going to fall on one of the amazing people behind Xenia? I would really hope that it isn't the latter.

**Comment by backgamon** [comment]
As i said above - u can (sort of) fix issue with --d3d12_edram_rov=false.
On RTV/DSV no issue at all, but loose the 2x render.

**Comment by gandalfthewhite19890404** [comment]
Also you loose half of performance, I had 60 fps, with RTV - only 30.

**Comment by backgamon** [comment]
With new 440.97 -> Problem SOLVED:

![Screenshot - 22_10_2019 , 20_21_11](https://user-images.githubusercontent.com/39404647/67317026-c3cccb00-f509-11e9-8702-71c516d38642.jpg)
