### ISSUE TITLE
[UI/GPU] Preserve Aspect Ratio

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#1477]
The current behavior of xenia is to stretch games instead of preserving the aspect ratio with black bars. This is undesirable, especially on ultrawide+ displays.
Integer scaling would also be nice.

Related: #1460, #1227

**Comment by Triang3l** [comment]
Fixed in https://github.com/xenia-project/xenia/commit/0be0eb2b381948df605863ca16adfd7d771e2ee0, also trying to crop to up to 90% of the original image before adding black bars.
