### ISSUE TITLE
forza horizon 1 bad or umimplemented file io calls

### ISSUE THREAD

**Issue by BardiaMGTGC** [xenia-project/xenia#1478]
forza horizon 1 gives
 "There's been an issue reading content from the game disc.
This is likely caused by bad or unimplemented file IO calls."
while launching 
i saw some videos and others running the game
[xenia.log](https://github.com/xenia-project/xenia/files/3627332/xenia.log)

**Comment by Margen67** [comment]
Game-specific issues belong in in their respective [game-compatibility](https://github.com/xenia-project/game-compatibility) report.
