### ISSUE TITLE
Pleas add primary GPU selection, i can start have on notebook with Optimus Nvidia+Intel.

### ISSUE THREAD

**Issue by ruthan** [xenia-project/xenia#1480]
Hello,
i copy already worked installation from other machine and tried Windows 7/10 on Core i7 7700 + Geforce 1050 TI machine with Nvidia optimus, i set Nvidia as primary GPu in invidia panel, but im still getting black screen in all games which i tried - Gears 2 / Forza Horizon for example, DX12 / Vulkan.
   You should also add some DX12 is not supported on Windows 7 dialog, its trying to start even with this settings, which is not possible, until MS will free DX12 for WIn 7 for everyone..
  
  I tried official and custom builds, lots of versions.

**Comment by Razzile** [comment]
I'm not quite sure what you're trying to say but xenia should be set up to tell nvidia optimus to use the dedicated GPU always

**Comment by randprint** [comment]
DX12 won't work in win7 that should be obvious, and gears 2 and forza only work in xenia-canary and as far as I know they are untested with Vulkan

**Comment by illusion98** [comment]
You can change GPU in the config file in `documents/xenia` with d3d12_adapter.

**Comment by Margen67** [comment]
It already says so on the download page:
![image](https://user-images.githubusercontent.com/3462541/65300785-8c918580-db29-11e9-8abb-eea96fffb8e6.png)
It's not our fault some people can't read.

**Comment by ruthan** [comment]
I know that is on download page, its there is no reason why is not make it handled in code.. it cant work.

 I tried web version and also AlexVS builds, there are working with Gears 2, Gears 3 forza 1+2etc.. i tried Blood Forge too, its able to reach at least menu with web version, but on this machine.. i have always with any setting with build working on other machine, everytime just black screen.
  RPCS is working fine.. i really thing that is because of Optimus, that is Intel HD 630, intead Geforce 1050 TI used.
  Everything is updated to last versions.

  I config for DX12 is for example this:
d3d12_adapter = -1 # Index of the DXGI adapter to use. -1 for any physical adapter, -2 for WARP software rendering.

Same with Vulka part:
[Vulkan]
vk_device = -1                          	# Index of the Vulkan physical device to use. -1 to use any compatible.

  How its working even you have 2 GPus in system? Or maybe emulator not even counts with 2 Gpus situation.

**Comment by Margen67** [comment]
If you're referring to D3D12on7 xenia doesn't support that.
Also, GitHub is not for tech support. Go to our [Discord server](https://discord.gg/5g93S8H) for that.

**Comment by ruthan** [comment]
I looked into log, problem can be elsewhere (its from Win7):
!> 00000028 LoadLibrary(XAudio2_8.dll) failed
!> 00000028 ResolvePath(ShaderDumpxe:\CompareBackEnds) failed - device not found
!> 00000028 ResolvePath(\Device\Harddisk0\) failed - device not found
!> 00000028 ResolvePath(cache:\) failed - device not found
!> 00000028 ResolvePath(\Device\Harddisk0\) failed - device not found

  I have emulator and images on crypted - Truecrypt / Veracrypt volumes, so far in 10+ years of usage, i havent problem with any WIndows program with it.. Its should be transparent with Windows as any other volume. So i suspect that there would be probably some problem if someone is using Bitlocker.

**Comment by dany5639** [comment]
"Im using lots of other emulators, they are fine with crypted volumes." Xenia is unlike any other emulator.
