### ISSUE TITLE
GPU Backend - Confusion with Vulkan

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [xenia-project/xenia#1484]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

Currently xenia has two Vulkan backends - Vulkan Prototype and Vulkan.
Vulkan prototype activates by setting gpu = 'vk'  in configuration file.
Vulkan activates by setting gpu = 'vulkan'.

It brings confusion and needs to be replaced by more understanding settings, for example:
vulkan_prototype (or vk_prototype) and vulkan (or vk)

**Comment by Razzile** [comment]
Right now neither vulkan backend should be used as one is obsolete and not maintained and the other is still a work in progress. Some games may work better with the old vulkan backend but if that's the case it should be reported in their compatibility issue that it's buggier with D3D12

**Comment by Margen67** [comment]
Documentation says not to use it: https://github.com/xenia-project/xenia/wiki/options#vulkan

**Comment by gandalfthewhite19890404** [comment]
So if we have not to use it - it should be completely disabled, with removing all related stuff from configuration file,

**Comment by Margen67** [comment]
It's still useful in certain cases where d3d12 doesn't work. A good compromise would be a notification/alert telling the user that Vulkan is deprecated or something since people can't read.
