### ISSUE TITLE
Xenia doesn't generate log when lauching from a container.

### ISSUE THREAD

**Issue by illusion0001** [xenia-project/xenia#1485]
# Expected behavior 
Xenia creates a log file after launching from a container with "Open With" menu (GoD, STFS)

# Current behavior 
Xenia doesn't create any log file launching from a container.

See GIFs below.
<details>
<summary>GIFs (click to expand)</summary>

Starting Xenia from a container 

![](https://i.imgur.com/56tRTD1.gif)

Starting Xenia from a executable

![](https://i.imgur.com/9iEH2Aq.gif)

</details>

**Comment by Razzile** [comment]
Chances are xenia does create a log but it's in a different folder due to "Open with..." not starting xenia in the current/expected folder
