### ISSUE TITLE
Multiple key presses in some games

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [xenia-project/xenia#1492]
Some games has issues with multiple key presses.
Title list:
- Diablo 3

But it is input backend dependent and its need to be tested.
I tested with:
- XInput via x360ce - impossible to play, one single press equal multiple.
- winkey - pressing and holding equal multiple but not such aggressive as with xinput via x360ce.

Need to test native xinput with compatible gamepad.

**Comment by illusion98** [comment]
Do not create a game specific issue in this repository
A game specific issue belongs in it's thread. xenia-project/game-compatibility#1114
