### ISSUE TITLE
Sorry for asking but guys can you please fix wwe 2011" save and wrestlemania problem"

### ISSUE THREAD

**Issue by Marko214** [xenia-project/xenia#1502]
### **

[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by illusion98** [comment]
Can't read? `THIS IS NOT A SUPPORT FORUM!`
