### ISSUE TITLE
vcruntime140_1.dll was not found

### ISSUE THREAD

**Issue by cxqx3998** [xenia-project/xenia#1521]
I have downloaded Xenia about 10 times now hoping that itll load and work but i keep getting this same error. I know the app should work perfectly upon load,

**Comment by Margen67** [comment]
Tech support belongs on the [Discord server](https://discord.gg/5g93S8H), but since people can't read and are going to probably make an issue like this again, I'll leave the answer here:

>Make sure you downloaded a Release build of Xenia, and download the latest x64 Microsoft Visual C++ Redistributable: https://aka.ms/vs/16/release/vc_redist.x64.exe
Latest Release Xenia build:
https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration:%20Release&pr=false

**Comment by syfer-darknight** [comment]
> Tech support belongs on the [Discord server](https://discord.gg/5g93S8H), but since people can't read and are going to probably make an issue like this again, I'll leave the answer here:
> 
> > **Make sure you downloaded a Release build of Xenia, and download the latest x64 Microsoft Visual C++ Redistributable: https://aka.ms/vs/16/release/vc_redist.x64.exe
> > Latest Release Xenia build:
> > https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration:%20Release&pr=false**

read message loud and clear but the links not working for xenia-master. Error message shown is '_{"message":"Artifact not found or access denied."}_'

**Comment by Margen67** [comment]
> 
> 
> > Tech support belongs on the [Discord server](https://discord.gg/5g93S8H), but since people can't read and are going to probably make an issue like this again, I'll leave the answer here:
> > > **Make sure you downloaded a Release build of Xenia, and download the latest x64 Microsoft Visual C++ Redistributable: https://aka.ms/vs/16/release/vc_redist.x64.exe
> > > Latest Release Xenia build:
> > > https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration:%20Release&pr=false**
> 
> read message loud and clear but the links not working for xenia-master. Error message shown is '_{"message":"Artifact not found or access denied."}_'

@syfer-darknight Up-to-date links are in the [Quickstart guide](https://github.com/xenia-project/xenia/wiki/Quickstart).

**Comment by syfer-darknight** [comment]
> > read message loud and clear but the links not working for xenia-master. Error message shown is '_{"message":"Artifact not found or access denied."}_'
> 
> @syfer-darknight Up-to-date links are in the [Quickstart guide](https://github.com/xenia-project/xenia/wiki/Quickstart).

up to date link gave same error. I downloaded the DLL and it works fine now. thank you for your time :-)
