### ISSUE TITLE
Many games crash randomly, and error dialog box appears:

### ISSUE THREAD

**Issue by arcadee1977** [xenia-project/xenia#1523]
![未标题-1](https://user-images.githubusercontent.com/47111657/71573100-1be10880-2b1d-11ea-933f-6bfac367f595.jpg)
This is a huge bug that has not been fixed since the last month

MY PC:
WIN10 1803
8700K 1070TI 16GBRAM

**Comment by vangar** [comment]
Hello, I was able to track down the build using appveyor to where the issue starts. https://github.com/xenia-project/xenia/commit/8ba6f3fc37e6f99e3fd232384388cb73b3494bae seems like this commit and any builds after it will have the crash frequently every 5 - 10 minutes

**Comment by Margen67** [comment]
Closing in favor of #1524
