### ISSUE TITLE
'git describe --long --tags' not works anymore

### ISSUE THREAD

**Issue by sl1pkn07** [xenia-project/xenia#1525]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

seems git tags is gone in the project. the latest build i have with tags working is 1.0.119.1151 builded in 22/05/2018

greetings

**Comment by Margen67** [comment]
The only release/tag was deleted because people kept asking for help with it.

**Comment by sl1pkn07** [comment]
then, now, how i can adquire the version number of the project?

**Comment by gibbed** [comment]
There are no versions, there is commit ID if you want to refer to a specific build.
