### ISSUE TITLE
bit_scan_forward() non-Windows implementation is off by one

### ISSUE THREAD

**Issue by GerbilSoft** [xenia-project/xenia#1530]
https://github.com/xenia-project/xenia/blob/c43ccc073da10fcf2ba43c4f90746cbc9b26880d/src/xenia/base/math.h#L234-L243

The non-Windows implementation of bit_scan_forward() is off by one, resulting in LZX decompression failing.

ffs() returns 1 for the least-significant bit and 0 for "no bits set".

Fix: Change both functions (uint32_t, uint64_t) to:
```
*out_first_set_index = i - 1;
```

Note that this will result in out_first_set_index being 0xFFFFFFFF if no 1 bits are found, but the function returns 0 in that case as well.

**Comment by gibbed** [comment]
Fixed with 0b3cdf2aaadce709cbbff3d83259291bff6ad924.
