### ISSUE TITLE
Change keyboard mapping button and add mouse joystik ?

### ISSUE THREAD

**Issue by gamersalpha** [xenia-project/xenia#1531]
Hello there :

i see in the FAQ button but how change it ?

https://github.com/xenia-project/xenia/wiki/faq

i want map this with Keyboard and mouse : 
![image](https://user-images.githubusercontent.com/32466950/72666575-11c37300-3a14-11ea-9b60-bd302dcaa19e.png)

what do u think do that please?

**Comment by Margen67** [comment]
Tech support doesn't belong on the GitHub issue tracker. Go to the [Discord server's #help channel](https://discord.gg/5g93S8H) for that.

**Comment by gamersalpha** [comment]
is not a tech support, i supose to u integrage a injection mouse and keyboard direct on the Xenia project

to have acces to keyboard and mousse directly on xenia.
