### ISSUE TITLE
Burnout Revenge freezes when creating a savegame

### ISSUE THREAD

**Issue by MastaG** [xenia-project/xenia#1548]
[//]: # (Describe what's going wrong:)
Burnout Revenge freezes when trying to create a new savegame.
I'm running today's latest git from the buildbot  on Windows 10 and the game is running from the dumped iso file.
I checked the game multiple times in abgx360 but it seems to checkout and all crc are correct.
Apart from the freeze all graphics and sound look superb and the game seems to run full speed as well.
[//]: # (Describe what should happen:)
It should continue
[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by MastaG** [comment]
Well I wasn't asking for help or support. Just report the bug so it can be fixed.
The game was running on an older revision.

**Comment by Margen67** [comment]
@MastaG Game-specific issues belong in https://github.com/xenia-project/game-compatibility.
Make sure to read the readme or your issue will be closed again.
