### ISSUE TITLE
diablo 3 not save the game "autosave" not working  i hope you u guys fix it 

### ISSUE THREAD

**Issue by Black-Thunder55** [xenia-project/xenia#1551]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Margen67** [comment]
Congratulations! You failed to read most, if not all of the documentation. Here is your reward.
