### ISSUE TITLE
Problem with lauching xenia with wine 

### ISSUE THREAD

**Issue by Adehom** [xenia-project/xenia#1566]
Hello, 
I want to try to launch xenia with wine but i have a missing dll : 

`002f:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\home\\tony\\T\00e9l\00e9chargements\\xenia.exe") not found
002f:err:module:attach_dlls Importing dlls for L"Z:\\home\\tony\\T\00e9l\00e9chargements\\xenia.exe" failed, status c0000135`

When i add vcruntime140_1.dll manually, xenia launch but crash 2s after. 
LOG :

`tony@tony-Swift-SF314-41:~/Téléchargements$ WINEDEBUG=ALL wine xenia.exe
002e:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x231000, 0x242030, 0x242050) stub.
002e:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x23fd70, 43) stub
002e:fixme:console:AttachConsole stub ffffffff
002e:fixme:ntdll:NtQueryTimerResolution (0x22fc58,0x22fc38,0x22fc34), stub!
002e:fixme:ntdll:NtSetTimerResolution (0,1,0x22fc34), stub!
0030:fixme:ver:GetCurrentPackageId (0x13efdc0 (nil)): stub
0032:fixme:dwmapi:DwmEnableMMCSS (1) stub
0032:fixme:dwmapi:DwmSetPresentParameters (0x10048 0x160f9e0) stub
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
`

**Comment by Prism019** [comment]
Can you give us more information, please?

Distro, hardware, wine version, etc.

**Comment by Adehom** [comment]
Distro: Ubuntu
wine version : 3.6

hardware : 
CPU - > Ryzen 5 3500U
GPU -> Radeon vega 8
RAM : 8Go

**Comment by Margen67** [comment]
That version of Wine is outdated. The latest stable is 5.0.

**Comment by Kattus** [comment]
Even Wine-Stable is on 5.0 lol, so indeed absolutely update.

**Comment by Adehom** [comment]
With a correct version it's work.
Thanks for your help.
