### ISSUE TITLE
Request/Question: Splitscreen in games such as Minecraft.

### ISSUE THREAD

**Issue by ectoBiologist15** [xenia-project/xenia#1576]
First post here, not sure whether to call it a question or request.
Splitscreen in games like Minecraft just dont work.
For example:
Plug in second controller
"press start to join"
spamming start, nothing happens?
give up

I'm wondering if there are any efforts to make this work? I've never owned an actual 360 so I'm not sure what the cause is, and whether it's possible to fix.
Sorry for being a noob about this kind of thing.

**Comment by ZolaKluke** [comment]
If you looked when creating this issue there was a link to the Discord server for technical support, this doesn’t belong here

**Comment by ectoBiologist15** [comment]
sorry my bad, new to all this
