### ISSUE TITLE
Add a disclaimer about Vulkan being buggy

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#1579]
People seem to use Vulkan despite the d3d12 backend being superior, so add a message so people stop asking which backend is better.

**Comment by gandalfthewhite19890404** [comment]
Here is similar issue - https://github.com/xenia-project/xenia/issues/1484

**Comment by LittleStinky123** [comment]
Would be really nice if they added it, my PC crashed with a black screen when using vulkan.
