### ISSUE TITLE
Black Screen after Intro Video

### ISSUE THREAD

**Issue by Gimmy88** [xenia-project/xenia#1603]
[//]: # (Describe what's going wrong:)
The game (Fable 2) is correctly loaded since the intro video:

![1](https://user-images.githubusercontent.com/20839977/79252238-93933300-7e81-11ea-8c5b-73b415b679ea.PNG)
![2](https://user-images.githubusercontent.com/20839977/79252240-94c46000-7e81-11ea-960e-36979f4d03ec.PNG)
![3](https://user-images.githubusercontent.com/20839977/79252243-94c46000-7e81-11ea-919c-60624f4fa319.PNG)
![4](https://user-images.githubusercontent.com/20839977/79252245-955cf680-7e81-11ea-8f2d-df537701c903.PNG)

But after that, a black screen appear:

![5](https://user-images.githubusercontent.com/20839977/79252299-adcd1100-7e81-11ea-8ec8-bd99b4e722b8.PNG)

Is there some fix or some setting I could adjust?

Regards,
Andrea

[xenia.log](https://github.com/xenia-project/xenia/files/4476681/xenia.log)

**Comment by ZolaKluke** [comment]
@Gimmy88 This is not a support forum, when making the issue it said join the Xenia discord for support and a link to it, please close this issue

**Comment by Gimmy88** [comment]
> @Gimmy88 This is not a support forum, when making the issue it said join the Xenia discord for support and a link to it, please close this issue

I tried, but it said invitation is not valid... How could I access to it?

**Comment by Margen67** [comment]
@Gimmy88 Where?

**Comment by Gimmy88** [comment]
> @Gimmy88 Where?

When I click on "New Issue" --> "Open" I get this:

![6](https://user-images.githubusercontent.com/20839977/79266740-5e460f80-7e98-11ea-9624-f901d3a79212.PNG)
