### ISSUE TITLE
Xenia won´t launch with d3d12 AMD rx570 GPU

### ISSUE THREAD

**Issue by carlespring** [xenia-project/xenia#1611]
[//]: # (If i change the Graphics api in the settings with my current setup to anything other than vulkan, xenia doesn't start-no error or crash, simply doesn't start.:)

[//]: # (Xenia should start in this configuration with directx or opengl:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Margen67** [comment]
Duplicate of #1251
