### ISSUE TITLE
Regression between xenia-project and xenia-canary

### ISSUE THREAD

**Issue by tuxuser** [xenia-project/xenia#1615]
# Describe what's going wrong
Uncertainity about the relation of xenia-project vs xenia-canary.
Which fork should be used?
Are they cooperational or independent?

# What should happen?
Please clear up the confusion

Thanks!

**Comment by ZolaKluke** [comment]
Github isn't for tech support please ask on the official discord: https://discord.gg/Q9mxZf9

**Comment by Razzile** [comment]
The canary fork is maintained by regular/active members of the xenia community (who aren't the main devs) and has some not yet merged PRs from the main repo merged, as well as some game specific hacks that can be toggled on. It's 'unofficial' but I'd recommend it to average users. I know you're no average user though so it's up to you which you use really. if you're planning on making any PRs I'd do it for the main repo
