### ISSUE TITLE
Rainbow textures on RDR2 on Xenia stable and CTD on Xenia Canary if d3d12_edram_rov =

### ISSUE THREAD

**Issue by anito9999** [xenia-project/xenia#1617]
![Annotation 2020-06-01 114933](https://user-images.githubusercontent.com/47070105/83374409-23734900-a3fe-11ea-8a8e-450e084c89d5.jpg)
 Rainbow textures on RDR2 on Xenia stable and CTD on Xenia Canary if d3d12_edram_rov = true with a graphics device lost error.

issue happened after updating to Windows 10 2004 and the new WDDM v7 450.99 driver from Nvidia was working fine before the update.

on a AMD 3700X, 32GB RAM at 3000MHZ and RTX 2070 Super.
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Margen67** [comment]
Per-game issues don't belong here.
