### ISSUE TITLE
Discord RPC not displaying some game titles after C++17 merge

### ISSUE THREAD

**Issue by ZolaKluke** [xenia-project/xenia#1621]
### Describe what's going wrong
Since the merge of the C++17 PR some games no longer display their name on Discord Rich Presence. A few games I've tested and noticed this with is Banjo Kazooie, Banjo Tooie and Guitar Hero III.
![image](https://user-images.githubusercontent.com/6497775/83849224-6b71d300-a752-11ea-9cea-e005dbe24815.png)
![image](https://user-images.githubusercontent.com/6497775/83849687-21d5b800-a753-11ea-8e26-71549de0d3f6.png)

### Describe what should happen
The name of the game should be displayed on the user's profile rather than it being blank
![image](https://user-images.githubusercontent.com/6497775/83849414-b986d680-a752-11ea-9b97-920f2de4a407.png)

### If applicable, upload a logfile and link it here
Before C++17 merge log
[xenia.log](https://github.com/xenia-project/xenia/files/4734612/xenia.log)
After C++17 merge log
[xenia.log](https://github.com/xenia-project/xenia/files/4734603/xenia.log)
Latest (June 2nd) log
[xenia.log](https://github.com/xenia-project/xenia/files/4734623/xenia.log)

**Comment by Razzile** [comment]
Possibly related to the utf8 overhaul?
