### ISSUE TITLE
Controllers/USB devices breaks, and Shut down problem after using xenia

### ISSUE THREAD

**Issue by Javonski** [xenia-project/xenia#1623]
[//]: # (Describe what's going wrong:)
Sometimes when I'm playing on xenia, it randomly crashes. These crashes seem to make my USB devices break. When I unplug my Xbox controller, I don't hear the _USB disconnected_ noise. And when I try to reconnect, the light ring of the controller briefly turns on and stays off, all without the _USB connected_ noise. When I try to plug in a new controller, nothing happens at all. The only solution is to restart my PC. Another issue is when I do try to restart the PC, it just stays on the "Restarting" screen no matter how long I wait, forcing me to do a hard power off. It seems these problems are correlated because they always happen at the same time. I'll try to recreate the problem and attach the log. (Amazing job on xenia btw)

Update: The crashes doesn't seem to correlate to the problem. Just playing long enough caused my PC to be stuck in _Shutting Down_. I also can't get the log file, it always gets too big.

**Comment by yxmline** [comment]
device manager refresh freeze encountered ??

**Comment by Mew89** [comment]
l
