### ISSUE TITLE
Xenia OpenGL error

### ISSUE THREAD

**Issue by IonutAG** [xenia-project/xenia#1627]
So when I try to open Xenia emulator it show me an error I know this is an error provided by my GPU and it is because it needs OpneGL 4.5 and I have it but on my dedicated GPU but my laptop has an integrated GPU (Intel HD Family) and it have only 1.2 I think and I know it is not selected as the primary OpenGL GPU if someone know hot to fix this and can help me I will be very thanksfull (Sorry for bat english) :)
![image](https://user-images.githubusercontent.com/67830699/86513664-b136bf80-be14-11ea-8a6c-73ce5708a972.png)
My Gpu stats
![image](https://user-images.githubusercontent.com/67830699/86513734-4f2a8a00-be15-11ea-89f4-4e71d1beb331.png)

**Comment by Triang3l** [comment]
Xenia uses Direct3D 12, not OpenGL 4.5. Make sure you have the latest graphics card driver installed (for the Nvidia GPU), and that you're launching the emulator on the Nvidia GPU (if your Intel GPU doesn't support modern, D3D11-level graphics features).
