### ISSUE TITLE
WWE '12 & WWE 2K14

### ISSUE THREAD

**Issue by mjiii** [xenia-project/xenia#1630]
On Latest Xenia Build WWE '12 & WWE 2K14 only Royal Rumble works, other modes crashes before match begin

I found a build that WWE '12 Works Perfect without crashes but in WWE 2K14 is unlimited loading screen

Is there any way to make wwe 2k14 playable?

**_Custom Build_**: [Xenia-DX12 1.07-ML BASE.zip](https://github.com/xenia-project/xenia/files/4924172/Xenia-DX12.1.07-ML.BASE.zip)

Xenia Log from WWE 2K14 crash: [xenia.log](https://github.com/xenia-project/xenia/files/4924247/xenia.log)

WWE '12 on custom build: ![Bez tytu1ł2u](https://user-images.githubusercontent.com/68325706/87528082-54959900-c68d-11ea-978b-7effd87fe809.png)
WWE 2K14 on latest xenia master build: ![Bez tytu1łu](https://user-images.githubusercontent.com/68325706/87527446-6dea1580-c68c-11ea-85ea-dd866506ba2c.png)

**Comment by SplinterSword** [comment]
there are massive frame drops in the custom build

**Comment by Triang3l** [comment]
> there are massive frame drops in the custom build

Any reports from any branches other than `xenia-project/xenia:master` (or with clearly described changes as opposed to the `master` branch) are not valid in this tracker. Also, distribution of binaries of custom builds is not allowed in the compatibility tracker. Do not use custom builds that are often heavily outdated, contain questionable hacks/workarounds that aren't even shared publicly, and may potentially contain viruses.

**Comment by Triang3l** [comment]
Also, the compatibility tracker is located in another repository, and neither this repository nor the compatibility tracker is for "is there any way?" tech support questions. This repository is for development of Xenia, for whole-emulator issues, or, when specific games are involved, for discussion of the actual details of the reimplementation of the console's behavior and of the technical causes of the crashes/freezes, not just for reporting that a crash happens in a game.
