### ISSUE TITLE
[REQUEST] Support Linux nativly

### ISSUE THREAD

**Issue by Godnyx** [xenia-project/xenia#1633]
I don't know if you accept requests but in case you do I just wanted to request for Linux support (native not through wine) in case no one did. Of course it's fine if you don't but I just wanted to say that there are people that care about Linux!

**Comment by ZolaKluke** [comment]
If you took a look at the open PR's you'd see plenty of work is already being done for Linux support
https://github.com/xenia-project/xenia/labels/platform-linux

**Comment by Triang3l** [comment]
Linux support is in development, and is tracked in #1430 and other issues linked in the comment above.
