### ISSUE TITLE
Does Xenia have a functionality to map keyboard controls?.

### ISSUE THREAD

**Issue by ElektroStudios** [xenia-project/xenia#1641]
( I publish here because when I accept the Discord invite link it says "you have no permissions to send messages in this channel"... )

Does Xenia have a functionality to map keyboard controls?.

If not, what are the alternatives to remap the current keyboard controls?, for people that does not have a game pad and want to configure other keayboard keys than the current ones...

Is this info correct?: https://www.reddit.com/r/emulation/comments/3ywpsn/xenia_360_keyboard_controls/

Which are the keys for triggers?.

Also, does Xenia support both Dinput and XInput?, the program will correctly configure any game pad?... 

The apparent lack of all this kind of functionality is just temporal until devs can start focus their effort to implement these options in the menu, or it will be like this without any kind support forever?. Just asking to know the answer, I understand it could require time.

Thanks in advance.

**Comment by mirh** [comment]
In the meantime you can use [vjoy](http://vjoystick.sourceforge.net/site/index.php/vxbox) or [UCR](https://github.com/Snoothy/UCR/wiki/Core_Interception).

**Comment by Margen67** [comment]
Duplicate of #1333

**Comment by gamersalpha** [comment]
HEllo i up this, bevause we hare in 2022  can't map keybaord and mousse ?

why guys ?

**Comment by RagdolllFan2005** [comment]
You Can Use Virtual Controller Or X360ce 
Or Get XBOX 360 USB Control Or Adapter
