### ISSUE TITLE
x360ce_x64 blank screen with Xenia

### ISSUE THREAD

**Issue by MunduZ2** [xenia-project/xenia#1645]
please help me , i have issue while trying to modify my controller with x360ce controller emulator with Xenia but whenever i try to open it keep showing blank screen , tried to run as admin but not working
![xenia](https://user-images.githubusercontent.com/70414245/91619479-6d33e700-e98d-11ea-88aa-1fd12cb6ecd7.JPG)

**Comment by MunduZ2** [comment]
any solution  ?

**Comment by MunduZ2** [comment]
ok you have closed it but can i know how to use my controllers with xenia ?

**Comment by Margen67** [comment]
> 
> 
> any solution ?

RTFM
