### ISSUE TITLE
Switches not working?

### ISSUE THREAD

**Issue by ThePapaw** [xenia-project/xenia#1648]
I update Xenia Canary to 09-09 version. I use Launchbox frontend and had been using "-vsync=false -fullscreen" (without quotes) for a couple switches. Not I am unable to get either of them to work in in combination I have tried since updating.

Is it something I am doing wrong or are the switches not working correctly with this build?

Thanks for the awesome work you're doing with the emulator

[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
Switches must be prefixed with `--`, not `-`. This is not a support forum though, but rather, a bug/improvement tracker, for questions, the Discord server is preferred.

**Comment by ThePapaw** [comment]
Thank you, I apologize, I wasn't able to input on Discord when I went there. Again, thank you and I do apologize
