### ISSUE TITLE
Linux threading: Fix potential dealock during multiple wait

### ISSUE THREAD

**Issue by bwrsandman** [xenia-project/xenia#1679]
Suspension needs rework to only occur immediately when the thread is in guest code, but deferred until the return to the guest if it happens during a kernel call. Or, for performance reasons, possibly not on every guest–host boundary, but when a special kind of mutex, similar to global_critical_region but not limited to a single instance, is locked/unlocked.

This should be somewhat easy to implement on POSIX because the thread itself will reply to the suspension signal — it can set a flag in its context structure when it enters a kernel function, and the signal handler can check whether to sleep immediately or to defer the suspension.

On Windows, however (while there is a native WaitForMultipleObjects implementation that will work fine, having control over suspension would allow us to have more granular kernel mutexes rather than just a single global_critical_region which is our current way of preventing suspension when kernel state is being modified, with easier usage of condition variables in the kernel — would possibly be useful for GPU readback in the access violation handler), the target thread can't provide its own response to suspension, and there are no signals. A possible solution is making suspension synchronous (which is contrary to the way it actually works on Windows, but possibly should have no noticeable effect on anything), with the source thread, not the target, being partially responsible for checking whether the target is in kernel code: call SuspendThread, then GetThreadContext to synchronize with the suspended thread, and check whether it's sleeping in kernel code currently — if yes, notify it that suspension was requested and unsuspend it on the host, to let it self-suspend on the next kernel to guest return.

_Originally posted by @Triang3l in https://github.com/xenia-project/xenia/pull/1317#discussion_r517989158_

**Comment by Triang3l** [comment]
Seems like there was a race condition between this and #1677 :)
