### ISSUE TITLE
Rename branch 'master' to 'main'

### ISSUE THREAD

**Issue by gibbed** [xenia-project/xenia#1683]
https://github.com/github/renaming

Since there's a lot of work involved in this, this is a planned change that will occur when GitHub implements seamless renaming:
https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by gibbed** [comment]
I'm not interested in discussing the why of this change so this issue comments are locked to collaborators, it will happen regardless.

**Comment by Triang3l** [comment]
Are there any new cloning/forking issues in repositories still using `master`? Seems like this change may add unnecessary and unpredictable inconvenience for existing clones/forks.

**Comment by gibbed** [comment]
The planned seamless transition that GitHub has documented suggests it would resolve any issues like that.

**Comment by Triang3l** [comment]
"Seamless", as it normally happens with everything in the software world, is a very optimistic promise, I think, considering the external integrations and the overall complexity of Git and GitHub.

**Comment by gibbed** [comment]
Agreed. It'll require testing, for sure.

**Comment by Triang3l** [comment]
What existing/upcoming issues are going to be solved with this change though?

**Comment by gibbed** [comment]
Voted per Discord discussion.
