### ISSUE TITLE
 launch Red dead redemption always crash after headpiece rockstar

### ISSUE THREAD

**Issue by JIuBeP** [xenia-project/xenia#1719]
Hello! Im sorry, if wrong/ 
pc: win7 x64, cpu ryzen 2600, 8 gb ram, gtx 950 2gb (vulkan beta 451.98)

when im just launch Red dead redemption always crash after headpiece rockstar.

what could be the problem?
[xenia.log](https://github.com/xenia-project/xenia/files/5668066/xenia.log)

maybe you help me please?

**Comment by Triang3l** [comment]
The current Vulkan renderer is largely unsupported (for 2.5 years already), upgrade to Windows 10 and use the Direct3D 12 renderer. A new Vulkan renderer will be available in a few months. Also, for support, please use the #help channel of our Discord server, GitHub issues are for development.
