### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by QuantumCoder002** [xenia-project/xenia#1738]
Hi, ive recently downloaded Xenia so i can play Forza H 2.
So whenever i launch the exe, it closes just after, and i checked xenia.txt and found that it says : “000004FC Failed to initialize vulkan instance”. Do you know any fix for it ?

**System info:**
Windows 7
4 GB RAM
Intel Core i3-2350M
2.30 GHz

**Comment by JoelLinn** [comment]
Your system probably can't run it. (ultimately graphics card which seems to not support vulkan but RAM/CPU would also make the experience terrible anyways) 
For help please use the help channel in the [xenia discord server](https://discord.gg/Q9mxZf9).
