### ISSUE TITLE
Sleep(10) inside XMPGetPlaybackController causes issues in certain games

### ISSUE THREAD

**Issue by emoose** [xenia-project/xenia#1749]
As noted at https://github.com/xenia-project/game-compatibility/issues/154#issuecomment-770482719, removing the Sleep(10) call from [XMPGetPlaybackController](https://github.com/xenia-project/xenia/blob/master/src/xenia/kernel/xam/apps/xmp_app.cc#L431) fixes issues with MGS2 taking 5-10 minutes to load, and fixes the rapid flashing during menus/gameplay.

Apparently that Sleep is there because A-Train would spawn a thread that looped over XMPGetPlaybackController forever, but in MGS2's case it's calling XMPGetPlaybackController from the main thread, and I guess making main thread sleep is a bad idea...

(E: MGS3 also has the same issue calling it from main thread, but in MGS3 case it just reduces framerate + slows down gameplay, not as major as MGS2)

Maybe there's a check we can add so it only sleeps if it's outside main thread?
IIRC wasn't A-Train one of the first games to run on Xenia too? I wonder if it's behavior has changed at all since then, maybe a Sleep here is unneeded now.

**Comment by spacebear84** [comment]
How do I remove the sleep from main thread?
