### ISSUE TITLE
Blinding white screen at startup

### ISSUE THREAD

**Issue by Raijin56** [xenia-project/xenia#1752]
[//]: # (Describe what's going wrong:)
Hi. When we open the emulator, in my case Xenia Master a6954ace Feb 1 2021, also in Xenia Canary, with no game loaded yet, so at the startup, the window shows a blinding white screen. When we move or resize the window, it turns into a black screen.

[//]: # (Describe what should happen:)
The behavior should be to have it being black always.

I attach two pics of the window, in the initial state and after moving or resizing it (no game loaded yet)

Thank you very much and kind regards.
![1  before](https://user-images.githubusercontent.com/1304436/106815506-41233d00-6674-11eb-8dd7-43696012ad87.png)
![2  after](https://user-images.githubusercontent.com/1304436/106815509-42ed0080-6674-11eb-8920-e7b3bbca7d8e.png)

**Comment by Triang3l** [comment]
That's kind of probably by design (to make it look more blank on launch), used to be white changing to grey at first though, but I changed it to black when I added letterboxing. But Razzile's new GUI will not have this issue at all, I think.

**Comment by Margen67** [comment]
This was fixed.
