### ISSUE TITLE
Performance randomly takes a nosedive, but clicking out of the window, and back in fixes it.

### ISSUE THREAD

**Issue by StrikerMan780** [xenia-project/xenia#1753]
[//]: # (Describe what's going wrong:)
Pretty much the title, at random, the performance of Xenia takes a nosedive, but if you click out of the window and back in, it immediately returns to normal. Tested with GoldenEye XBLA. 

[//]: # (Describe what should happen:)
Performance should be consistent, of course.

If it helps, my specs are as follows: AMD Ryzen 5 3600, at 4.2ghz, 16gb RAM, NVidia GeForce GTX 1060 6gb.

**Comment by illusion0001** [comment]
Similar to #1207
