### ISSUE TITLE
Xenia not launching under wine

### ISSUE THREAD

**Issue by BulletproofMike** [xenia-project/xenia#1755]
I am using Lutris under Manjaro linux to launch Xenia. I have added Xenia as a game to Lutris and when I run it it crashes. If I launch Xenia directly from wine I get the same crash which is:

i> 00000104 Build: detached / a6954aced397ea1846379dbb48571a76637dadce on Feb  1 2021
i> 00000104 Storage root: C:\users\mike\My Documents\Xenia
i> 00000104 Loaded config: C:\users\mike\My Documents\Xenia\xenia.config.toml
i> 00000104 Content root: C:\users\mike\My Documents\Xenia\content
i> 00000104 Cache root: C:\users\mike\My Documents\Xenia\cache
w> 00000114 Failed to set process DPI awareness. (code = 0x-7FF8FFFB)
w> 00000114 SDL GameControllerDB: file 'gamecontrollerdb.txt' does not exist.
w> 00000104 Failed to load dxilconv.dll, converted DXIL disassembly for debugging will be unavailable - DXIL may be unsupported by your OS version
w> 00000104 Failed to load dxcompiler.dll, converted DXIL disassembly for debugging will be unavailable - if needed, download the DirectX Shader Compiler from https://github.com/microsoft/DirectXShaderCompiler/releases and place the DLL in the Xenia directory
i> 00000104 DXGI adapter: Intel(R) HD Graphics 4600 (vendor 8086, device 0412)
i> 00000104 Direct3D 12 device and OS features:
* Max GPU virtual address bits per resource: 40
* Non-zeroed heap creation: no
* Programmable sample positions: tier 0
* Rasterizer-ordered views: no
* Resource binding: tier 3
* Tiled resources: tier 0
w> 00000114 Unable to load japanese font; jp characters will be boxes
i> 00000104 Added handle:F8000004 for class xe::kernel::XObject
i> 00000104 XThreadF8000004 (1) Stack: 40010000-40030000
w> 00000104 Too few processor cores - scheduling will be wonky
i> 00000104 Added handle:F8000008 for class xe::kernel::XObject
i> 00000104 XThreadF8000008 (2) Stack: 40050000-40070000
w> 00000104 Too few processor cores - scheduling will be wonky
K> F8000004 XThread::Execute thid 1 (handle=F8000004, 'GPU Commands (F8000004)', native=00000130, <host>)
K> F8000008 XThread::Execute thid 2 (handle=F8000008, 'GPU VSync (F8000008)', native=00000134, <host>)
!> F8000004 Failed to create the global root signature for bindless resources, the version for use without tessellation

The dxgi log says:

warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: xenia.exe
info:  DXVK: v1.7.3-4-g03f11baf
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Intel(R) HD Graphics 4600 (HSW GT2):
info:    Driver: 20.3.3
info:    Vulkan: 1.2.145
info:    Memory Heap[0]: 
info:      Size: 1536 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:  Adapter LUID 0: 0:3f6

I am using wine 6.0
OS: Manjaro linux
CPU with built integrated graphics: i5 4600

Any help would be greatly appreciated

Thanks

**Comment by JoelLinn** [comment]
xenia uses some uncommon dx12 features
basically wine is not able to run xenia (except for very basic guests but only with vulkan)

unfortunately there isn't much we can do about it
