### ISSUE TITLE
Closing game through file menu freezes and crashes Xenia

### ISSUE THREAD

**Issue by wbrooks003** [xenia-project/xenia#1756]
I have noticed an issue where going to close a game through the file menu in Xenia often leads to the application freezing and not responding, requiring me to end the task within Windows. I am using build a6954aced397ea1846379dbb48571a76637dadce. I have attached the log file from one of these situations where I have experienced this freeze.

Thanks
[xenia.zip](https://github.com/xenia-project/xenia/files/5936207/xenia.zip)

[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by halotroop2288** [comment]
See #665.
