### ISSUE TITLE
AVX is not supported by the cpu. 

### ISSUE THREAD

**Issue by jim1023** [xenia-project/xenia#1764]
Hello when I try to open xenia it displays an error message my cpu does not support AVX.

AMD Phenom(tm) 2 X6 1045T  Processor 2,70 GHZ

64 bits win 10  AMD Radeon HD 7770

**Comment by Masamune3210** [comment]
Then you will have to upgrade your cpu before you can use xenia, since xenia requires AVX instructions

**Comment by Triang3l** [comment]
Your CPU is too old/low-end and doesn't support the AVX instruction set which Xenia heavily relies on, and this is not a tech support forum.
