### ISSUE TITLE
Burnout revenge in game sound

### ISSUE THREAD

**Issue by Recker2** [xenia-project/xenia#1765]
Hi I'm new here just wonderd if there is some fix for the game music in burnout revenge xbox 360 any help would be great full thankyou as music doesn't play and is such an awesome game from yesteryear

**Comment by Triang3l** [comment]
This is not a support forum. For Burnout Revenge-specific discussions, see https://github.com/xenia-project/game-compatibility/issues/914. Audio decompression is a relatively underresearched part of the emulator, and there are almost no situations where there is some simple fix for something — if there was, it would have likely been fixed already.

**Comment by Triang3l** [comment]
As far as I understand, XAudio1 on the Xbox 360 is only capable of playing pre-mixed PCM buffers, with WMA/xWMA decoding performed on the application side (in the library statically linked to the game). XMA2 has special decoding hardware, but the decoder writes to a PCM buffer that is then played as usual.
