### ISSUE TITLE
Incorrect texture/framebuffer pitch on Plants vs. Zombies backgrounds

### ISSUE THREAD

**Issue by NightShade110** [xenia-project/xenia#1768]
I am having bugs playing plants vs zombies. Here is a picture 
of how loading screen looks for me :
![Untitled](https://user-images.githubusercontent.com/80777809/111345924-00a8dd00-867e-11eb-953f-5ade89e09c67.png)

This is how it should look like:
![320px-PvZHighEndConsoles_title](https://user-images.githubusercontent.com/80777809/111346359-6eed9f80-867e-11eb-90f3-b03a8f982f7b.png)
Its not only the loading screen, there are multiple bugs like this, does anyone know how to fix this

**Comment by Triang3l** [comment]
Possibly texture pitch that we're currently ignoring for tiled textures, though it's weird that it's not in 32x32 regions, interesting.

**Comment by NightShade110** [comment]
> Possibly texture pitch that we're currently ignoring for tiled textures, though it's weird that it's not in 32x32 regions, interesting.

Is there a way to fix this?

**Comment by NightShade110** [comment]
![Untitle2d](https://user-images.githubusercontent.com/80777809/111348193-3b137980-8680-11eb-95fa-182a7c08ffe4.png)
There is also this, look at the sky its soo glitchy

**Comment by NightShade110** [comment]
The only way to fix this is for xenia to update or something?

**Comment by Triang3l** [comment]
If these are 8 pixels tall, this might also be something with render target pitch (with MSAA) rather than textures, which is more weird, though not sure.

Related: Marvel vs. Capcom 2 character sprites also exhibit wrong texture pitch apparently, but there the effect seems more 32-pixel-aligned: https://www.youtube.com/watch?v=mb60wAGyK7w

> Is there a way to fix this?
This is a bug in the emulator. If you're looking for a user-side fix, then no, it needs to be fixed in the emulator code — in the texture cache code, address/size calculation in texture_util, and compute shaders for untiling textures (which also don't take the row pitch for tiled textures).

**Comment by NightShade110** [comment]
> If these are 8 pixels tall, this might also be something with render target pitch (with MSAA) rather than textures, which is more weird, though not sure.
> 
> Related: Marvel vs. Capcom 2 character sprites also exhibit wrong texture pitch apparently, but there the effect seems more 32-pixel-aligned: https://www.youtube.com/watch?v=mb60wAGyK7w
> 
> > Is there a way to fix this?
> 
> This is a bug in the emulator. If you're looking for a user-side fix, then no, it needs to be fixed in the emulator code — in the texture cache code, address/size calculation in texture_util, and compute shaders for untiling textures (which also don't take the row pitch for tiled textures).

uhh wait , i didn't quite understand what i need to change in the code
`dump_shaders = ""                                 	
dxbc_source_map = false                           	
dxbc_switch = true                                	
fullscreen = false                                	
gpu = "any"                                       	
gpu_allow_invalid_fetch_constants = true         	
half_pixel_offset = true                          	
present_letterbox = true                          	
present_rescale = true                            	
present_safe_area_x = 90                          	
present_safe_area_y = 90                          	
query_occlusion_fake_sample_count = 1000          	
resolve_resolution_scale_duplicate_second_pixel = true	
spv_disasm = false                                	
spv_validate = false                              	
ssaa_scale_gradients = true                       	 
                                                  	

store_shaders = true                              	
texture_dump = false                              	
trace_gpu_prefix = "scratch/gpu/"                 	
trace_gpu_stream = false                          	
vsync = true  `                             	
here is the code , what exactly do i have to change?

**Comment by NightShade110** [comment]
oh wait i didnt see i have to change cache code sorry

**Comment by Triang3l** [comment]
> here is the code , what exactly do i have to change?
It's the config, not the code. There's no "make everything perfect" option in it, you need to wait until a programmer fixes this in the emulation logic. This is also a place for bug _reporting_ and investigation, not for support.

**Comment by NightShade110** [comment]
> > here is the code , what exactly do i have to change?
> 
> It's the config, not the code. There's no "make everything perfect" option in it, you need to wait until a programmer fixes this in the emulation logic. This is also a place for bug _reporting_ and investigation, not for support.

dammit...

**Comment by NightShade110** [comment]
where can i report the bug

**Comment by Triang3l** [comment]
> where can i report the bug
You have already reported it here, thanks. But please stop using this place as a chat.

**Comment by Triang3l** [comment]
Places this is affected by:

- Texture key in the texture cache (should contain the pitch as part of it).
- Size calculation in texture_util.cc/.h. Tile rows [0,last) should use the pitch as the width, the last row should use the rounded width. For 3D textures, it's a more difficult thing to define what the last row actually is — but it's probably the last row of the last layer when the texture size is rounded to 32x32x4 (every 4 layers are stored in non-overlapping memory locations, even though the address calculation formula repeats every 32x32x8 texels).
- Texture loading shaders — they have a special pitch value to indicate that the texture is tiled, should use a bit instead, and also use the pitch when the texture is tiled.

**Comment by Triang3l** [comment]
Fixed in 4eca2326c3e25cd26f26f6aebabfe5a6e16bae4d.
