### ISSUE TITLE
No picture in Dodonpachi Saidaioujou

### ISSUE THREAD

**Issue by LeToShaitTan** [xenia-project/xenia#1770]
[//]: # (Describe what's going wrong:)
The video intro of the game is OK and then, there is no more picture (black screen). The game seems to work in the background, I can heard the sound of the game and there is no crash.
[//]: # (Describe what should happen:)
it should for as fine as  Mushihime-sama Futari ? (it seems to be quite perfect! GG)
[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
Unless there are hints at the exact problem (like some texture not laid out correctly, or an assertion failure), this belongs in the comments of the game's compatibility tracker entry. This is too vague for an actual bug report, black screen is what happens in dozens or hundreds of games.
