### ISSUE TITLE
No Audio connected; crash of guest 

### ISSUE THREAD

**Issue by TiloGit** [xenia-project/xenia#1776]
(Describe what's going wrong:)
Computer has no speaker/audio plugged in. guest crashes.  
log shows: 
` !> F8000028 IXAudio2::CreateMasteringVoice failed with -7FF8FB70`

see also https://github.com/xenia-project/game-compatibility/issues/1704#issuecomment-820917472

 (Describe what should happen:  Maybe bit more graceful handling this condition. 

(If applicable, provide a callstack here - esp. for crashes)  sorry don't 

 (If applicable, upload a logfile and link it here)
log has CRASH DUMP  [xenia.log](https://github.com/xenia-project/xenia/files/6322729/xenia.log)

**Comment by illusion0001** [comment]
Duplicate of #1319

**Comment by TiloGit** [comment]
Thanks for the quick update. 
Was wondering if that could/should be handled more gracefully but looks like no interest for that. Anyhow cheers.

**Comment by Margen67** [comment]
#1967
