### ISSUE TITLE
 Write to unknown register (0601): 00000003

### ISSUE THREAD

**Issue by JABirchall** [xenia-project/xenia#1779]
While testing the recent compatibility or xenia with UFC 3, I noticed the game would lock up randomly between transitions.
The game would enter an endless loop trying to write to a register which xenia does not have.

```
!> F8000228 XMA: Write to unknown register (0601): 00000003
!> F8000228 XMA: Write to unknown register (0601): 00000002
!> F8000228 XMA: Write to unknown register (0601): 00000003
!> F8000228 XMA: Write to unknown register (0601): 00000002
```

Log: [xenia.zip](https://github.com/xenia-project/game-compatibility/files/6395154/xenia.zip)

**Comment by JABirchall** [comment]
Related https://github.com/xenia-project/game-compatibility/issues/1081

**Comment by gibbed** [comment]
These log messages would not be why any particular game is freezing and don't warrant an issue by themselves.
