### ISSUE TITLE
Bright textures in red dead redemption 1

### ISSUE THREAD

**Issue by jf123git** [xenia-project/xenia#1791]
When I play the game with rtv the textures are glitchy and the game is unplayable. When using rov it looks fine but costs fps. I want to be able to play with rtv without the graphical glitches, can anyone help?
![Screenshot (111)](https://user-images.githubusercontent.com/76422824/116897453-448e7c00-ac03-11eb-96c6-708b05ab1ad1.png)

**Comment by andgtr08** [comment]
Same here, with latest Nvidia driver and a RTX 3070.

**Comment by backgamon** [comment]
2070 RTX and 466.11.
No problems with RTV.
https://www.youtube.com/watch?v=yeU-SpjGgTI

**Comment by andgtr08** [comment]
I managed to fix this. You must change the new option "render_target_path_d3d12" to "rov" in the Xenia config file.

**Comment by fshwrm** [comment]
I also have this problem, is there any way to play with RTV? RTX 3060.

**Comment by andgtr08** [comment]
It's something related to nvidia drivers. Using a old driver solve this issue.

**Comment by daniyarmadi** [comment]
Hello right now with the latest driver of nvidia I am have this issue artifacts can you help me please?

**Comment by Margen67** [comment]
https://github.com/xenia-project/game-compatibility/issues/108
