### ISSUE TITLE
Sound issue(BGM) with latest XMA(FFmpeg) change.

### ISSUE THREAD

**Issue by backgamon** [xenia-project/xenia#1794]
BGM can stop or crash with the latest Xenia Update.

- In Goldeneye BGM stop after a while, only sound FX continues to play.If u start a new level, BGM restart inside...and stop again after some times.
- Same in KOF Sky Stage, BGM play normally at start, and after a while just disapear.

- Games just doesn't crash, it continu running well....without BGM.
- https://www.youtube.com/watch?v=C2e8tJpiNnQ

Mayhem 3D - Old version with XMA/LIBAV:
https://www.youtube.com/watch?v=IgEFa62GZXA
Mayhem 3D - New version with XMA/FFMPEG
https://www.youtube.com/watch?v=zkWdChm1X0A

**Comment by JoelLinn** [comment]
Please report the regression through the [game-compatibility tracker](https://github.com/xenia-project/game-compatibility/issues) (on the respective game issue) and add the label `apu-xma-regression`.
