### ISSUE TITLE
Good today and I detected a problem when playing xenia emulator b099d74 and that is that when I play forza horizon or forza horizon 2 when doing the prologue it closes and closes so I would like to have neither create nor hang nor close alone and that they improved performance and there was no lag and that it could be handled without lag and that the ai did not fail so much and the cars did not collide with each other and that the graphics were the same as that of the xbox 360 and the lighting of the texture and the colors are neither transparent nor have strange colors please it is time for xenia emulator to go well and do not fail so much I ask you please

### ISSUE THREAD

**Issue by JuanjoSevilla1** [xenia-project/xenia#1796]
Well today and I have detected a problem when playing xenia emulator b099d74 and it is that when I play forza horizon or forza horizon 2 when doing the prologue it closes and closes so I would like to not have neither create nor hang nor close alone and that improved performance and there was no lag and that it could be driven without lag and that the ai did not fail as much and the cars did not crash into each other and that the graphics were the same as the xbox 360 and the lighting of the texture and colors are not transparent or have strange colors please it's time for the xenia emulator to go well and not fail so much I ask you please
It is necessary for me because I do not have xbox 360 and my pc is powerful enough that the xenia emulator works without problems
Thanks @ Triang3l

_Originally posted by @ JuanjoSevilla1 at https://github.com/xenia-project/xenia/issues/1795#issuecomment-832777534_

**Comment by Triang3l** [comment]
Forza Horizon issues should be in the games' respective pages in the game compatibility tracker. This is not a support forum for "closes and closes", "lag", "AI did not fail as much", and also totally not for "I ask you please, it is necessary for me". This issue tracker is for detailed issues, when you already know the actual technical reason — the game compatibility tracker is for abstract symptoms. Also don't reopen closed issues.
