### ISSUE TITLE
Audio glitch in several games

### ISSUE THREAD

**Issue by Clarke2131** [xenia-project/xenia#1800]
[//]: # (Describe what's going wrong:)
several games having audio glitches after a few seconds, after menu

[//]: # (Describe what should happen:)
the emulator should play the ost without problems

[//]: # (If applicable, upload a logfile and link it here)
i cant, its too large to upload (113MB to 1.05GB)
 games i've noticed the audio bug was forza motorsport 2 and 4, forza horizon 1 and 2, hydro thunder and resident evil 0
 last know working build was "xenia detached 55689317/ apr 2021"

**Comment by Clarke2131** [comment]
ok, my bad

**Comment by Margen67** [comment]
Duplicate of #1156
