### ISSUE TITLE
Dead Rising Case West and Zero cutscene rewind and loop

### ISSUE THREAD

**Issue by rvrdx** [xenia-project/xenia#1805]
Dead rising case west and case zero both have a problem where the cutscene starts, Goes a few seconds and then rewinds and loops forever. The cutscene needs to be skipped for going Ingame.

**Comment by rvrdx** [comment]
And yeah one more issue i found was that when you create a combo weapon the camera gets stucks and need to be skipped to return to gameplay.

**Comment by JoelLinn** [comment]
Please report this on the respective issue (or create one) in the game compatibility repo https://github.com/xenia-project/game-compatibility/issues
This issue tracker is only for general xenia bugs and not title related things
