### ISSUE TITLE
APPCRASH

### ISSUE THREAD

**Issue by blackie369** [xenia-project/xenia#1813]
ENG - I just wanted to play crash mind over mutant and downloaded torrent of game. When I start xenia all is OK, but when I start the game it works for 2 seconds and crushes!
RUS - Я просто хотел поиграть в crash mind over mutant и скачал торент. Когда запускаю xenia всё работает, но сама игра работает секунды 2 и вылетает вместе с xenia.

Имя события проблемы: APPCRASH
Имя приложения: xenia.exe
Версия приложения: 0.0.0.0
Отметка времени приложения: 5a9b4bfd
Имя модуля с ошибкой: ucrtbase.DLL
Версия модуля с ошибкой: 10.0.14393.2990
Отметка времени модуля с ошибкой: 5caeb96f
Код исключения: c0000005
Смещение исключения: 000000000000a324
Версия ОС: 6.3.9600.2.0.0.768.100
Код языка: 1049
Дополнительные сведения 1: 28ec
Дополнительные сведения 2: 28ec01a27b15302f99ed21235f13b5d7
Дополнительные сведения 3: 2325
Дополнительные сведения 4: 2325a1e7f37e88ca9e0e6c4ec3da450e

![изображение_2021-05-18_144838](https://user-images.githubusercontent.com/84386889/118645860-266e7180-b7e8-11eb-9445-080d5ff1431a.png)
![изображение_2021-05-18_144858](https://user-images.githubusercontent.com/84386889/118645899-325a3380-b7e8-11eb-8f3e-dfbc4c4bb16d.png)
![изображение_2021-05-18_144937](https://user-images.githubusercontent.com/84386889/118645973-49008a80-b7e8-11eb-88c3-6e3634d3b5c8.png)

**Comment by Triang3l** [comment]
1) No help for pirates.
2) This is a 3 years ancient build.
3) The Vulkan renderer is unsupported.
