### ISSUE TITLE
Color swapping issues?

### ISSUE THREAD

**Issue by benvanik** [xenia-project/xenia#182]
F5 clear cache in A-train a few times and colors will invert (red sky) - some non-deterministic setting controlling texture uploads?

**Comment by raven02** [comment]
Just wonder https://github.com/benvanik/xenia/commit/7cabcad69ee8e8be65d4db438cfc1553f5dde857 solved this issue ?

**Comment by benvanik** [comment]
Nope :(

**Comment by raven02** [comment]
thanks @benvanik
