### ISSUE TITLE
BaseHeap::Alloc page count too big for requested range, What to do?

### ISSUE THREAD

**Issue by TheBigFatAlbert** [xenia-project/xenia#1823]
[//]: # (Describe what's going wrong:)
Started Xenia everything was fine, Had done a test on a game to see if it would boot as normal, It worked, Tested the game 
Naughty Bear Panic In Paradise and did proceed to open but crashed at the 505 Game logo after a few minutes of freezing
up and not responding, Looked at the log file after Xenia had output an error upon crashing with (Not Responding) and looked at the log file to discover "!: BaseHeap::Alloc page count too big for requested range." and after that we end up here.
[//]: # (Describe what should happen:)
The game Naughty Bear Panic in Paradise should open with the 505 Logo and its other respected logos and should go to a game menu to start the game and you could play the game with a tutorial guiding you to play the game right, Then you continue to play the game. 
[//]: # (If applicable, provide a callstack here - esp. for crashes)
Look at Log File.
[//]: # (If applicable, upload a logfile and link it here)

[xenia.log](https://github.com/xenia-project/xenia/files/6566548/xenia.log)

**Comment by Masamune3210** [comment]
Please report issues with specific games in the game-compatibility section

https://github.com/xenia-project/game-compatibility
