### ISSUE TITLE
[Linux] Build failure on recent commits

### ISSUE THREAD

**Issue by Shoegzer** [xenia-project/xenia#1825]
Xenia fails to build on linux again.   Suspect PR #1797 though it may be due to gcc-11 as previously was compiling with gcc-10.

Specs:
* OS: Linux Mint 20.1 / kernel 5.11
* Compiler: gcc-11.1.0

Build log excerpt:
```
../third_party/spirv-tools/source/validate_cfg.cpp:42:12: error: no member named 'numeric_limits' in namespace 'std'
using std::numeric_limits;
      ~~~~~^
validate_composites.cpp
1 error generated.
make[1]: *** [spirv-tools.make:386: obj/Linux/Debug/Linux/Debug/spirv-tools/validate_cfg.o] Error 1
```

**Comment by JoelLinn** [comment]
I suspect thats due to your GLIBC version, can you try adding `#include <limits>` to that cpp file?

**Comment by Shoegzer** [comment]
Thanks @JoelLinn.   After adding `#include <limits>` to `validate_cfg.cpp`, xenia compiles successfully and I get a binary in `./build/bin/Linux/Debug`, I suppose due to `numeric_limits` now being recognized.

**Comment by Shoegzer** [comment]
Update: Tried to compile against more recent commit 509a1fa3866be4fb3ab9d413f600012688c89a7c and with gcc-11.2.0 but with same results as above.  

@JoelLinn I can create a PR with `#include <limits>` based on your suggestion, just want to be sure it won't conflict with anything else first.

**Comment by JoelLinn** [comment]
Yes you can do that in https://github.com/xenia-project/SPIRV-Tools
Since it's already forked it shouldn't be an issue. @Triang3l 

It's gonna be replaced _someday_ but till then let's have the project build

**Comment by Shoegzer** [comment]
One step closer!  Master now compiles, though the resulting binary (predictably) crashes soon after the application window is drawn, as below.

```
(xenia:123426): Gdk-ERROR **: 14:00:10.924: The program 'xenia' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 344 error_code 9 request_code 149 (unknown) minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```
