### ISSUE TITLE
Title Updates

### ISSUE THREAD

**Issue by Djassie18698** [xenia-project/xenia#1826]
When are title updates coming back? The older canary version cant read my save files but can read the title update, the newer one cant read the title update but can read the saves but they're corrupt because they arent the same game version

**Comment by Arysr** [comment]
Well if you're strictly just playing for fun [emoose's STFS writer](https://github.com/emoose/xenia/releases/tag/mousehook-v1.13.4) currently supports title updates. it also makes some changes to the way saves work, to improve success rate among saving some games that are running title updates. So as always, back up your saves.

Please make sure to download the xenia_stfs-writer v1.05 at the bottom. I am not sure if this is common knowledge, but it will work with all your current folders (saves, title updates, etc) right from the get-go.

**Comment by legend800** [comment]
Wow, I just got DLC to load on Hydro Thunder for the first time ever on that build! Amazing! Now we just need to find a way to convert the saves safely over. :)

Master:
![2021-06-05 00_00_33-Window](https://user-images.githubusercontent.com/20983844/120883527-8d36ad80-c592-11eb-8ace-6fd7d251fa60.png)

Branch:
![2021-06-04 23_56_56-Window](https://user-images.githubusercontent.com/20983844/120883524-8b6cea00-c592-11eb-9dca-e5740529e987.png)

**Comment by Djassie18698** [comment]
Im not sure why but I had an older canary version and it worked with a TU i use with diablo 3, however it didn't save. But the stfs build doesnt read my diablo update and doesnt save once i leave the game

**Comment by Razzile** [comment]
I'd just like to point out that issues with the canary build belong on the canary repo, not here.
