### ISSUE TITLE
Xenia crashes after opening any game

### ISSUE THREAD

**Issue by Reaper2001** [xenia-project/xenia#1864]
Xenia crashes after opening any game, all games crashes cant go to the loading screen even even try dragging the game in xenia but it crashes before reading or starting 
 PC Specs i5 4 generation 8gb ram intel graphics 44000 what should i do

**Comment by enthiran01** [comment]
Bro u need good graphics card, intelligent hd graphics card are slower,
atleast nvidia gtx 970 and better or and rx 580 and above. Igpu graphics
are not good for emulation

**Comment by Reaper2001** [comment]
thank you bro will get it then tell you again

**Comment by Masamune3210** [comment]
the wild dudebros in their natural habitat

**Comment by Margen67** [comment]
@Reaper2001 Tech support belongs on the [Discord server](https://discord.gg/Q9mxZf9).
