### ISSUE TITLE
[Linux] build fails due to empty -l flags

### ISSUE THREAD

**Issue by belegdol** [xenia-project/xenia#1868]
I tried building Xenia on Fedora 34. With workaround for #1825 I was making good progress. Unfortunately, I hit the following issue a few times:
```
/usr/bin/ld: cannot find -l-lstdc++fs
```
This comes from
```
build/xenia-ui.make:LIBS += bin/Linux/Release/libxenia-base.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -l -lstdc++fs -ldl -llz4 -lpthread -lrt
```
There is an `-l` between `-lglib-2.0` and `-lstdc++fs`. In premake.lua there appears to be nothing wrong:
```
filter("platforms:Linux")
  system("linux")
  toolset("clang")
  buildoptions({
    -- "-mlzcnt",  -- (don't) Assume lzcnt is supported.
  })
  pkg_config.all("gtk+-x11-3.0")
  links({
    "stdc++fs",
    "dl",
    "lz4",
    "pthread",
    "rt",
  })
```
Any ideas where the `-l` comes from?

**Comment by jgoyvaerts** [comment]
Could it be a premake-core/premake-cmake bug? 
The extra -l is placed between the concatenation of the output of `pkg-config -libs gtk+-x11-3.0` and the normal linked libraries.

What happens if you remove `pkg_config.all("gtk+-x11-3.0")` from the premake and try again? I know it won't build but does it still output the extra -l then?

**Comment by belegdol** [comment]
With `pkg_config.all("gtk+-x11-3.0")` commented out the `-l` disappears:
```
LIBS += bin/Linux/Release/libxenia-base.a -lstdc++fs -ldl -llz4 -lpthread -lrt
```
I have then commented out the entire `links` block. This was the result:
```
LIBS += bin/Linux/Release/libxenia-base.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -l
```
So it looks like there is a trailing space or something in the pkg-config output.

**Comment by belegdol** [comment]
@JoelLinn, it appears that the issue is with tools/build/scripts/pkg_config.lua

**Comment by JoelLinn** [comment]
That scripts lacks error handling. Could you check what happens if you run pkg config manually on the shell for the relevant gtk dependency? 
I think you either miss a dev package or the pkg entry has a different name on non debian distros

**Comment by belegdol** [comment]
pkg-config output looks like this:
```
$ pkg-config --libs gdk-x11-3.0 
-lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 
```

**Comment by jgoyvaerts** [comment]
What about `pkg-config --libs-only-l gdk-x11-3.0 ` ?

**Comment by jgoyvaerts** [comment]
Maybe your output has a trailing space which would cause the for loop to run one extra time and cause this weird -l.
Try adding the following code at https://github.com/xenia-project/xenia/blob/master/tools/build/scripts/pkg_config.lua#L26
```
if (flag == "") then
    continue
end
```

**Comment by belegdol** [comment]
> What about `pkg-config --libs-only-l gdk-x11-3.0` ?
```
$ pkg-config --libs-only-l gdk-x11-3.0
-lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0
```

> Maybe your output has a trailing space which would cause the for loop to run one extra time and cause this weird -l.
> Try adding the following code at https://github.com/xenia-project/xenia/blob/master/tools/build/scripts/pkg_config.lua#L26
> 
> ```
> if (flag == "") then
>     continue
> end
> ```
I think there might be a trailing space in the output. Unfortunately adding the snippet results in a syntax error:
```
Error: /home/julas/cvs/xenia/tools/build/scripts/pkg_config.lua:28: syntax error near 'end'
```

**Comment by belegdol** [comment]
Looks good now:
```
LIBS += bin/Linux/Release/libxenia-base.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lstdc++fs -ldl -llz4 -lpthread -lrt
```
