### ISSUE TITLE
Game freezes on startup

### ISSUE THREAD

**Issue by jillv46** [xenia-project/xenia#1869]
So when I try to play resident evil revelations 2 the moment I start the game it doesn’t load. Revelations 1 works fine but revelations 2 doesn’t work. Why is this happening? Here’s a pic of what I get when starting the game
![D8B62252-81CF-4170-93F3-AEF0685C9CBE](https://user-images.githubusercontent.com/29643271/126162866-b23da86b-bf6d-4a5b-a0b3-e3d0ced1d6d0.jpeg)

**Comment by Triang3l** [comment]
https://github.com/xenia-project/game-compatibility/issues/38 is the preferred location for game-specific issues, interesting nonetheless, there have been major audio changes recently, though may be the kernel changes even.

**Comment by jillv46** [comment]
So how do I fix it?
