### ISSUE TITLE
after open the game and finish start display the xenia crashes

### ISSUE THREAD

**Issue by Sofeanalntsha000** [xenia-project/xenia#1872]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
Closing as the amount of information provided is nearly zero. See the [game compatibility tracker](https://github.com/xenia-project/game-compatibility/issues) for info about the game you're trying to play.
