### ISSUE TITLE
Xenia crashes after opening any games,i can play gears of war 2,but 3 and Judgment，after opening game，the screen shows that the archive is being read，then xenia crashes

### ISSUE THREAD

**Issue by ADA000** [xenia-project/xenia#1880]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Masamune3210** [comment]
Not a correctly written issue report, not a reason to issue a report, and not the right place for it anyway
