### ISSUE TITLE
xenia crashes after opening any game 

### ISSUE THREAD

**Issue by Reaper2001** [xenia-project/xenia#1890]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
Closing as absolutely zero information is provided.

**Comment by Reaper2001** [comment]
Everytime I try to launch a game it just says "xenia.exe has stopped working". Any ideas of what the problem might be?

My specs are fine:
Intel Core I5 4670k
AMD hd7570
Windows 10

**Comment by Triang3l** [comment]
This is not a tech support forum (#help on the Discord server is), but HD 7570 is based on the TeraScale architecture for which neither Direct3D 12 nor Vulkan was ever implemented. The minimum supported AMD GPU architecture is GCN.

**Comment by Reaper2001** [comment]
so it wont run on my pc should i get nvidia card

**Comment by Triang3l** [comment]
You should get a graphics card that supports Direct3D 12, but Xenia is very GPU-demanding, so a modern and a high-end one is heavily recommended.

**Comment by Reaper2001** [comment]
is there any way to run with these specs its a 1gb graphic card ddr5 128bit amd 7570 
its a bummer will nvidia card work

**Comment by Triang3l** [comment]
No, Xenia simply doesn't know how to communicate with your graphics card because it doesn't support Direct3D 12. Nvidia GT 400 series is the minimum, but for comfortable playing you need something on the GTX 1060 level at least.

**Comment by Reaper2001** [comment]
thanks for the help bro
