### ISSUE TITLE
Bright at night in x2 resolution scaling - RDR1

### ISSUE THREAD

**Issue by jacebeleren1408** [xenia-project/xenia#1901]
Anyone with the same issue when shooting a gun at night in RDR1 it gets very bright? I'm using x2 resolution scale. I know it's not stable at this resolution but do you guys happen to know any workarounds? Oh and also it when it is raining, the raindrops isn't visible.

**Comment by JoelLinn** [comment]
For game specific issue tracking, please use https://github.com/xenia-project/game-compatibility/issues/
