### ISSUE TITLE
bakugan battle brawlers flickering items and cards

### ISSUE THREAD

**Issue by aleksikan** [xenia-project/xenia#1906]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
While it's definitely an interesting GPU accuracy issue, please at least provide a description — in this repository, preferably with research details. For reports of symptoms, the game compatibility tracker is preferred — https://github.com/xenia-project/game-compatibility/issues/310

**Comment by aleksikan** [comment]
i didn't know i can send pictures my bad
![image](https://user-images.githubusercontent.com/93398767/139521992-188074bd-ecdf-45d8-b05e-130cb3331f3f.png)

![image](https://user-images.githubusercontent.com/93398767/139522008-679dc795-2daf-4323-a6b4-2a08e2540dec.png)

**Comment by Margen67** [comment]
Duplicate of #1907

**Comment by aleksikan** [comment]
> Duplicate of #1907

ion know how github works i thought u can't comment here when it is closed my baddd
