### ISSUE TITLE
Error when building xenia for android

### ISSUE THREAD

**Issue by lsgasu** [xenia-project/xenia#1912]
This is the error message:
"
In file included from C:\Users\user\xenia\src\xenia\cpu\backend\x64\x64_backend.h:16:
In file included from C:\Users\user\xenia\src\xenia\cpu\backend\backend.h:16:
C:\Users\user\xenia\src\xenia\cpu\thread_debug_info.h:76:14: error: field has incomplete type 'xe::X64Context' "

**Comment by Triang3l** [comment]
Not really an issue at the current stage of the development — this is a small sub-issue caused by the complete lack of Arm code generation.
