### ISSUE TITLE
WWE 2K14 WRESTLEMANIA ARENA'S BUG

### ISSUE THREAD

**Issue by Karimws5** [xenia-project/xenia#1916]
the WrestleMania arena's don't work in any of the mods (one vs one two vs two, 30 years of wrestlemania...) and it just shows a black screen , i hope you fix the problem.

**Comment by Triang3l** [comment]
Please use game entries in the compatibility tracker for game-specific issues without implementation details, for WWE 2K14 the entry is https://github.com/xenia-project/game-compatibility/issues/1361
