### ISSUE TITLE
Xenia Crash

### ISSUE THREAD

**Issue by fort-za** [xenia-project/xenia#1917]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
Zero information provided — closing.

**Comment by fort-za** [comment]
xenia keeps crashing

**Comment by Codexmsters** [comment]
XENIA KEEPS CRASHING
