### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#1922]
When running `xb setup` I get the following error:
```
PS C:\Users\marge\Documents\GitHub\xenia> .\xb setup
Setting up the build environment...

- git submodule init / update...

- running premake...
Error: no such action 'vs2022'
```

**Comment by brichan** [comment]
Updating premake-core solves this problem.
I am not sure to what extent updating the original premake-core will affect it.

**Comment by brichan** [comment]
The premake-core submodule has been updated ([#094c20b](https://github.com/xenia-project/xenia/commit/094c20bd4e9e1e57943880e8943f6409840c2818)) to support Visual studio 2022.

**Comment by gibbed** [comment]
Yeah, issue can be closed once we have confirmation VS2022 is working properly now.

**Comment by Razzile** [comment]
I have VS2022 installed and can give it a test tomorrow if nobody has done so by then

**Comment by Wunkolo** [comment]
I have been using VS2022 and can verify that it has been working!

**Comment by Margen67** [comment]
As additional confirmation: `Visual Studio 2022` builds successfully on AppVeyor.

**Comment by Darkhost1999** [comment]
Same

**Comment by TylerJaacks** [comment]
@Darkhost1999 I just commented out lines 514 and 515 in xenia-build file and it worked for me.  I wasn't able to build using xb build but just do xb devenv and upgrade the project and build in VS.

**Comment by Darkhost1999** [comment]
![Screenshot_20220708-223758_GitHub.png](https://user-images.githubusercontent.com/60384196/178090205-fb3e036d-eead-4345-b4ee-469d4acdb2d8.png)
These 2 lines in the def run platform premake for?

**Comment by TylerJaacks** [comment]
> ![Screenshot_20220708-223758_GitHub.png](https://user-images.githubusercontent.com/60384196/178090205-fb3e036d-eead-4345-b4ee-469d4acdb2d8.png) These 2 lines in the def run platform premake function?

yes this worked for me.

**Comment by Margen67** [comment]
This is also happening with GitHub Actions CI so this isn't just user error.

**Comment by Margen67** [comment]
I think this was caused by `premake-core` accidentally being downgraded/reverted.

Before vulkan merge: ![](https://media.discordapp.net/attachments/440280035056943104/995231706003025931/unknown.png)
https://github.com/xenia-project/xenia/tree/20fe7bc4b77ea9b5551bf870df4e49cfec4cfc3c/third_party

After: ![](https://media.discordapp.net/attachments/440280035056943104/995231706267275294/unknown.png)
https://github.com/xenia-project/xenia/tree/master/third_party

**Comment by Darkhost1999** [comment]
https://github.com/xenia-project/xenia/commit/ff35a4b3a1f3eef24c789cec6340a32fb64152eb
Premake is now fully successful without any hiccups or delays for me now.
I can't express how much a relief it is that building Xenia wasn't just a me problem.
Thanks guys, now to get to work.

**Comment by Margen67** [comment]
#1971

**Comment by wonderful2643** [comment]
using "vs2019" instead
