### ISSUE TITLE
xenia master crashes gameplay

### ISSUE THREAD

**Issue by Codexmsters** [xenia-project/xenia#1941]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Codexmsters** [comment]
https://www.youtube.com/watch?v=px-E5tGMpCY

**Comment by Masamune3210** [comment]
Literally says in the template that you didn't bother to read that this isn't the place for game compat issues.....

**Comment by Codexmsters** [comment]
fixed

**Comment by Codexmsters** [comment]
get blackscreen on xenia
