### ISSUE TITLE
crash caused by commit  0fdb855a11552d865beca9ba647502e53cf63ce1

### ISSUE THREAD

**Issue by ace1000** [xenia-project/xenia#1945]
[//]: # (Describe what's going wrong:)

After commit  0fdb855a11552d865beca9ba647502e53cf63ce1 xenia will always crash on my 2600k (AVX 1 only) no matter what game I try. 

[//]: # (Describe what should happen:)

xenia should correctly run as before this commit as it does if I revert that commit.

[//]: # (If applicable, provide a callstack here - esp. for crashes)

example crash dump from geometry wars 2

!> F8000028 ==== CRASH DUMP ====
!> F8000028 Thread ID (Host: 0x00001138 / Guest: 0x00000006)
!> F8000028 Thread Handle: 0xF8000028
!> F8000028 PC: 0x82099C58
!> F8000028 Registers:
!> F8000028  r0   = 0000000000000000
!> F8000028  r1   = 000000007018F9F0
!> F8000028  r2   = 0000000000000000
!> F8000028  r3   = 0000000040000270
!> F8000028  r4   = 0000000000000070
!> F8000028  r5   = 0000000000000060
!> F8000028  r6   = 0000000000003FF9
!> F8000028  r7   = 0000000040000278
!> F8000028  r8   = 0000000000000E07
!> F8000028  r9   = 0000000000003FF9
!> F8000028  r10  = 0000000000000000
!> F8000028  r11  = 0000000040040270
!> F8000028  r12  = 0000000082133768
!> F8000028  r13  = 000000000003D000
!> F8000028  r14  = 0000000000000000
!> F8000028  r15  = 0000000000000000
!> F8000028  r16  = 0000000000000000
!> F8000028  r17  = 0000000000000000
!> F8000028  r18  = 0000000000000000
!> F8000028  r19  = 0000000000000000
!> F8000028  r20  = 0000000000000000
!> F8000028  r21  = 0000000000000000
!> F8000028  r22  = 0000000000000001
!> F8000028  r23  = 0000000000000000
!> F8000028  r24  = 0000000000000000
!> F8000028  r25  = 0000000000000060
!> F8000028  r26  = 0000000040000270
!> F8000028  r27  = 0000000040000000
!> F8000028  r28  = 0000000000000001
!> F8000028  r29  = 0000000000000007
!> F8000028  r30  = 00000000400002E0
!> F8000028  r31  = 000000007018F9F0
!> F8000028  f0   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f1   = 3FE472B020000000 = (double)0.6389999985694885 = (float)1.0842022e-19
!> F8000028  f2   = 3FF19999A0000000 = (double)1.100000023841858 = (float)-1.0842022e-19
!> F8000028  f3   = 3FD60418A0000000 = (double)0.3440000116825104 = (float)-1.0842022e-19
!> F8000028  f4   = 3FF0000000000000 = (double)1.0 = (float)0.0
!> F8000028  f5   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f6   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f7   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f8   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f9   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f10  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f11  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f12  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f13  = 401921FB60000000 = (double)6.2831854820251465 = (float)3.689349e+19
!> F8000028  f14  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f15  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f16  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f17  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f18  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f19  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f20  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f21  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f22  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f23  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f24  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f25  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f26  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f27  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f28  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f29  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f30  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f31  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  v0   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v1   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v2   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v3   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v4   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v5   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v6   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v7   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v8   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v9   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v10  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v11  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v12  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v13  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v14  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v15  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v16  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v17  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v18  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v19  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v20  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v21  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v22  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v23  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v24  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v25  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v26  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v27  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v28  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v29  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v30  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v31  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v32  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v33  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v34  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v35  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v36  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v37  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v38  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v39  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v40  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v41  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v42  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v43  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v44  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v45  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v46  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v47  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v48  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v49  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v50  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v51  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v52  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v53  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v54  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v55  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v56  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v57  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v58  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v59  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v60  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v61  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v62  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v63  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v64  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v65  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v66  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v67  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v68  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v69  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v70  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v71  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v72  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v73  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v74  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v75  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v76  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v77  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v78  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v79  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v80  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v81  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v82  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v83  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v84  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v85  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v86  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v87  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v88  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v89  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v90  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v91  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v92  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v93  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v94  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v95  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v96  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v97  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v98  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v99  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v100 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v101 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v102 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v103 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v104 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v105 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v106 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v107 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v108 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v109 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v110 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v111 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v112 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v113 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v114 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v115 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v116 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v117 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v118 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v119 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v120 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v121 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v122 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v123 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v124 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v125 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v126 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v127 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]

[//]: # (If applicable, upload a logfile and link it here)
[xenia.log](https://github.com/xenia-project/xenia/files/7832513/xenia.log)

**Comment by Razzile** [comment]
Try the latest commit as there was a problem with the commit you linked that has since been fixed

**Comment by ace1000** [comment]
I tried 600c14b3f01803ea55653c59046a2250b9a0511d from appveyor it is still crashing there. however if I clone the repo and revert commit 0fdb855a11552d865beca9ba647502e53cf63ce1 only and build everything is working correctly so something from that commit still cases ever game to crash on my system. possibly it is emitting something that sandy bridge  processors do not have.

**Comment by Razzile** [comment]
cc/ @Wunkolo did any of your recent additions manage to slip through the "use haswell instructions" gate?

**Comment by Wunkolo** [comment]
All that stuff is totally guarded by `use_haswell_instructions`. And it is only enabled if it is detected on your system.
https://github.com/xenia-project/xenia/blob/975eadf17e8a4af93530d595ce06b14c8be7209b/src/xenia/cpu/backend/x64/x64_emitter.cc#L77-L93

The `2600K` does _not_ support bmi1 or 2, so `cpu_.has(Xbyak::util::Cpu::tBMI1)` should return false and it should not emit those instructions. The crash log doesn't seem to be saying enough info to diagnose the issue in case it is emitting an illegal instruction of some sort. It could be hitting an assert of some kind too. I'll see what happens on my end when I try to open `584108FF` on my 11900k.

**Comment by Wunkolo** [comment]
Found the issue. The non-BMI1 accelerated case was not handling its operands correctly. Should be fixed with #1951 if you have a chance to try it out.

**Comment by ace1000** [comment]
games are now running correctly on the latest master thanks.
