### ISSUE TITLE
Build error in Ubuntu

### ISSUE THREAD

**Issue by MoonDragon-MD** [xenia-project/xenia#1958]
I would like to try Xenia on Ubuntu 20.04. I started installing the following dependencies:
sudo apt-get install libgtk-3-dev libpthread-stubs0-dev liblz4-dev libx11-dev libx11-xcb-dev libvulkan-dev libsdl2-dev libiberty-dev libunwind-dev libc++-dev libc++abi-dev
sudo -E apt-get -yq --no-install-suggests --no-install-recommends install clang-6.0 clang-format-6.0
sudo apt-get install python3-opencv
"cd folder"
./xb build --config=release --target linux CC=clang-6
but I get the following error:
./xb: line 1: xenia-build: command not found
So I tried with:
python xenia-build premake --devenv=cmake
but I get the following error:
ERROR: Python 3.4+ must be installed and on PATH
Is anyone kind enough to explain to me step by step how to do it? 
Thanks in advance

**Comment by heroku-miraheze** [comment]
Please, install Python 3.4 or more supported, this will help.

**Comment by MoonDragon-MD** [comment]
> Please, install Python 3.4 or more supported, this will help.

the following pythons are installed on my system:
- Python 2.7.18
- Python 3.8.10

**Comment by heroku-miraheze** [comment]
Please, uninstall Python 2.7 and now try again.

**Comment by gibbed** [comment]
What does `python --version` output for you?

**Comment by JoelLinn** [comment]
> What does `python --version` output for you?

It's `python3` on most linux distros.
 

> Please, uninstall Python 2.7 and now try again.

That's a little bit dangerous, sadly some packages still depend on it

> `ERROR: Python 3.4+ must be installed and on PATH`

How did you download the sources? We currently require Python 3.6+.
Please either use git or Download the current master tarball from github

That being said, you won't get very far with xenia on Linux at the moment.

**Comment by gibbed** [comment]
> How did you download the sources? We currently require Python 3.6+.

I think the `linux` branch doesn't have the updated build scripts, so it would complain about 3.4. If that's what they're doing.

**Comment by JoelLinn** [comment]
Best to manually merge branches from #1430 into master
Also you may want to use a current compiler

**Comment by MoonDragon-MD** [comment]
Thanks for the answers, on Ubuntu you should not remove python 2.7 otherwise the operating system will be destabilized. I tried to see the version indicated by JoelLinn but I don't understand what I have to do. I tried to compile by downloading the zip but I have an initial error:
```
 $ ./xb build --config u003d release --target linux
WARNING: The source tree is unversioned. Version info will be omitted from all binaries!

Building release ...

- running premake ...
premake5 executable not found, attempting build ...
make: Bootstrap.mak: File or directory does not exist
make: *** No rules for generating the 'Bootstrap.mak' target. Stop.
ERROR: cannot build premake5 executable.
```
Should I wait for them to update?

**Comment by JoelLinn** [comment]
I forgot, tarball download will not include submodules. You are missing the git submodules, hence no premake.



I hate to break it to you but this project will currently not work as a native linux build. Unless you are familiar with assembler level debugging and systems engineering (or want to get familiar with it), there isn‘t much you can do about it.

**Comment by MoonDragon-MD** [comment]
Thank you for the explanation. It will mean that I will wait for better times to try it :P

**Comment by Razzile** [comment]
Closing as there is no actual issue here as far as I can tell
