### ISSUE TITLE
VS2022 compiler bug/undefined behavior with GetDepthControlForCurrentEdramMode

### ISSUE THREAD

**Issue by gibbed** [xenia-project/xenia#1971]
The call in `GetHostViewportInfo` to `GetDepthControlForCurrentEdramMode` where it checks `.z_enable` of the result generates broken code in MSVC v19.30 (VS2022). It generates correct code on v19.29 (VS2019).

Relevant godbolt with the isolated code: https://godbolt.org/z/6aG8e8qMr

**Comment by Gliniak** [comment]
Fixed in MSVC v19.35
