### ISSUE TITLE
Bug: X69 Monster Jam Battlegrounds -XBOX360 [XBLA] in game play is stop.

### ISSUE THREAD

**Issue by tee4341** [xenia-project/xenia#1975]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

X69 Monster Jam Battlegrounds -XBOX360 [XBLA] in game play is stop
![screenshot 1](https://user-images.githubusercontent.com/48321898/151716627-2e58f04c-aaa8-4a16-9e74-204c1b73c362.jpg)
.

### Describe what should happen

after play game is stop.

**Comment by Prism019** [comment]
Game compatibility reports belong on the https://github.com/xenia-project/game-compatibility/issues compatibility tracker.
Please make sure your report there follows the guidelines or it will automatically be closed.
