### ISSUE TITLE
Wiki Improvement: Update Wiki FAQ from XQEMU to xemu

### ISSUE THREAD

**Issue by MasonT8198** [xenia-project/xenia#1980]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

XQEMU has since become defunct and xemu is more functional and in a better state for being used, the FAQ page isn't available to be written to in a PR or else I'd save you the trouble and do it myself, this seems like most edits are made by @Margen67 so I'll point this mainly towards you

### Describe what should happen

Don't think this is applicable to the subject so, N/A

**Comment by halotroop2288** [comment]
Hi, new wiki dev here. The new wiki will include mention of both.

**Comment by MasonT8198** [comment]
> Hi, new wiki dev here. The new wiki will include mention of both.

oh alright!

it's rather annoying that github doesn't allow all wiki pages to be available for a Pull Request :/

**Comment by MasonT8198** [comment]
closed as this was dealt with thanks @halotroop2288

**Comment by Margen67** [comment]
XQEMU is basically dead, so not much reason to list it at all.
