### ISSUE TITLE
Window too big when using high resolution with scale

### ISSUE THREAD

**Issue by paulomanrique** [xenia-project/xenia#1986]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Whenever you have a big monitor with scale applied, Xenia window open way bigger than it should, because it's applying the % scale windows says.

![image](https://user-images.githubusercontent.com/4464977/153770054-1e31c1ca-cadb-456a-aff2-c44585fb9585.png)

### Describe what should happen

Window should remain proportionally at same size when scale = 100%.

**Comment by Triang3l** [comment]
This is by design, the window should take roughly the same size in physical units on, for instance, a 15.6" 1920x1080 laptop with 140% scale, and a 15.6" 1366x768 laptop with 100% scale.
