### ISSUE TITLE
Ignoring portable.txt?

### ISSUE THREAD

**Issue by djstevens** [xenia-project/xenia#1995]
Hi All,

Excellent work with this! I've got xenia running smoothly, but I've noticed that it doesn't seem to acknowledge the portable.txt (or portable.ini -- I tried both) file I created in the same directory as the .exe. It continues to use my Documents/xenia folder as the content folder.

I tried editing the config file to specify the content directory that way, but xenia doesn't start up when I do that.

Am I missing something? I'm running 64-bit Win10, for what it's worth.

**Comment by halotroop2288** [comment]
GitHub is not for tech support. Your issue may be caused by your Xenia executable being in a protected folder.

***Please ask in [the Discord](https://discord.gg/Q9mxZf9)'s #help channel if you have further questions.***
