### ISSUE TITLE
xenia & windows 11

### ISSUE THREAD

**Issue by Datzibu** [xenia-project/xenia#1996]
xenia does not work on windows 11 setting xenia compatibility mode to windows 8 runs a game then guest has crashed happens

**Comment by JoelLinn** [comment]
generally, windows 11 is supported the same as windows 10. what game are you trying to run, it might be a game issue

**Comment by Datzibu** [comment]
games i tryed are too human wwe 2k16 and forza motorsport 4 all of em crash only game that works is golden eye xbla remake

**Comment by JoelLinn** [comment]
Golden eye works without compat mode?

**Comment by Datzibu** [comment]
yep i know its not my pc bec i have an i7 an rtx 3060 video card and 16gb of ram

**Comment by JoelLinn** [comment]
https://github.com/xenia-project/game-compatibility/issues states the two games are not stable. Please report your findings there for the individual games.
