### ISSUE TITLE
Schizoid - Crashes on startup

### ISSUE THREAD

**Issue by DragonEyeNinja** [xenia-project/xenia#1997]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [ ] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

I am not knowledgeable in emulation, but something is giving and Schizoid refuses to launch.

Error reads:
"The guest has crashed.

Xenia has now paused itself.
A crash dump has been written into the log."

Tells me nothing. Can someone else find out what is going on?

### Describe what should happen

Game should start and at least be functional

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-project/xenia/files/8171677/xenia.log)

**Comment by Prism019** [comment]
This issue tracker is not for game-specific issues. Please report it [here](https://github.com/xenia-project/game-compatibility/issues) instead of the main Xenia repository.
