### ISSUE TITLE
Account banned

### ISSUE THREAD

**Issue by Washong** [xenia-project/xenia#2014]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Help me I was hacked I think and I got banned btw this is Prism Daymon
![gdhr0fj9k8u51](https://user-images.githubusercontent.com/104286034/164954070-c6ef8a2f-3e01-4cad-b450-183dd04074eb.jpg)

### Describe what should happen

help

### If applicable, provide a callstack here, especially for crashes

nope

### If applicable, upload a logfile and link it here

nope

**Comment by Washong** [comment]
Can I have the collaborator role please for within @ma

**Comment by Margen67** [comment]
https://github.com/ps2homebrew/Open-PS2-Loader/issues/636
https://github.com/hrydgard/ppsspp/issues/15497
https://github.com/Jiiks/BetterDiscordApp/issues/994
https://github.com/jonmosco/kube-ps1/issues/153
