### ISSUE TITLE
Sonic unleashed sudden crash in graphic fallowed by xenia completely crash 

### ISSUE THREAD

**Issue by sonic1385** [xenia-project/xenia#2021]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Sonic unleashed sudden crash in graphic as if the objects crashed to each other and then xenia completely crashed 

### Describe what should happen

the game should had any problem in that place and it should have go smoothly

### If applicable, provide a callstack here, especially for crashes

opening the game - past menu - past some part of the game - images crash - xenia complete crash 

### If applicable, upload a logfile and link it here

[xenia.zip](https://github.com/xenia-project/xenia/files/8786237/xenia.zip)

**Comment by Margen67** [comment]
maidenless
