### ISSUE TITLE
Cant Launch 

### ISSUE THREAD

**Issue by Frexs2002** [xenia-project/xenia#2032]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Hi recently i downloaded xenia emulator and tried it but when i launch the software it opens for 0.1 seconds then dissepears its not a requirments problem ive seen people playing it with 2gb ram
heres the error
[xenia.log](https://github.com/xenia-project/xenia/files/8941741/xenia.log)
here pls HEEEEEEEEEEEEEKO

### Describe what should happen

should open

**Comment by Triang3l** [comment]
First of all, you've checked "This issue isn't for tech support (help with Xenia)", yet you're still asking a tech support question.

However, you don't have a compatible graphics card (even though you've checked "My device meets the minimum requirements") according to the log — a graphics card that supports the Direct3D 12 API with at least the Direct3D feature level 11_0 is required.
