### ISSUE TITLE
Perfect Dark voice cut off issue

### ISSUE THREAD

**Issue by backgamon** [xenia-project/xenia#2041]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Voice in Perfect Dark cut off.

### Describe what should happen

After a while (in introduction by ex) voice of characters cut off:

This is the issue (latest Xenia official):
https://www.youtube.com/watch?v=Zx3h9ndpNE0

This is the same but with a older build (10 june 2021 official too):
https://www.youtube.com/watch?v=Zx3h9ndpNE0

Issue seem to happen since the change of LIBAV to FFMPEG.

**Comment by Margen67** [comment]
This belongs on the game compatibility report.
