### ISSUE TITLE
Is there a Google Play or Samsung Galaxy Store edition of Xenia?

### ISSUE THREAD

**Issue by PlayfulBowl3512** [xenia-project/xenia#2043]
I can't download it if it's an apk, as my family manages my phone, and I can't change the setting to download from unknown sources. If not, plz try to publish ur apk's code to Google Play or Galaxy. Either one. Thx.

**Comment by CobeSoft-dev** [comment]
I've found an Android version at this link: https://apkod.com/xenia-emulator-android/
But I can't find it on the official website
