### ISSUE TITLE
Xenia crashes on Linux with Lutris / Proton GE

### ISSUE THREAD

**Issue by Bboy486** [xenia-project/xenia#2045]
I have tried to add Xenia a few ways:

1. Via Proton GE on Steam Deck
2. Via Lutris via wine
3. Both Xenia + Xenia Canary

I am trying to launch Goldeneye but Xenia crashes. Both of the logs are for the two versions in Lutris. 
[xenia.log](https://github.com/xenia-project/xenia/files/9285051/xenia.log)
[xenia-canary.log](https://github.com/xenia-project/xenia/files/9285059/xenia-canary.log)

**Comment by Fabxx** [comment]
I think you need to uise vkd3d-proton for directX12 or, use the --gpu vulkan as a launch argument for the xenia exe

**Comment by YamiYukiSenpai** [comment]
Did you get it to work?

**Comment by austinarchibald** [comment]
> I think you need to use vkd3d-proton for directX12 or, use the --gpu vulkan as a launch argument for the xenia exe

Thank you! Trying to get this working for hours. Am using EmuDeck (replicated Cemu launcher but changed names/locations of Cemu to Xenia) then have these arguments in Steam: `"/run/media/mmcblk0p1/Emulation/tools/launchers/xenia.sh" --fullscreen --gpu vulkan "Z:/run/media/mmcblk0p1/Emulation/roms/xbox360/roms/Goldeneye/defaultCE.xex"`

Finally got it to work. Runs suprisingly well!

**Comment by Triang3l** [comment]
These are issues with Proton and VKD3D, not Xenia. VKD3D doesn't implement some of the valid Direct3D 12 API usage scenarios we have, and we have no intention to make workarounds for that as in case of translation layers, reversing the roles would be undesirable for the quality of both Xenia and VKD3D (for which Xenia is one of the real-life test cases).

**Comment by Smoker1** [comment]
I am also having a Issue with it on my Steam Deck with EmuDeck. I have 2 Versions (the Port Proton Build, and also the EmuDeck Build (Proton)

Port Proton - Tried to Load a ISO, it closed out. Tried to Load a XBLA, it works, but not getting everything Loaded

Proton (EmuDeck) - Mouse (Right Mouse Pad) does not work. Seems certain Apps want to Disable it. I even get Issues with RPCS3 on both my PC and Steam Deck at times (Open the App, and depending on how many Windows are Open, the Mouse moves a certain Direction by itself. Can still move the Mouse where I am wanting, but it still wants to move that one Direction). But with Xenia, it will not work, so I have to use the Screen which is a pain to get accurately, and too many times trying to get the right Menu Listing...it freezes the System requiring a Restart
