### ISSUE TITLE
Want to add Alpha Protocol to list of uninstallable games

### ISSUE THREAD

**Issue by has207** [xenia-project/xenia#2048]
There's a section in the Quickstart wiki page that lists known uninstallable games, I would like to submit "Alpha Protocol" to that list but couldn't find a way to edit the wiki myself so submitting an issue with someone with more knowledge or access. I own the disc version of this game and going to Game Details there is no Install option for this one, so far it's the first such disc I found in my collection.

**Comment by Margen67** [comment]
I've created a game-compatibility label for this: https://github.com/xenia-project/game-compatibility/labels/no-disc-install
