### ISSUE TITLE
Condemned: Criminal Origins

### ISSUE THREAD

**Issue by mysterystain** [xenia-project/xenia#2068]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [ ] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Audio issues.
Desynch in cutscenes and in-game, slight.
Very noticeable at end of menu cutscene.
Music/Ambience will stop playing after a few seconds after beginning.
Second level specific: Died once after elevator, reloading checkpoint caused severe, location-based audio issues in the form of various but most commonly a buzzing. 
Some crackling in the room where Malcom calls for a second time.
Also end-mission text displayed improperly. 

### Describe what should happen

None of the audio issues occurred on real hardware.
End-mission log text display (DUMMY) should not occur. Instead of listing DUMMY # or an empty space, it should list achievements gained. Upon returning to menu and checking achievements, nothing was unlocked. 
![Untitled](https://user-images.githubusercontent.com/108964567/192040941-dcaea19e-7419-4038-be4e-0f3d6ec498c4.png)

**Comment by Razzile** [comment]
This is probably for the compatibility repo instead. https://github.com/xenia-project/game-compatibility/issues
