### ISSUE TITLE
Ninja Gaiden II - Audio mutes after random period of time

### ISSUE THREAD

**Issue by HappehLemons** [xenia-project/xenia#2069]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When you start the game, it works fine, but after a random period of time, it completely mutes.
Sometimes happens at startup when you're at the main menu, sometimes happens during gameplay.

There' doesn't seem to be an obvious trigger, but once the audio mutes a restart of the emulator is required to restore it.

This seems to have been happening since 2021 September:
https://youtu.be/uSf-inSoadY?t=271

Happening in current canary version 203267b as well. 

### Describe what should happen

Audio should not mute.

**Comment by Margen67** [comment]
This belongs in the game compatibility report.
