### ISSUE TITLE
"Canary Latest Build Used" Ninja Gaiden 2 crashes after every level ends

### ISSUE THREAD

**Issue by ParagonXIIV** [xenia-project/xenia#2085]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When I start Ninja Gaiden 2 and complete a level after it tries to go into the next level Xenia Canary crashes to desktop. This also was tested for all levels it does the same thing. It is not playable at all. Been a issues also, for over 2 years now. 

### Describe what should happen

It needs to be patched and updated not sure why this happens on your latest build of xenia canary?

**Comment by Margen67** [comment]
Learn how to read:
![image](https://user-images.githubusercontent.com/3462541/199493869-e265a742-3263-44f7-8d4a-cd378ea49e78.png)
# The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
