### ISSUE TITLE
Xenia tries to open an ms-gamingoverlay link without checks

### ISSUE THREAD

**Issue by halotroop2288** [xenia-project/xenia#2086]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Whenever Xenia is opened on a Windows 10 installation which doesn't include the Gaming Overlay, the following pop-up error appears, blocking input from controllers.

!["You'll need a new app to open this ms-gamingoverlay link"](https://media.discordapp.net/attachments/308194948048486401/1038107447459594271/image.png "Screenshot of the error")

This is likely because of a missing check for the gaming overlay being installed, assuming that the user is using a standard, unmodified edition of Windows. In this case, I have removed all unnecessary packages from my Windows installation.

### Describe what should happen

This pop-up should not appear.

**Comment by gibbed** [comment]
To my knowledge, this isn't something Xenia is doing directly. This is probably some Windows API that we rely on causing this, which would likely mean it's not something we could change.

**Comment by Masamune3210** [comment]
Ms-gamingoverlay is the Game Bar, and it is very much included in Windows 10. Either you removed it, it's somehow damaged, or you installed Windows from a modified image or script that prohibited it from installing as standard

**Comment by Skynet19972029** [comment]
Masamune is right.
Though, the easy fix is, go to Start>Settings>Gaming
Toggle off "Open Xbox Game Bar"

**Comment by illusion0001** [comment]
Not a xenia issue, if your windows installation doesn't have game bar, you'll get the prompt regardless of application.

**Comment by Margen67** [comment]
> Not a xenia issue, if your windows installation doesn't have game bar, you'll get the prompt regardless of application.

This is further proven by the fact Xenia doesn't open it itself:
 * https://github.com/xenia-project/xenia/search?q=gaming
 * https://github.com/xenia-project/xenia/search?q=ms-gamingoverlay

**Comment by chrisps** [comment]
This is a deeply internal Windows thing. Windows.Gaming.UI.GameBar.dll is the one that tries to open that link, which obviously is not a library we import, it is a WinRT interface and its not clear what references it, but it's probably done through Windows.Gaming.Input which is imported by XinputUAP which is imported by Xinput1_4.dll which is imported by Xenia (the most likely one because that is explicitly gaming related), or d3d12.dll or dxgi.dll. The earlier commenters are right, you can't give them a "thumbs down" just because the facts don't align with your initial take.

**Comment by Masamune3210** [comment]
Don't intentionally damage your Windows install and this stuff wont happen. Simple as that.
