### ISSUE TITLE
Persistent hardware crash Windows 11

### ISSUE THREAD

**Issue by virtual-man007** [xenia-project/xenia#2088]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Attached below memdump that might help me understand why is xenia (stable) crashing constantly after 30+ sec in game (any game and my system halts completely, reboots on it's. Own, any help would be appreciated as I'm losing my mind and I have latest windows 11 updated and nvidia drives all up to date.

### Describe what should happen

Persistent crash with xenia stable on windows 11 with latest nvidia drivers 3070.

### If applicable, provide a callstack here, especially for crashes

BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  dwm.exe

STACK_TEXT:  
ffff808f`a83d6670 fffff807`0ed8a4ed     : 00000000`00000001 ffff928f`6ed2b7e0 00000000`00000001 ffff928f`6ef17000 : nt!RtlRaiseStatus+0x4f
ffff808f`a83d6c10 fffff807`274a081d     : 00000000`00000000 00000000`00000000 00000000`00000280 ffffbe86`dd12b160 : nt!KeReleaseSemaphore+0x19d
ffff808f`a83d6c90 fffff807`2730e69a     : ffff808f`a83d75f0 00000000`00000000 ffffbe86`e3690010 00000000`00000105 : dxgkrnl!DxgkGetPresentHistoryInternal+0x70d
ffff808f`a83d6eb0 fffff807`2730e46d     : ffffbe86`db8cae10 ffffbe86`00000000 ffffbe86`db8cae10 00000000`00000000 : dxgkrnl!CTokenManager::ProcessDxgkAdapterTokens+0x18a
ffff808f`a83d77b0 fffff807`2731aca9     : 00000000`00000000 ffff928f`6d85d760 00000000`00000000 ffff808f`a83d7940 : dxgkrnl!CTokenManager::ProcessTokens+0x17d
ffff808f`a83d7870 fffff807`27311d90     : 00000000`00000000 ffff808f`a83d7a60 ffffbe86`db4dc500 000000e7`ee2ff550 : dxgkrnl!CTokenManager::TokenThread+0x79
ffff808f`a83d78c0 fffff807`0ee3d1e5     : ffff928f`6ef15080 000001f8`10c61450 00000000`00000020 00000000`00000001 : dxgkrnl!NtTokenManagerThread+0x1c0
ffff808f`a83d79e0 00007ffc`fc7387d4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x25
000000e7`ee2ff838 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ffc`fc7387d4

SYMBOL_NAME:  dxgkrnl!DxgkGetPresentHistoryInternal+70d

MODULE_NAME: dxgkrnl

IMAGE_NAME:  dxgkrnl.sys

IMAGE_VERSION:  10.0.22621.815

STACK_COMMAND:  .cxr 0xffff808fa83d6130 ; kb

BUCKET_ID_FUNC_OFFSET:  70d

FAILURE_BUCKET_ID:  0x3B_C0000047_dxgkrnl!DxgkGetPresentHistoryInternal

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {bd161d58-4d5a-f322-b36e-6b23e4cd4960}

Followup:     MachineOwner
---------

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-project/xenia/files/10002435/xenia.log)

**Comment by virtual-man007** [comment]
deleted cache and content folder problem solved it seems for now.

**Comment by Sijinshu** [comment]
Hey ghost,
we has meet the same issue on AMD(igpu) + Nvidia(dgpu) hybrid mode platform, can you remember the root cause and fix solution of this issue？thanks.

**Comment by Masamune3210** [comment]
> Hey ghost, we has meet the same issue on AMD(igpu) + Nvidia(dgpu) hybrid mode platform, can you remember the root cause and fix solution of this issue？thanks.

Ghost means that the profile that made the comment has been deleted....
