### ISSUE TITLE
Very apparent screen flickering when playing at 2x resolution scale (not default 720p)

### ISSUE THREAD

**Issue by InSovietCS** [xenia-project/xenia#2091]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Hi All, 

Issue at hand: when scaling the resolution by 2x on both x and y axis causes constant fast and severe flickering. (tested on Modern Warfare 2, Call of Duty 4 and Burnout Revenge, for those who wish to try and replicate). This issue does not occur nearly as often when not scaling (blinking is very rare and sometimes does not even happen)

Please find attached the Modern Warfare 2 test footage to see how it looks.

Apart from that, not much else is wrong and nothing related to this specific issue.

### Describe what should happen

No flickering should occur, as there's no good reason for it to occur. Modern build, updated OS, updated drivers.

### If applicable, upload a logfile and link it here

https://pastebin.com/u6DBq9vZ

**Comment by Masamune3210** [comment]
This should probably go on xenia-compatibility

**Comment by Blackbird88** [comment]
This happens in lot of games I tried, not even sharing engine or any other tech which makes me wonder what do those games all have in common.

**Comment by Margen67** [comment]
Resolution scaling is a hack, and is expected to have issues.

**Comment by Razzile** [comment]
I feel like this issue actually might be worth keeping open as it could still be investigated. @Triang3l what do you think?

**Comment by ShadowTheLight** [comment]
I'm in the same spot with Sonic The Hedgehog (2006), setting the resolution to 1440p makes the water and sky flicker. Everything else is fine except the flickering. I've looked at like 10 Reddit posts about this and the all just say Sonic 06 is just buggy or that it just happens when you emulate it. I'll report here if I ever find a solution, it would be great to be able to play the game in 1440p.

**Comment by ttenor12** [comment]
Happens on Splinter Cell Double Agent as well.
