### ISSUE TITLE
Diablo 3 Reaper of Souls. Xenia insta crashes when trying to load the saved data 

### ISSUE THREAD

**Issue by CVG1Ger** [xenia-project/xenia#2099]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Hey, my problem is that when i open Diablo 3 for the first time i can play all the time i want without any issues, but if i close Xenia and re open the game, when it starts to load the saved game data, it crashes. Any idea how can i fix this?

My PC info: Intel i3 9100f, RTX 2060 Super, EVGA 600W 80+ White, ASrock H310CM-HDV, 16 GB Patriot 3200mhz.

### Describe what should happen

It should load normally the saved game data but it crashes when trying to load it.

**Comment by Masamune3210** [comment]
![Screenshot_20221208-143225.jpg](https://user-images.githubusercontent.com/1053504/206561582-4c2a1cc9-070c-4d83-a802-9b4d81cb080d.jpg)
