### ISSUE TITLE
[feature] Offline mode by default option

### ISSUE THREAD

**Issue by Shituation** [xenia-project/xenia#2107]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Xenia shows a prompt to choose between online and offline profiles, the problem is this prompt cannot be controlled with a gamepad, so it kills couch gaming. 

Using headless mode will use the default "online" option in the prompt which causes a deadlock.

![1](https://user-images.githubusercontent.com/43975882/211163214-965c9409-e25e-4f7e-9f7b-899b14e97c17.png)

### Describe what should happen

It would be nice to have a "default to offline" or a way to control the prompt with the gamepad.

**Comment by Margen67** [comment]
#1088

**Comment by gir489returns** [comment]
What the hell is the point of this request? You can't even connect to the XBOX live servers anyway? It should just default to offline.

**Comment by Triang3l** [comment]
The text in this popup is provided by the game itself if I understand correctly, Xenia just shows what the game asks it to show.
