### ISSUE TITLE
d3d12 doesn't work on Navi 3x cards

### ISSUE THREAD

**Issue by bigstusexy** [xenia-project/xenia#2133]
Hello, 

I'm technical, but not a programmer - regular user.  

I believe Xenia does not work with d3d12 on Navi 3x cards. 

Master Jan Jan 29 2023
Canary Feb 17th 

Video card 7900 xts (driver upto date)
CPU Ryzen 9 7950x
Memory 64GB
OS Upto date Win 10 64 (22H2)

Master just closes when loading anything.  One may see a split second of a screen and then it closes.  I *think* I see the loading icon of first starting Scott Pilgrim vs the World - it doesn't animate, it's just a flash. 

Canary spits two errors then closes. (attached)

Changing gpu to vulkan runs just fine as vulkan can run I think.
I still have a copy of Master from Dec 13 '21, I think this is before d3d12 and it runs just fine. 

Both current versions run on my older system with an RX 580 (driver probably isn't up to date)

Also, as far as I know Navi 3x cards are still separate drivers from the rest of the AMD Driver package. 

![Xenia 2a](https://user-images.githubusercontent.com/47860316/221066177-fe0925e8-c704-43d3-b390-3f1c083efeae.jpg)
![Xenia 1a](https://user-images.githubusercontent.com/47860316/221066178-1fb84a5c-4858-4ddc-b05f-132c6be0f56b.jpg)

If I can provide anything else, please let me know.

**Comment by Razzile** [comment]
The error indicates this is happening on xenia canary, could you also try standard xenia too?

**Comment by Gliniak** [comment]
https://github.com/xenia-canary/xenia-canary/issues/129#issuecomment-1430285768

**Comment by bigstusexy** [comment]
@Razzile , Yes I did try this on Master as well, the latest Janurary release, there is no error just close. 

@Gliniak ,  Thank you, I will try this setting 
d3d12_remove_retc_from_geometry_shader = true 
and report back, I understand the risks.  Also sorry, I did do a search for 7900 and so on but I must have done it wrong as it turned up no results.

**Comment by bigstusexy** [comment]
Yep, that did it for Canary @Gliniak.

Thank you.
