### ISSUE TITLE
BACKBREAKER xbox-360 field-is-blacked-out

### ISSUE THREAD

**Issue by jiddly** [xenia-project/xenia#2139]
https://github.com/RPCS3/rpcs3/issues/7518

i have the same issue as the link above but on Xenia. I do not know how to disable Asynchronous Shader to fix the field being blacked out

please help so i can enjoy this game

![image](https://user-images.githubusercontent.com/127419298/224065247-6ea4df20-5d2a-4465-b7f9-dd25c5e94f1c.png)

**Comment by DerpDylan** [comment]
desperately looking for a fix for this
