### ISSUE TITLE
[Linux] Builds failing

### ISSUE THREAD

**Issue by Shoegzer** [xenia-project/xenia#2147]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Builds from recent master are failing on linux, apparently for Discord-related reasons.  Log excerpt:
```
In file included from ../third_party/discord-rpc/src/discord_rpc.cpp:3:
../third_party/discord-rpc/src/backoff.h:3:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
X86ATTInstPrinter.c
aes.c
X86Disassembler.c
1 error generated.
make[1]: *** [discord-rpc.make:182: obj/Linux/Release/Linux/Release/discord-rpc/discord_rpc.o] Error 1
```
Test info:

* OS: Linux Mint 21.1 / kernel 5.15
* CPU: Intel i7-10870H
* Commit tested: 75d805245d2fcfca69993d3dc01bb43697bd28c4
* Last known good build: 4a2f4d9cfe28847039ccf939f68a0d486796398b

### Describe what should happen

Xenia should build.

### If applicable, provide a callstack here, especially for crashes

N/A

### If applicable, upload a logfile and link it here

Log: [build.log](https://github.com/xenia-project/xenia/files/11192205/build.log)

**Comment by meequrox** [comment]
Tried to build from master branch on a fresh install of Linux Mint 21.1, here is the list of packages I manually installed:
`libgtk-3-dev libsdl2-dev liblz4-dev libx11-xcb-dev clang llvm`.

The build failed with the following messages:
```
../third_party/discord-rpc/src/backoff.h:3:10: fatal error: 'algorithm' file not found
../third_party/fmt/include/fmt/format-inl.h:11:10: fatal error: 'cassert' file not found
../third_party/rapidjson/include/rapidjson/rapidjson.h:39:10: fatal error: 'cstdlib' file not found
../third_party/glslang/SPIRV/spvIR.h:52:10: fatal error: 'algorithm' file not found
../third_party/fmt/include/fmt/os.h:16:10: fatal error: 'cerrno' file not found
../third_party/rapidjson/include/rapidjson/rapidjson.h:39:10: fatal error: 'cstdlib' file not found
    ...
ERROR: build failed with one or more errors.
```

Since clang is used for building, I tried to build a simple helloworld with the `-v` option and found out that clang chooses path `/usr/lib/gcc/x86_64-linux-gnu/12` and cannot find libraries in `/usr/lib/gcc/x86_64-linux-gnu/12/include/c++`.

Then I **manually installed `g++-12`** and tried again - built successfully. Back to xenia:
```
    ...
make: Leaving directory '/home/user/xenia/build'

Success!
```

Looks like a distro-specific LTS thing, not a bug. By the way, on Arch it compiled on the first try :)

**Comment by Shoegzer** [comment]
Hey thanks.  I opened this issue presuming it would build on gcc-11 as it has in the past, though I tried again with gcc-12 and it built successfully as you've observed.  So I agree that it seems to be more of a distro/compiler issue.  Not sure exactly of the cause, but since it builds with a more recent compiler I'll close this.
