### ISSUE TITLE
Forza motorsport 4 crashes when patch is applied

### ISSUE THREAD

**Issue by kamil00110** [xenia-project/xenia#2155]
Forza motorsport 4 crashes when patch is applied when patch is disabled 
![Unhandled Exception in Xenia 13 05 2023 []([](15_46_52]([](https://github.com/xenia-project/xenia/assets/68923965/6ff783bf-c5d8-45c8-b3e7-c4249c947c81))))

**Comment by CodeNinja-sys** [comment]
Try install visual c++ or try other version Xenia
