### ISSUE TITLE
Ridge racer 6 artifacts non playable

### ISSUE THREAD

**Issue by sharicov** [xenia-project/xenia#2158]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Getting graphical artifacts in the game itself (intro and menus are fine.
Windows 11 22h2
Radeon 6900
latest drivers, latest xenia build (same artifacts in master and canary builds)

### Describe what should happen

based on youtube game should be playable

**Comment by JohnHenry150** [comment]
Known issue. You need to download this AMD Radeon™ driver to fix it.
**https://drivers.amd.com/drivers/radeon-software-adrenalin-2020-20.12.1-win7-64bit-dec8.exe**

**Comment by Gliniak** [comment]
> Known issue. You need to download this AMD Radeon™ driver to fix it. **https://drivers.amd.com/drivers/radeon-software-adrenalin-2020-20.12.1-win7-64bit-dec8.exe**

That's incorrect. RR6 have issues with gpu cache invalidation. This issue can be mitigated once by pressing F5 or in case of canary whole time by changing: ``d3d12_clear_memory_page_state`` to true

**Comment by JohnHenry150** [comment]
> That's incorrect. RR6 have issues with gpu cache invalidation (and that's Xenia fault, not drivers). This issue can be mitigated once by pressing F5 or in case of canary whole time by changing: `d3d12_clear_memory_page_state` to true

Hello, Gliniak. One possible solution is to press F5 to clear the cache. However, this is only be a temporary fix and may need to be repeated periodically which isn't ideal at all.

Changing `d3d12_clear_memory_page_state` doesn't apply to this issue. Therefore, changing it won't have any effect at all.

**Comment by Gliniak** [comment]
But you know that code that is used for ``d3d12_clear_memory_page_state`` is basically simplified version (for less performance impact it only executes code related to invalidation of memory to fix corruption and vertex explosions) of clearing cache that you're doing while pressing F5, which means it is applicable.

Additionally I have RR6 and I am well aware what issues it has.

**Comment by JohnHenry150** [comment]
> But you know that code that is used for `d3d12_clear_memory_page_state` is basically simplified version (for less performance impact it only executes code related to invalidation of memory to fix corruption and vertex explosions) of clearing cache that you're doing while pressing F5, which means it is applicable.
> 
> Additionally I have RR6 and I am well aware what issues it has.

As far as I'm aware, `d3d12_clear_memory_page_state` is not related to cache invalidation and is not a simplified version of clearing the cache with F5.

Anyway, if you're experiencing issues with GPU cache invalidation in RR6, then you might want to try using the driver that I sent. That might help resolve the issue.

**Comment by JohnHenry150** [comment]
Adrian, do you have any inquiries about this?

**Comment by JohnHenry150** [comment]
> Thanks all for your suggestions, F5 fixed the issue, d3d12_clear_memory_page_state didn't, still using latest AMD drivers (didn't downgrade).

Pressing F5 is a temporary solution, downgrade to the driver I sent and it'll be fixed permanently.

**Comment by sharicov** [comment]
Thanks, you're right, but it's not a big deal from me, I prefer to stay with latest AMD driver for better performance and compatibility in other games.

**Comment by Gliniak** [comment]
That's enough. You're not a contributor here nor anyone that is related to this project and that's definitely an escalation.

@sharicov Strange that d3d12_clear_memory_page_state doesn't work for you. I just checked on my PC (also with AMD GPU) and it works flawlessly. If you want better support feel free to join discord.

**Comment by sharicov** [comment]
Thanks, Gliniak!
