### ISSUE TITLE
A triangle appears on the surface of the sea during the game in ACE COMBAT6.

### ISSUE THREAD

**Issue by fieldwest** [xenia-project/xenia#2204]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

In "ACE COMBAT6", triangles appear on the surface of the sea during the game.
Also, the BGM and audio are cut off in the middle of the movie after the game starts

https://assets.st-note.com/img/1686832636474-TqX05RxIe8.png

### Describe what should happen

I want the triangle to disappear from the surface of the sea.
I would like the background music and audio to be uninterrupted during the movie in the game.

### If applicable, provide a callstack here, especially for crashes

it doesn't crash.

**Comment by Triang3l** [comment]
This bug is discussed in https://github.com/xenia-project/game-compatibility/issues/419. I did a bit of research, it's possible that the precision of calculating the reciprocal on the Xbox 360 GPU is different than on modern GPUs, but I'm not entirely sure: https://github.com/xenia-project/game-compatibility/issues/419#issuecomment-974652080
