### ISSUE TITLE
xenia keeps crashing when i start it up with wine

### ISSUE THREAD

**Issue by dantheman121** [xenia-project/xenia#2223]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

it keeps saying it encountered a serious error

### Describe what should happen

it should boot up like it would on windows 10

### If applicable, provide a callstack here, especially for crashes

Unhandled exception: page fault on write access to 0x00000000ffffffff in 64-bit code (0x0000014054a2f8).
Register dump:
 rip:000000014054a2f8 rsp:000000000011fe38 rbp:0000000000000000 eflags:00010202 (  R- --  I   - - - )
 rax:00000000ffffffff rbx:0000000000000000 rcx:000000007ffd0000 rdx:000000014054a2f8
 rsi:0000000000000000 rdi:0000000000000000  r8:000000007ffd0000  r9:000000017007f888 r10:0000000000000000
 r11:0000000000000000 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x0000000011fe38:  000000017802a019 0000000000000000
0x0000000011fe48:  000000000011fe90 0000000000000000
0x0000000011fe58:  0000000000000000 0000000000000000
0x0000000011fe68:  00000001700600b0 0000000000000000
0x0000000011fe78:  0000000000000000 0000000000000000
0x0000000011fe88:  0000000000000000 000000014054a2f8
0x0000000011fe98:  000000007ffd0000 ffffffffffffffff
0x0000000011fea8:  000000017006f140 0000000170027490
0x0000000011feb8:  0000000000000000 000000000011fea0
0x0000000011fec8:  0000000000000000 000000000011fe70
0x0000000011fed8:  0000000000000000 0000000000000000
0x0000000011fee8:  0000000000000000 0000000000000000
Backtrace:
=>0 0x0000014054a2f8 in xenia (+0x54a2f8) (0000000000000000)
0x0000014054a2f8 EntryPoint in xenia: add %al, (%rax)
Modules:
Module	Address					Debug info	Name (13 modules)
PE	0000000140000000-000000014109f000	Export          xenia
PE	0000000170000000-000000017039a000	Deferred        ntdll
PE	0000000174000000-000000017461b000	Deferred        kernelbase
PE	0000000178000000-00000001781a1000	Deferred        kernel32
ELF	00007b631bb4d000-00007b631bb75000	Deferred        liblzma.so.5
ELF	00007b631bb75000-00007b631bb90000	Deferred        libunwind.so.8
ELF	00007b631bb90000-00007b631bb9a000	Deferred        librt.so.1
ELF	00007b631bb9a000-00007b631bc6d000	Dwarf           ntdll.so
ELF	00007b631bc70000-00007b631be44000	Deferred        libc.so.6
ELF	00007b631be44000-00007b631be4a000	Deferred        libdl.so.2
ELF	00007b631be4a000-00007b631be6c000	Deferred        libpthread.so.0
ELF	00007b631be7e000-00007b631beab000	Deferred        ld-linux-x86-64.so.2
ELF	00007b631beab000-00007b631beb0000	Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	0000005c    0     wine_rpcrt4_io
	00000078    0     wine_rpcrt4_io
	000000a8    0     wine_rpcrt4_io
	000000c0    0     wine_rpcrt4_io
	000000d4    0     
	000000ec    0     wine_rpcrt4_io
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	00000060    0     
	00000064    0     
	00000068    0     
	0000006c    0     
	000000cc    0     
	000000d0    0     
00000070 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000074    0     
	0000007c    0     
	00000080    0     wine_sechost_service
	00000084    0     
	00000088    0     
	0000008c    0     
	000000a0    0     
	000000a4    0     
00000090 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000094    0     
	000000d8    0     
	000000dc    0     wine_rpcrt4_server
00000098 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	0000009c    0     
	000000ac    0     
	000000b0    0     wine_sechost_service
	000000b4    0     wine_rpcrt4_server
000000b8 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000bc    0     
	000000c4    0     
	000000c8    0     wine_sechost_service
000000e4 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000e8    0     
	000000f4    0     
	000000f8    0     wine_sechost_service
	000000fc    0     wine_rpcrt4_server
	00000100    0     wine_rpcrt4_server
	00000104    0     wine_rpcrt4_io
	00000140    0     wine_rpcrt4_io
00000114 (D) Z:\mnt\chromeos\archive\xenia_master.zip\xenia.exe
	["Z:\mnt\chromeos\archive\xenia_master.zip\xenia.exe" ]
	00000118    0 <== 
	0000012c    0     
00000124 conhost.exe
	["C:\windows\system32\conhost.exe" --server 0x40]
	00000128    0     
00000130 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000134    0     
	00000138    0     
	0000013c    0     wine_rpcrt4_server
System information:
    Wine build: wine-8.14 (Staging)
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.117-19676-g93ff41d10a7f

### If applicable, upload a logfile and link it here

[backtrace.txt](https://github.com/xenia-project/xenia/files/12432724/backtrace.txt)

**Comment by dantheman121** [comment]
it does it with both master and canary

**Comment by Fabxx** [comment]
Install dxvk and vkd3d in your prefix

**Comment by Fabxx** [comment]
> > Install dxvk and vkd3d in your prefix
> 
> how and i am on linux btw

install winetricks in your system, then simply do the command `winetricks dxvk vkd3d` or if you want to change the prefix path to another folder instead of `.wine` add this line at the beginning:

`WINEPREFIX="path/to/prefix/folder" winetricks dxvk vkd3d`

keep in mind tho that it would be better to install vkd3d-proton from the master code in github, following the compile instructions since they implemented new fixes for shaders that are still not available in the 2.9 release

**Comment by dantheman121** [comment]
> 

it says it has no installation candidate
