### ISSUE TITLE
We really can't alter controls?

### ISSUE THREAD

**Issue by qu-mark** [xenia-project/xenia#2251]
I've literally never seen an emulator ever, even in the 1990s, that disallowed control editing? You're just stuck with whatever the defaults are?

**Comment by nugarp** [comment]
keyboard assignments are in the toml. if you want to use something else, try x360ce (https://www.x360ce.com/) or wheel2xinput (https://forum.arcadecontrols.com/index.php/topic,166939.0.html)

**Comment by Razzile** [comment]
This is a good candidate for the new UI if/when it eventually gets merged
