### ISSUE TITLE
4:3 Support seems to be broken.

### ISSUE THREAD

**Issue by portalsam1** [xenia-project/xenia#2255]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

In the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ#43) it states to change this line: 
`video_mode->is_widescreen = 1` to `video_mode->is_widescreen = 0`
to enable 4:3 support.

After following [the building guide](https://github.com/xenia-project/xenia/blob/master/docs/building.md) I had a functional build of Xenia, however changing `is_widescreen` would do absolutely nothing, and the window and game would stay in 16:9. I built with both the Visual Studio build button and using `xb build` and both results were the same.

Changed Function:
![image](https://github.com/xenia-project/xenia/assets/41414314/c2142336-4b80-41cd-a6c9-123c574b38ac)

Games still being ran in 16:9:
![image](https://github.com/xenia-project/xenia/assets/41414314/ea4d1b2d-9fbd-4576-ae92-0a72c3ced3ee)
![image](https://github.com/xenia-project/xenia/assets/41414314/7b996da8-334b-4bb7-a8f1-66512acfbe64)

### Describe what should happen

Following the instructions in the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ#43) should produce the results it describes, and games should run in 4:3.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-project/xenia/files/14784699/xenia.log)

**Comment by Gliniak** [comment]
First screenshot clearly looks like 4:3 stretched to window size. 
Just set ``present_letterbox`` to false and resize window manually to size you want

**Comment by Margen67** [comment]
Xenia master's wiki is outdated. Use this option with Xenia Canary instead: https://github.com/xenia-canary/xenia-canary/wiki/Options#internal-display-resolution
