### ISSUE TITLE
Build under Linux fails with "cannot bind non-const lvalue reference of type <x> to an rvalue of type <y>"

### ISSUE THREAD

**Issue by v-fox** [xenia-project/xenia#2262]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

So, I've tried to see if xenia became operable under Linux and updated from 20230914T123251. f6b5424 (where it tries to launch something but gets stuck) to 20240516T230549. 8e7301f but it failed to build altogether.

### Describe what should happen

Build successfully and possibly launch something.

### If applicable, provide a callstack here, especially for crashes

Seems like https://github.com/xenia-project/xenia/commit/376bad5056f3b8456b48c5f9ad61c85005127418 have caused it. Reverting it made the build pass.

### If applicable, upload a logfile and link it here

It failed with:
```
[  137s] /home/abuild/rpmbuild/BUILD/xenia-20240516T230549.8e7301f/src/xenia/gpu/command_processor.cc: In member function ‘virtual void xe::gpu::CommandProcessor::WriteRegister(uint32_t, uint32_t)’:
[  137s] /home/abuild/rpmbuild/BUILD/xenia-20240516T230549.8e7301f/src/xenia/gpu/command_processor.cc:372:67: error: cannot bind non-const lvalue reference of type ‘xe::gpu::reg::DC_LUT_RW_INDEX&’ to an rvalue of type ‘xe::gpu::reg::DC_LUT_RW_INDEX’
[  137s]   372 |         auto& gamma_ramp_rw_index = regs.Get<reg::DC_LUT_RW_INDEX>();
[  137s]       |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[  137s] /home/abuild/rpmbuild/BUILD/xenia-20240516T230549.8e7301f/src/xenia/gpu/command_processor.cc:408:67: error: cannot bind non-const lvalue reference of type ‘xe::gpu::reg::DC_LUT_RW_INDEX&’ to an rvalue of type ‘xe::gpu::reg::DC_LUT_RW_INDEX’
[  137s]   408 |         auto& gamma_ramp_rw_index = regs.Get<reg::DC_LUT_RW_INDEX>();
[  137s]       |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[  137s] /home/abuild/rpmbuild/BUILD/xenia-20240516T230549.8e7301f/src/xenia/gpu/command_processor.cc:443:67: error: cannot bind non-const lvalue reference of type ‘xe::gpu::reg::DC_LUT_RW_INDEX&’ to an rvalue of type ‘xe::gpu::reg::DC_LUT_RW_INDEX’
[  137s]   443 |         auto& gamma_ramp_rw_index = regs.Get<reg::DC_LUT_RW_INDEX>();
[  137s]       |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by Triang3l** [comment]
For some reason Visual Studio allows that, though definitely the modification of that value was going nowhere after that change. Fixed it. Thank you!
