### ISSUE TITLE
Resident evil 5 chapter 4-1 the screen is dark

### ISSUE THREAD

**Issue by Vantrestar** [xenia-project/xenia#2278]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [x] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

when i reached chapter 4-1 of resident evil 5 on xenia canary i went into a tomb as normal but the place is so dark for the emulator or smothing that i cant see anything in front of me

### Describe what should happen

![image](https://github.com/user-attachments/assets/2903546a-a0e6-4afb-8b64-6ea217d88dd4)

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/user-attachments/files/16529264/xenia.log)

**Comment by Margen67** [comment]
Game compatibility reports don’t belong here. Also this isn’t even the right branch/repository.
