### ISSUE TITLE
very specific crash (impossible to advance)

### ISSUE THREAD

**Issue by deividariel0909** [xenia-project/xenia#2285]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

I have no idea why but I know it's only in this GTA 5 mission
![Unhandled Exception in Xenia 8_31_2024 4_43_16 PM](https://github.com/user-attachments/assets/df4342d5-43f8-4bab-9baa-6a1061656513)

### Describe what should happen

In this mission everything happens normally until you get to this part and the game crashes out of nowhere

### If applicable, provide a callstack here, especially for crashes

[xenia.log](https://github.com/user-attachments/files/16825860/xenia.log)

### If applicable, upload a logfile and link it here

![Unhandled Exception in Xenia 8_31_2024 4_43_16 PM](https://github.com/user-attachments/assets/5f748c6b-c616-4996-b5cd-8748f5d065f6)

**Comment by Gliniak** [comment]
Closing: Validation point 2 not meet. 
``The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)``
