### ISSUE TITLE
Perfect Dark Zero Mousehook Support?

### ISSUE THREAD

**Issue by jovantancic** [xenia-project/xenia#2291]
Any chance making Perfect Dark Zero support mousehook like XBLA? I'm not playing this with gamepad.

_Originally posted by @jovantancic in https://github.com/xenia-project/game-compatibility/issues/175#issuecomment-2517982083_

**Comment by jovantancic** [comment]
> Mousehook is an unofficial fork unrelated from the Xenia project [read here](https://github.com/marinesciencedude/xenia-canary-mousehook/pull/37)

Can you guide me what could I do to make mousehook work for Perfect Dark Zero? And also have good mouse sensitivity with it, like on XBLA?

**Comment by Margen67** [comment]
This sort of request doesn't belong here. Go to the #modding channel on the Xenia Discord: https://discord.gg/Q9mxZf9
