### ISSUE TITLE
Fix buffer clearing in RR

### ISSUE THREAD

**Issue by benvanik** [xenia-project/xenia#315]

**Comment by raven02** [comment]
@benvanik , not too sure if it is an coincidence , i tried to disable the in-shader alpha testing and replace it using traditional one , the RR ,Ikaruga and Raiden IV are clearing correct now.

**Comment by raven02** [comment]
looks like alpha testing may affect the clearing as well .

**Comment by JohnGodgames** [comment]
@raven02 yeah maybe 

I know that it's not right, but it's maybe related to something similar.Let's see what happened when we set:
#### from 
active_draw_.header->alpha_test.x = enabled ? 1.0f : 0.0f;
#### to 
active_draw_.header->alpha_test.x = enabled ? 0.0f : 0.0f;

#### at
https://github.com/benvanik/xenia/blob/master/src/xenia/gpu/gl4/draw_batcher.h#L74








#### Results with active_draw_.header->alpha_test.x = enabled ? 1.0f : 0.0f;

https://www.youtube.com/watch?v=AuvY4MkEDvg
https://www.youtube.com/watch?v=vsKi2tfkce4

#### Results with active_draw_.header->alpha_test.x = enabled ? 0.0f : 0.0f;

https://www.youtube.com/watch?v=KrgIsHRts84
https://www.youtube.com/watch?v=Z56-67u7HLU
https://www.youtube.com/watch?v=01HHYSyrcfw
https://www.youtube.com/watch?v=CYJ8_ItJUEU
https://www.youtube.com/watch?v=EUYQd711ErI

**Comment by raven02** [comment]
Surprisingly #524 doesnt fix it.
