### ISSUE TITLE
Replace FileTimeToSystemTime & SystemTimeToFileTime in xboxkrnl_rtl.cc

### ISSUE THREAD

**Issue by benvanik** [xenia-project/xenia#347]
Need to do some funky math to do TIME_FIELD<->FILETIME. Can probably reverse engineer this.

**Comment by AlyShmahell** [comment]
wasn't this solved with [7a0a36c](https://github.com/benvanik/xenia/commit/a74c88851b49608335907a3ae7a19c5ff1aed3f7#diff-db3b25a8090a7e005731feaec3ae9160)?

**Comment by Parovozik** [comment]
I think solved :D
