### ISSUE TITLE
Several games are hanging at opening videos etc. - src\xenia\gpu\gl4\command_processor.cc:680

### ISSUE THREAD

**Issue by JohnGodgames** [xenia-project/xenia#427]
Some of games:
Ace Combat 6: Fires of Liberation
Afro Samurai
Alone in the Dark
Armored Core 4
Armored Core V
Armored Core: For Answer
Binary Domain
Blazing Angels: Squadrons of WWII
Blue Dragon
Burnout Revenge
Cabela's African Safari
Cabela's Big Game Hunter
Cabela's North American Adventures
Conan
Dead Rising 2
Dead Space
Dead Space 2

https://github.com/benvanik/xenia/blob/master/src/xenia/gpu/gl4/command_processor.cc#L680

```
class CommandProcessor::RingbufferReader {
 public:
  RingbufferReader(uint8_t* membase, uint32_t base_ptr, uint32_t ptr_mask,
                   uint32_t start_ptr, uint32_t end_ptr)
      : membase_(membase),
        base_ptr_(base_ptr),
        ptr_mask_(ptr_mask),
        end_ptr_(end_ptr),
        ptr_(start_ptr),
        offset_(0) {}

  uint32_t ptr() const { return ptr_; }
  uint32_t offset() const { return offset_; }
  bool can_read() const { return ptr_ != end_ptr_; }

  uint32_t Peek() { return xe::load_and_swap<uint32_t>(membase_ + ptr_); }

  void CheckRead(uint32_t words) {
    assert_true(ptr_ + words * sizeof(uint32_t) <= end_ptr_);
  }
```

**Comment by tmccaff** [comment]
Call Of Duty 2 is another hangs

**Comment by ikki84** [comment]
@tmccaff thanks for the feedback,

**Comment by Margen67** [comment]
OpenGL is deprecated.
