### ISSUE TITLE
GL4 Translator: ADDs/MULs/SUBs issues

### ISSUE THREAD

**Issue by JohnGodgames** [xenia-project/xenia#473]
Unfortunately, it is not correct too or there is an error somewhere else.

https://github.com/benvanik/xenia/pull/273/files#r32895357
## Tested Games:

Eternal Sonata
Dead or Alive 5 Ultimate
Deadliest Catch - Alaskan Storm
Looney Tunes: Acme Arsenal
Madagascar Kartz
Rogue Warrior
Way of the Samurai 3
## Current state:

GL4ShaderTranslator::TranslateALU_ADDs ---> Append(".y");
GL4ShaderTranslator::TranslateALU_MULs ---> Append(".y");
GL4ShaderTranslator::TranslateALU_SUBs ---> Append(".y");

Eternal Sonata
![eternal sonata y](https://cloud.githubusercontent.com/assets/11453507/11423963/6bac9cae-9449-11e5-9ca5-fa3417b0478d.PNG)

Dead or Alive 5 Ultimate
![dead or alive 5 ultimate y](https://cloud.githubusercontent.com/assets/11453507/11423967/715f4610-9449-11e5-97e0-dae47ed8a9d1.PNG)

Deadliest Catch - Alaskan Storm
![deadliest catch - alaskan storm y](https://cloud.githubusercontent.com/assets/11453507/11423969/75a4bbc4-9449-11e5-93df-b1370a708317.PNG)

Looney Tunes: Acme Arsenal
![looney tunes acme arsenal y](https://cloud.githubusercontent.com/assets/11453507/11423973/7b588596-9449-11e5-9e2a-8d95ada2563e.PNG)

Madagascar Kartz
![madagascar kartz y](https://cloud.githubusercontent.com/assets/11453507/11423976/80752d90-9449-11e5-909d-0753d7456e37.PNG)

Rogue Warrior
![rogue warrior translatealu_adds y](https://cloud.githubusercontent.com/assets/11453507/11423983/927a85da-9449-11e5-9462-6e9d5b86a39a.PNG)

Way of the Samurai 3
![way of the samurai 3 y](https://cloud.githubusercontent.com/assets/11453507/11423985/96d305c6-9449-11e5-931a-1fa237ab55f9.PNG)
## Previous state:

GL4ShaderTranslator::TranslateALU_ADDs ---> Append(".z");
GL4ShaderTranslator::TranslateALU_MULs ---> Append(".z");
GL4ShaderTranslator::TranslateALU_SUBs ---> Append(".z");

Eternal Sonata
![eternal sonata z](https://cloud.githubusercontent.com/assets/11453507/11424754/1215f92c-9450-11e5-833e-26f8a977f7e1.PNG)

Dead or Alive 5 Ultimate
![dead or alive 5 ultimate z](https://cloud.githubusercontent.com/assets/11453507/11424759/18126734-9450-11e5-9550-a249deafebc0.PNG)

Deadliest Catch - Alaskan Storm
![deadliest catch - alaskan storm z](https://cloud.githubusercontent.com/assets/11453507/11424764/1f29a316-9450-11e5-9c74-de5909d0e47c.PNG)

Looney Tunes: Acme Arsenal
![looney tunes acme arsenal z](https://cloud.githubusercontent.com/assets/11453507/11424771/25e41902-9450-11e5-9518-c03ed00e80aa.PNG)

Madagascar Kartz
![madagascar kartz z](https://cloud.githubusercontent.com/assets/11453507/11424774/2bb2ddc8-9450-11e5-8cdc-159d655add8d.PNG)

Rogue Warrior
![rogue warrior translatealu_adds z](https://cloud.githubusercontent.com/assets/11453507/11424780/312ddb2c-9450-11e5-800d-69431de98bf9.PNG)

Way of the Samurai 3
![way of the samurai 3 z](https://cloud.githubusercontent.com/assets/11453507/11424904/3c7c9ac6-9451-11e5-9e83-15c0c0de1947.PNG)

**Comment by raven02** [comment]
Humm .Looks like .y or .z works correct in some games .

**Comment by JohnGodgames** [comment]
#### GL4ShaderTranslator::TranslateALU_ADDs ---> Append(".y"); and vice versa affects: 
- Makes intro videos violet in some games
- Dead or Alive 5 Ultimate (intro / title screen) broken


#### GL4ShaderTranslator::TranslateALU_MULs ---> Append(".y"); and vice versa affects: 
- ???


#### GL4ShaderTranslator::TranslateALU_SUBs ---> Append(".y"); and vice versa affects: 
- Eternal Sonata (Causes Black Characters)
- Madagascar Kartz (Fixes Black Characters)
- Looney Tunes: Acme Arsenal (Looks better but, blue surface can be related to unimplemented fog)
- Way of the Samurai 3 (Looks better but, grey surface can be related to unimplemented fog)

**Comment by raven02** [comment]
so the following combination should be working all correct ?

GL4ShaderTranslator::TranslateALU_ADDs ---> Append(".z");
GL4ShaderTranslator::TranslateALU_MULs ---> Append(".y");
GL4ShaderTranslator::TranslateALU_SUBs ---> Append(".y");

**Comment by JohnGodgames** [comment]
@benvanik seems to have a interactive round-tripping tool for shader assembly to verify identical bytecode: https://imgur.com/2oA3ACl and also saw why a lot of dariosama's loop code in the shader translator never worked (taken from xenia-dev irc).It can be a solution for this issues I hope...

**Comment by raven02** [comment]
GL4ShaderTranslator::TranslateALU_ADDs ---> Append(".z"); also fixes the intro violet issues in the game - I'm Alive

**Comment by TranzRail** [comment]
@benvanik 

It's worth noting that Madagascar Karts has its shaders in HLSL in addition to the cache version within the games data directory. Useful for additional troubleshooting. It's also not the first game I've come across that has HLSL files available for inspection. Rayman 3 is another (which has serious graphical issues).

**Comment by JohnGodgames** [comment]
.hlsl files also in games:


America's Army - True Soldiers
Blood Bowl
Brave - A Warrior's Tale
Cars
Cloudy with a Chance of Meatballs
Deadliest Catch - Alaskan Storm
Janline (JPN)
MindJack
Minute to Win It
Mobile Suit Gundam - Operation Troy (JPN)
Need for Speed Shift
Need for Speed Shift 2 Unleashed
NCIS: The Game
Operation Darkness
Rayman Raving Rabbids
Sonic & SEGA All-Stars Racing with Banjo Kazooie
Splatterhouse
Surf's Up
Test Drive Ferrari Racing Legends
Tom Clancy's Ghost Recon - Advanced Warfighter
Tom Clancy's Ghost Recon - Advanced Warfighter 2
Tom Clancy's Rainbow Six - Vegas
Tom Clancy's Rainbow Six - Vegas 2
Way of the Samurai 3

**Comment by benvanik** [comment]
Awesome listing! I'm reworking the shader translation now and that will come in handy! Thank you both!

**Comment by benvanik** [comment]
This is likely to have gotten a lot better (or at least hopefully not worse!) with https://github.com/benvanik/xenia/compare/295c62c7a4b4...083f936bbcb4

**Comment by JohnGodgames** [comment]
Eternal Sonata is broken now  :(
![eternal sonata new glsl 1](https://cloud.githubusercontent.com/assets/11453507/11613603/2a4327de-9c27-11e5-836b-558bad697958.PNG)
![eternal sonata new glsl 2](https://cloud.githubusercontent.com/assets/11453507/11613604/2e598246-9c27-11e5-80a3-acf4a7dd9dec.PNG)
![eternal sonata new glsl 3](https://cloud.githubusercontent.com/assets/11453507/11613605/329b41e6-9c27-11e5-9e34-921821c637c3.PNG)

**Comment by JohnGodgames** [comment]
Next...

Dead or Alive 5 Ultimate
![doa 5 new glsl 1](https://cloud.githubusercontent.com/assets/11453507/11613634/4c901a12-9c28-11e5-869e-7b6b6d34ac1a.PNG)

Deadliest Catch - Alaskan Storm
![deadliest catch as new glsl 1](https://cloud.githubusercontent.com/assets/11453507/11613655/f9b57714-9c28-11e5-9e1e-720e65ae5259.PNG)


Rogue Warrior
![rogue warrior new glsl 1](https://cloud.githubusercontent.com/assets/11453507/11613644/8f30b566-9c28-11e5-956d-055d10f331c1.PNG)

**Comment by benvanik** [comment]
I'll check Eternal Sonata - there's one or two features I'm missing and it
may be using them.

**Comment by benvanik** [comment]
Looks like Eternal Sonata may be caused by unimplemented flow control. I'll get started on jumps now to see if it helps.

**Comment by JohnGodgames** [comment]
Diamond at title screen now seems to be a correct, but alpha issues are still there.

![eternal sonata glsl 1](https://cloud.githubusercontent.com/assets/11453507/11644336/59096a2c-9d4b-11e5-8055-51b7ec23acf2.PNG)
![eternal sonata glsl 2](https://cloud.githubusercontent.com/assets/11453507/11644338/5d580912-9d4b-11e5-8bbf-1da50cd36e4b.PNG)
![eternal sonata glsl 3](https://cloud.githubusercontent.com/assets/11453507/11644342/626e7b8e-9d4b-11e5-9eb9-c43813089958.PNG)
![eternal sonata glsl 4](https://cloud.githubusercontent.com/assets/11453507/11644343/668d1cf2-9d4b-11e5-92a4-222eec5b6bec.PNG)

**Comment by raven02** [comment]
@JohnGodgames , looks like RR6 is running pretty well with some fixes on your own . Probably u can propose the changes here.

https://www.youtube.com/watch?v=KrgIsHRts84

**Comment by raven02** [comment]
Madagascar Kartz 's car in title screen still in black color .

**Comment by JohnGodgames** [comment]
Something wrong in glsl shader translator propably. @benvanik @raven02

**Comment by Oreos019** [comment]
![image](https://user-images.githubusercontent.com/34288678/33636219-32d71910-da13-11e7-8825-2ba9207e7edf.png)

**Comment by DrChat** [comment]
GL4 is now gone. Closed.
