### ISSUE TITLE
XNA games based on .NET not supported

### ISSUE THREAD

**Issue by SakataGintokiYT** [xenia-project/xenia#529]
@x1nixmzeng 
@benvanik 
@gibbed 

Emulator closes after starting the game
*You need to add support for this format
-Arkedo Series: 01 JUMP!
-Arkedo Series: 02 SWAP!
-Arkedo Series: 03 PIXEL!

**Comment by jackchentwkh** [comment]
As I know the XBLIG indie games are created with XNA studio which is based on .NET framework. The execution file is actually a managed file including IL, not machine code. So unless the Xenia can emulate the whole system function of the xbox360 including the IL interpretation, we won't expect the emulation of these XNA titles any sooner. on the other hand, there is one 360 emulator dedicated for this IL type XBLA related titles, but unfortunately the emulator was abandoned.

**Comment by jackchentwkh** [comment]
there are two ways to run the titles built with XNA, one is to decompile it back to source code with ILspy or dotpeek, the recompile the source code with the publicly available XNA sdk on PC and fix the related errors in the source. the other way is a high end emulation which converts the xex files back to windows PE file format first, then introduces the windows version XNA runtimes, and then uses self-developed DLLs to fixup the missing function between 360 and PC. here is a unfinished HLE project. 

https://code.google.com/archive/p/ex360e/

**Comment by x1nixmzeng** [comment]
This is perhaps another case for trying to read `GameInfo.xml` or `GameInfo.bin` before launching `default.xex`. But as @jackchentwkh mentions there are bigger differences with XNA games.

**Comment by x1nixmzeng** [comment]
I was thinking of `ArcadeInfo.xml` in my last post.

The launch target in this series is `Arkedo Series - 02 SWAP!.exe` - which is a valid Windows executable... It's worth taking a look at the work done for Fez. I think there was an attempt to convert it to PC somewhere!

**Comment by x1nixmzeng** [comment]
So we can actually decompile this to IL using [ildasm](https://msdn.microsoft.com/en-us/library/f7dy01k1%28v=vs.110%29.aspx).

Running this command:
> ildasm /out=xenia_arkedo "Arkedo Series - 02 SWAP!.exe"

Produces:
* Microsoft.Xna.Framework.RuntimeProfile
* xenia_arkedo
* xenia_arkedo.res

Where work can begin :smiling_imp:

**Comment by benvanik** [comment]
Yeah, .NET based games are likely out of scope for awhile. Pre-translating them or running them on top of the fancy new coreclr seems like possible routes, and then that runtime could either use xenia as a library (for graphics/audio/etc) or be integrated into xenia.

**Comment by benvanik** [comment]
Could still be nice to detect them and throw up an error message that they are not supported.

**Comment by Pirateguybrush** [comment]
Is there likely to be any progress on this issue?

**Comment by x1nixmzeng** [comment]
> Is there likely to be any progress on this issue?

I did some work a few years ago (>5) to run the binaries through mono. It was surprisingly easy to setup the basic c# runtime interpreter in the mono project - there is a windows visual studio solution and decent demo project too. However the bulk of the work would be writing an XNA framework that is integrated in xenia. It's not as simple as copying files from the 360 and interpreting them - it's a full project in itself, and there are hundreds of classes that need implementing (or integrating, ie from mono game). 

Anyone trying to play XNA based game may have more success converting the 360-XNA games to PC-XNA games. I know that was attempted for FEZ when it was an Xbox exclusive but don't have a source

**Comment by eisnerguy1** [comment]
I wanted to check in to see if this if this is on the road map? I loved playing those Arkedo Series games and would love to play them on my Xbox Series X as well 👍🏻

**Comment by Razzile** [comment]
> I wanted to check in to see if this if this is on the road map? I loved playing those Arkedo Series games and would love to play them on my Xbox Series X as well 👍🏻

very unlikely. I think XNA games are a good target for a project separate from Xenia.

**Comment by berkayfeci** [comment]
> > Is there likely to be any progress on this issue?
> 
> I did some work a few years ago (>5) to run the binaries through mono. It was surprisingly easy to setup the basic c# runtime interpreter in the mono project - there is a windows visual studio solution and decent demo project too. However the bulk of the work would be writing an XNA framework that is integrated in xenia. It's not as simple as copying files from the 360 and interpreting them - it's a full project in itself, and there are hundreds of classes that need implementing (or integrating, ie from mono game).
> 
> Anyone trying to play XNA based game may have more success converting the 360-XNA games to PC-XNA games. I know that was attempted for FEZ when it was an Xbox exclusive but don't have a source

Do you have commits available for that project? I only want to play Dishwasher Dead Samurai, if i can manage to make it work somehow that would be great, don't need Xenia implementation specially.

**Comment by Glinckey** [comment]
Are there any projects that are making these XBLIG games work? cuz it seems like the 360 games and the xblig games are way too diffrent to be working in xenia (...unless?)

**Comment by UroshUchiha** [comment]
I am also interested in this. I want to play a game called Decay which is exclusive to the XBLIG format from what I can see.

**Comment by ZombieLRP** [comment]
Can you tell me guys how do i get these indie games to run
