### ISSUE TITLE
Games with half / quarter of screen cut off

### ISSUE THREAD

**Issue by JohnGodgames** [xenia-project/xenia#586]
There is a bunch of games with a black cut-off (half / quarter).I want to list these games here.
### Current list:
- 3D Ultra Minigolf
- Assault Heroes
- Battlestations: Pacific
- Cabela's African Safari
- Cabela's Alaskan Adventures
- Dance Dance Revolution Universe
- Dance Dance Revolution Universe 2
- Eternal Sonata
- Halo: Spartan Assault
- LEGO Star Wars: The Complete Saga
- PocketBike Racer
- Star Trek: Legacy
- TMNT
- Transformers: The Game

and propably more

**Assault Heroes**
![assault heroes](https://cloud.githubusercontent.com/assets/11453507/16203964/1030b6b8-371d-11e6-96d9-18740f7b24be.PNG)

**Battlestations: Pacific**
![battlestation pacific](https://cloud.githubusercontent.com/assets/11453507/16247774/bab24acc-380b-11e6-9c35-6111bc46a39a.PNG)

**Cabela's African Safari**
![cabelas african safari](https://cloud.githubusercontent.com/assets/11453507/16247783/c96167b0-380b-11e6-801c-29ed6138daed.PNG)

**Cabela's Alaskan Adventures**
![cabelas alaskan adventures](https://cloud.githubusercontent.com/assets/11453507/16247798/d244c0f2-380b-11e6-8683-8f2a1548bfe2.PNG)

**Dance Dance Revolution Universe**
![ddr universe](https://cloud.githubusercontent.com/assets/11453507/16247840/0cdf1c76-380c-11e6-9078-24d78a407e16.PNG)

**Dance Dance Revolution Universe 2**
![ddr universe 2](https://cloud.githubusercontent.com/assets/11453507/16247846/151cd270-380c-11e6-8b7a-e333cf986f94.PNG)

**Eternal Sonata**
![eternal sonata](https://cloud.githubusercontent.com/assets/11453507/16203940/f87a7fcc-371c-11e6-9b1f-82cfa36afc76.PNG)

**Halo: Spartan Assault**
![halo spartan assault](https://cloud.githubusercontent.com/assets/11453507/16281570/4cf495ca-38c5-11e6-8d37-197d937868a9.PNG)

**LEGO Star Wars: The Complete Saga**
![lego sw cs](https://cloud.githubusercontent.com/assets/11453507/16203952/06183c32-371d-11e6-8112-af50d5497ab4.PNG)

**PocketBike Racer**
![pocketbike racer](https://cloud.githubusercontent.com/assets/11453507/16281503/04e2ca90-38c5-11e6-807d-fd8c3f69304a.PNG)

**Star Trek: Legacy**
![star trek legacy](https://cloud.githubusercontent.com/assets/11453507/16281526/20f05838-38c5-11e6-8cc9-7eaa26060cd0.PNG)

**TMNT**
![tmnt](https://cloud.githubusercontent.com/assets/11453507/16281542/352e005c-38c5-11e6-92a5-4ec590bcc70b.PNG)

**Transformers: The Game**
![transformers the game](https://cloud.githubusercontent.com/assets/11453507/16281580/556837ac-38c5-11e6-806e-c5d7e079cc63.PNG)

**Comment by Razzile** [comment]
3D Ultra Minigolf also suffers from this and has inverted colors 

![image](https://cloud.githubusercontent.com/assets/5256381/16209979/a335eb86-3731-11e6-8341-b9baac4b5349.png)

**Comment by DrChat** [comment]
Does this still happen on the Vulkan backend?

**Comment by Margen67** [comment]
@DrChat Lego Star Wars: The Complete Saga and Eternal Sonata crash with Vulkan.

**Comment by Kitessencial** [comment]
Sonic: The Hedgehog also suffers from this issue.

**Comment by Triang3l** [comment]
Resolving with tiled rendering is fully implemented now (a 512 MB buffer with guest addressing is used for resolving and texture loading, so it works naturally).
