### ISSUE TITLE
Add PS4 controller input driver.

### ISSUE THREAD

**Issue by benvanik** [xenia-project/xenia#60]
Not sure what this requires, but it'd be nice to support them. Going forward they may be easier to support than 360 pads as (in theory) in OSX 10.9 they just work.

**Comment by vgturtle127** [comment]
I figured, Mac support these days is a real pain. Even for somebody who has done it before! I remember trying to compile my NES emulator for Mac. That was the worst week and a half of my life!

**Comment by benvanik** [comment]
Yeah - Apple hasn't been keeping up with graphics tech, and we need crazy new stuff. If they ever decide to give some love to OSX it shouldn't be too hard to port whatever works on Linux over. You know, if I ever get around to that ;P

**Comment by vgturtle127** [comment]
It's funny that they have a 5K iMac, but no good GPU tech support. LOL.

I have some Linux experience (a whole hell of a lot more than Mac support, that's for sure!), so I may be able to help with the port if you need anything. The only problem is my CPU is not an AVX2 compatible chip, so I can't test anything I write, I would have to rely on others. I just spent a crap ton of money upgrading my PC too. :sob:

**Comment by sasukedotca** [comment]
@vgturtle127: Can't you use this ? never tested it but worth trying may be, even if it's software emulation, https://software.intel.com/en-us/articles/intel-software-development-emulator/

**Comment by vgturtle127** [comment]
@sasukedotca Huh, I had never heard of such a thing. I suppose I could try it, but I'm not sure how it works or how it would affect things like performance or my current setup. I will look into it, but I don't have an extremely fast PC, so it may not even work in the long run anyway.

**Comment by hlide** [comment]
> Intel SDE is built upon the Pin dynamic binary instrumentation system and the XED encoder decoder. Pin controls the execution of an application. Pin examines each static instruction in the application approximately once, as it builds traces for execution. During this process, which is called instrumentation, for each instruction encountered Pin asks Intel SDE if this instruction should be emulated or not. If the instruction is to be emulated, then Intel SDE tells Pin to skip over that instruction and instead branch to the appropriate emulation routine. It also tells Pin how to invoke that emulation function, what arguments to pass, etc.

As you can see, it is more and less like a just-in-time partial dynamic recompilation. So the more your cpu is recent, the less instructions are emulated. So if your cpu has AVX but no AVX2, it only needs to emulate AVX2 instructions. The only drawback it needs to instrument the instructions when first encountered (slow process).

**Comment by vgturtle127** [comment]
Alright, that makes sense. I wonder if Intel has ever considered a sort of Dolphin-esque cached recompiler? Maybe that would speed it up? I will give it a try when I finish upgrading to Windows 10 and updating all my dev tools and what not.

**Comment by mirhl** [comment]
You'll need to support DirectInput under Windows then
In linux it should be just about plain joystick api
as for osx.. I believe you have to pass through IOHID.

**Comment by vgturtle127** [comment]
@benvanik I am doing some research on the DS4 here:

https://github.com/Jays2Kings/DS4Windows/issues/17

Just in case you are interested...

**Comment by Margen67** [comment]
Fixed by #1493.
