### ISSUE TITLE
Xenia cannot run more than one game across a single instance

### ISSUE THREAD

**Issue by OfficerObese** [xenia-project/xenia#641]
games crashing almost immediatly returns with error originating from line 856 in memeory.cc on 8gb ram 840m and intel core i5 4210u the last version of xenia i know works was built around the 25 of november before this issue started occuring

**Comment by PcDivision** [comment]
i did some debugging trying to fix the issue but was unable to

**Comment by PcDivision** [comment]
xenia works fine when using --gpu=null

**Comment by maxton** [comment]
Can you find the commit at which things stopped working? And also try --gpu=gl4 and --gpu=vulkan

**Comment by DrChat** [comment]
This probably never worked.
Would be something worth looking into, as this would deal with shutdown and initialization of Xenia.

At the moment I suspect we're not completely cleaning up Xenia after we leave a game, and it will just crash when loading a new game.

**Comment by PcDivision** [comment]
ive done both gpu gl4 and gpu vulkan gl4 starts the game for about 2 seconds and then crashes

**Comment by PcDivision** [comment]
it has somthing to do with memory allocation?

**Comment by PcDivision** [comment]
just got a friend to test xenia on a different computer same issues 930m i5 5200u 8gb ram

**Comment by PcDivision** [comment]
the error was in memory.cc line 856 and is
  if (start_page_number == UINT_MAX || end_page_number == UINT_MAX) {
    // Out of memory.
    XELOGE("BaseHeap::Alloc failed to find contiguous range");
    assert_always("Heap exhausted!");
    return false;
  }

**Comment by PcDivision** [comment]
xenia has sufficient memory to run.

**Comment by paulsapps** [comment]
pls consider collecting more info instead of spam posting so much!

**Comment by Margen67** [comment]
Duplicate of #665
