### ISSUE TITLE
Add automatic detection or launch parameter for setting license mask

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#675]
https://github.com/benvanik/xenia/blob/master/src/xenia/kernel/xam/xam_content.cc#L46
As described in the comments the license mask tells the game if it's a trial/demo etc.
But since it's not automatically detected by xenia it's always a trial or demo even if the game was purchased except for ISOs/disks.

Currently you have to do the equivalent of reverting https://github.com/benvanik/xenia/commit/c1d3d62e2a0f65cf04ac00be7a2b2598a51a68e3#diff-3b0782cb74d284e5e3191984cec00709L41 to make games run like they're purchased.

To solve this you could either:

1. Detect if the game is a demo/trial or not (maybe this could help? https://github.com/benvanik/xenia/blob/d4a14e8a495bde4224c3a9e9a967959f132af9ae/src/xenia/vfs/devices/stfs_container_device.h#L30 )
2. Add a launch parameter to set it manually

Related: #318

**Comment by Razzile** [comment]
While I think this is a good idea, I think the xenia devs purposely chose to have games run in demo mode :/

**Comment by gibbed** [comment]
Currently this is intended and will not be changed for the foreseeable future. If you desire a different license mask, you may build Xenia yourself.

**Comment by Margen67** [comment]
Fixed by #1436.
