### ISSUE TITLE
Add support for GOD images

### ISSUE THREAD

**Issue by Margen67** [xenia-project/xenia#680]
It would be nice to be able to play games installed from a disc without using god2iso.

Maybe this could help:
https://github.com/eliecharra/iso2god-cli
![msg](https://cloud.githubusercontent.com/assets/3462541/23860124/3df27f74-07c3-11e7-8cf8-94c49f56430a.png)

**Comment by Razzile** [comment]
do god games not run natively? I thought they did

**Comment by Margen67** [comment]
Games installed from a disc on the Xbox 360 dashboard don't run natively.
They have a file for the game, and a folder ending with .data that has a bunch of files.
Attempting to load the file without using god2iso to convert them just crashes xenia.

**Comment by Wildenhaus** [comment]
#1254
