### ISSUE TITLE
Xenia controls are not working

### ISSUE THREAD

**Issue by Lakera** [xenia-project/xenia#691]
Controls are not working.

neither keyboard or xbox 360 controller is not responding.

what am I doing wrong?

**Comment by Razzile** [comment]
is this for all games or a specific game. some games currently don't respond to controls

**Comment by DrChat** [comment]
@Razzile: Which games don't respond to controller inputs?

**Comment by Razzile** [comment]
https://github.com/xenia-project/game-compatibility/issues/110 and https://github.com/xenia-project/game-compatibility/issues/731 are the ones that pop to my mind but i'm pretty sure there are more

**Comment by gibbed** [comment]
Rainbow Islands: Towering Adventure! is also affected by this, but I wasn't able to figure out why yet.

**Comment by DrChat** [comment]
Hmm - I know xboxkrnl exports some input functions which I may have stubbed out...

**Comment by gibbed** [comment]
For RI:TA! specifically, I know it's calling the usual input state functions we've implemented, as expected. I'm pretty sure it has to do with the state we put the game in (IE XAM events/etc) causing it to just ignore them.

**Comment by Lakera** [comment]
I was trying to get nhl 15 to work, as the comp.list says it should work without a doubt. 🌵

**Comment by rlabrecque** [comment]
No game works 'without a doubt' on xenia at this time. Some games may work for some people to varying degrees, at some point.

**Comment by tmccaff** [comment]
Was this a recent issue or always the case? Reason I am asking was any of those files converted to new style affected this?

**Comment by Margen67** [comment]
There's a *[xam-input-problems](https://github.com/xenia-project/game-compatibility/issues?q=is%3Aopen+is%3Aissue+label%3Axam-input-problems)* label on game-compatibility so I don't see the need for this issue anymore.
