### ISSUE TITLE
AMD Does not support D24 depth format

### ISSUE THREAD

**Issue by zerocold1981** [xenia-project/xenia#756]
Hello! Thank you very much for your work! With every build I test my collection of games, the initial screens with video are emulated perfectly in the main cases. Progress is immediately visible. Unfortunately on my video card, like on the whole series of video cards, Polaris can not be played due to a Vulcan driver error. How so? After all, the volcano is the strong place of this series of video cards. My video card is RX480 gaming 8 gb. The mistake is always the same: **!> 00000004 Vulkan check: vkCreateImage returned VK_ERROR_INITIALIZATION_FAILED**
The big request to write anything, can I hope for anything in the near future? Thanks again to all those who are doing this great job. Regards, Yuri.

**Comment by Margen67** [comment]
#578 ?

**Comment by zerocold1981** [comment]
Yes

**Comment by DrChat** [comment]
I know why this happens and have it fixed locally.

I haven't pushed this workaround yet because AMD only supports D16_UNORM or D32_SFLOAT, and I haven't figured out a viable solution yet.

**Comment by shadowbrony33** [comment]
DrChat, can you push that fix to another branch?

**Comment by zerocold1981** [comment]
I believe that a solution will be found. I'm far from programming, so I'll wait with faith in you.

**Comment by shadowbrony33** [comment]
https://github.com/shadowbrony33/Xenia/releases/tag/Xenia

I made a temporary fix but it causes some graphical issues.
I was only able to test Sonic 06 and CoD: AW Multiplayer, the former having issues with invisible textures and the later seems to be working normally when compared to #a5bdeeb on a 1050Ti

**Comment by zerocold1981** [comment]
Not really helped .. The game is loaded! Previously, this was not, but more time after time, the same thing in the log:
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST
!> 0000159C Vulkan check: vkQueueSubmit returned VK_ERROR_INITIALIZATION_FAILED
!> 0000159C Failed to queue present: VK_ERROR_DEVICE_LOST

**Comment by shadowbrony33** [comment]
As I said I could only test a couple of games and it was just a temporary fix that will cause issues.

**Comment by zerocold1981** [comment]
The main thing is that there is a way to solve the problem, it is necessary to refine it and everything will go well, I hope)

**Comment by zerocold1981** [comment]
I downloaded Sonic, yes, it works, of course there are graphic bugs, but it's still a breakthrough, because before AMD just did not start anything on the volcan

**Comment by shadowbrony33** [comment]
I just tested Minecraft and it works perfectly, super meatboy works, I've gone in-game with CoD Ghosts and MW3.

**Comment by zerocold1981** [comment]
I ask DrChat to pay attention to this and allocate time for researching the possibility of developing a patch, or solving the problem for users' amd. We hope for you!

**Comment by drillsar** [comment]
I am sure will be a solution in the next month or so fingers crossed. I have a NVIDIA card though.

**Comment by shadowbrony33** [comment]
Builds for those who have AMD GPUs: https://ci.appveyor.com/project/shadowbrony33/xenia/history

Notes:
1. Changed 24-Bit render targets to 32-Bit
2. Unlocked XBLA content (Thanks to [Gibbed](https://github.com/gibbed))
3. Pause and Resume (Thanks to NuclearC)

**Comment by zerocold1981** [comment]
Many thanks! I'll check it in 6 hours, after work

**Comment by zerocold1981** [comment]
Ok, I came home and tested a few games.
1. Resonance.Of.Fate. 
The screensaver goes perfectly, after the inscription: press start - crashes, without notification
[Resonance.Of.Fate.zip](https://github.com/benvanik/xenia/files/1200046/Resonance.Of.Fate.zip)
2. Blue Dragon. Freezed, during the first minute of the initial video. Skip the screensaver unfortunately did not work.
[Blue Dragon.zip](https://github.com/benvanik/xenia/files/1200065/Blue.Dragon.zip)
3. Infinite Undiscovery. 
The first attempt is an immediate crash of the emulator.
The second attempt is a black screen with music.
[Infinite Undiscovery1_.zip](https://github.com/benvanik/xenia/files/1200080/Infinite.Undiscovery1_.zip)
[Infinite Undiscovery2.zip](https://github.com/benvanik/xenia/files/1200081/Infinite.Undiscovery2.zip)
4. Tales of Vesperia.
[Tales of Vesperia.zip](https://github.com/benvanik/xenia/files/1200095/Tales.of.Vesperia.zip)
The initial video hangs, the music continues to play.
5. Sonic the Hedgehog.
![screenshot](https://user-images.githubusercontent.com/10199092/28966236-c0784b10-791d-11e7-9618-c7119ff2733c.png)
[Sonic the Hedgehog.zip](https://github.com/benvanik/xenia/files/1200104/Sonic.the.Hedgehog.zip)
The game works, but the black screen. Screenshot attached
6. Star Ocean The Last Hope
Comes to the point: press the start button, but there is no reaction to it.
[Star Ocean The Last Hope.zip](https://github.com/benvanik/xenia/files/1200116/Star.Ocean.The.Last.Hope.zip)
Thanks for your work. I hope the logs are useful.

**Comment by Sleepy93** [comment]
Firstly thanks for your work at all.
Secondly just an idea so correct me if I'm wrong or I missunderstand something.
as I understand need to modify the 24 to 32 like in this build https://github.com/shadowbrony33/xenia/commit/1bbe8cf91eac9b2af829d9c677a7d4c1ede336c4

but could it be automatized by adding conditions.

https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPhysicalDeviceProperties.html
I've just done a little search about getting gpu type in Vulkan and my question is the following:

Could it be possible to make a condition for deciding which gpu has the current pc.
If Not AMD run the 24bit renderer else use the 32bit renderer..

Thanks.

**Comment by DrChat** [comment]
I've looked into this a bit before - and it looks like using D32F instead of D24 causes regressions.

I'm not entirely sure how we can effectively emulate 24-bit normalized depth using a 32-bit float depth buffer - if anyone has experience with this, please do hop into this discussion.

**Comment by shadowbrony33** [comment]
@DrChat Main issue I've had with using D32F is that Sonic 06 doesn't render correctly with most texturees being rendered invisible HOWEVER this also still occurs on my RX 580 with D24 so I'm not sure what exactly is causing that issue.

**Comment by Triang3l** [comment]
Both native unorm24 depth and unorm24-as-float32 (handled largely similarly to float24-as-float32) are supported on Vulkan in Xenia now.
