### ISSUE TITLE
Games sample from resolve textures with different dimensions

### ISSUE THREAD

**Issue by DrChat** [xenia-project/xenia#795]
As seen in #789.

Geometry Wars RE2
> Initial render: 150 x 100, resolved to 152x104
> Pass 2: 75x50, resolved as 80x56
> Pass 3: 37x25, resolved as 40x32
> Pass 4: 18x12, resolved as 24x16
> Pass 5: 9x6, resolved as 16x8
> Pass 6: 4x3, resolved as 8x8
> Pass 7: 2x1, resolved as 8x8

Textures are sampled with the dimensions from the first column.

**Comment by gibbed** [comment]
When games are doing this are they asking for a scaled version of that texture, or a sliced portion of the texture? (I'm assuming the former?)

**Comment by DrChat** [comment]
For our purposes let's assume the latter.
I don't think it's possible for games to scale a texture by requesting smaller dimensions, and I know RDR already slices images doing this.

**Comment by sabretooth** [comment]
I think the right way to do this is to generate cropped views of the resolve surface at demand time / when it's attached to the sampler. I'll try and come up with a changeset for method that's less terrible than my previous reimplementation of the resolve texture feature.

**Comment by DrChat** [comment]
I ran into this problem before and I thought of duplicating the texture with the sub-dimensions, and assigning it to the same writewatch as the original (so it's updated alongside the original).

**Comment by sabretooth** [comment]
Took a stab at generating cropped views of textures. Commit is here if you want to look: https://github.com/sabretooth/xenia/commit/a8228a5fc96f414f7716ee9e90abafd34ce2a6a3

Works for GW:RE2 at least!

**Comment by DrChat** [comment]
That actually looks a lot like what I had in mind :)

Open a PR with these changes and I'll review and test them.

**Comment by sabretooth** [comment]
Opened the PR as #800. I updated the patch to address your comments on the previous revision (about the feature flags).

**Comment by sabretooth** [comment]
You get a chance to look at that pull request yet?

**Comment by DrChat** [comment]
@sabretooth I looked at it briefly but haven't had time as of yet to give it a test.
I'll test it soon, but as of now it looks good!

**Comment by Triang3l** [comment]
Supported by the Direct3D 12 backend with generalized physical memory that resolve does tiling directly to.
