### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by DrChat** [xenia-project/xenia#811]
Xenia needs a new logo icon - the current one looks great when enlarged, but when shrunk the PCB design looks real nasty.

Honestly, the current one without the PCB etches would be awesome!

**Comment by Razzile** [comment]
I think it would be cool if the xenia logo was similar to the xbox 360 sphere (but in xenia colors)
![image](https://user-images.githubusercontent.com/5256381/33245647-8dca8fea-d302-11e7-9507-e119cdd9e90b.png)
not sure if that would infringe on any copyrights though

**Comment by gibbed** [comment]
@Razzile Have you actually seen Xenia's logo...?

**Comment by UlsterRose** [comment]
![hji oihp](https://user-images.githubusercontent.com/8225831/33261126-be710a82-d359-11e7-9d5c-fcdcf7e744fb.png)

What about this?

**Comment by iwanttobethebee** [comment]
What about putting that one but in red?

**Comment by Razzile** [comment]
@gibbed I was referring to it being shiny and metallic vs pixel art style

**Comment by DrChat** [comment]
@UlsterRose That actually looks really nice! Could you show me what it looks like at 16x16 resolution?

**Comment by C0RP3N** [comment]
Seems more like 32x32 tbh

**Comment by UlsterRose** [comment]
This is what it looks like on the taskbar:
![image](https://user-images.githubusercontent.com/8225831/33365518-6904392e-d4e0-11e7-974d-54fb419b7359.png)

This is it at 16x16 res:
![16](https://user-images.githubusercontent.com/8225831/33365767-281670c0-d4e1-11e7-9024-7d8ffccdfc9c.png)

**Comment by DrChat** [comment]
That looks awesome! Personally I'm sold on using this icon - any objections @gibbed / @benvanik?

**Comment by DrChat** [comment]
@gibbed Could you clarify? Do you mean keep the current icon at large sizes?

**Comment by gibbed** [comment]
@DrChat Yes? I quite like the old logo, but I agree it looks iffy at small sizes.

**Comment by DrChat** [comment]
Ah - I agree that it does look nicer at large sizes, but we only ever use the logo with smaller sizes

**Comment by gibbed** [comment]
I am actually pretty sure that the .ico we currently have of the current logo is not set up correctly, now that I'm looking at it.

**Comment by gibbed** [comment]
Figured it out. When we create the window, we set hIconSm, which, for whatever reason, causes a badly upscaled (or downscaled) version of the icon to be used. Setting it to NULL makes it default to looking at hIcon for the correct size icon to use. Looks better with the real 16x16 icon.

Pushed a commit with this fix, since it will affect any icon we end up using anyway. 78565e

**Comment by Sintendo** [comment]
Isn't this a little too similar to the actual Xbox 360 logo? It'd hate to see this project facing legal repercussions because of an icon.

**Comment by SquidNip** [comment]
I think @Sintendo is right it might face legal repercussions but I'm not a lawyer

**Comment by zGodz** [comment]
icon too small

**Comment by Xephorium** [comment]
A couple more options (though, they don't address the M$ design similarity issue):

![icon - detail pass](https://user-images.githubusercontent.com/7660631/37249781-a9c7ddbc-24b3-11e8-8308-eea05afbaf09.png)
![icon - wire pass](https://user-images.githubusercontent.com/7660631/37249784-ad2771fc-24b3-11e8-938b-4e371485737a.png)

And in varied colors:

![icon - detail red pass](https://user-images.githubusercontent.com/7660631/37249819-8cc3a8e4-24b4-11e8-9d19-9f23283c0ed6.png)
![icon - wire red pass](https://user-images.githubusercontent.com/7660631/37249820-911e8d64-24b4-11e8-91d4-af96988b328c.png)

![icon - detail purple pass](https://user-images.githubusercontent.com/7660631/37249823-955ca780-24b4-11e8-86e2-2029a5386bac.png)
![icon - wire purple pass](https://user-images.githubusercontent.com/7660631/37249824-97b2b75e-24b4-11e8-89ba-2668da1eea0e.png)

![icon - detail orange pass](https://user-images.githubusercontent.com/7660631/37249826-99efbcec-24b4-11e8-8ff8-0e2451d7e11e.png)
![icon - wire orange pass](https://user-images.githubusercontent.com/7660631/37249827-9b6fd1ce-24b4-11e8-8b8f-fc92df71ac3e.png)

**Comment by Xephorium** [comment]
And a rounded out revisit of @euroze's suggestion:

![icon - solid blue pass](https://user-images.githubusercontent.com/7660631/37358229-8ccdf44c-26b8-11e8-9517-1110727e694c.png)

![xenia icon - scaled solid](https://user-images.githubusercontent.com/7660631/37358230-8ed47130-26b8-11e8-9a76-2741f0497e1b.png)
@DrChat @gibbed @benvanik - Looking for your thoughts here in particular. Any preferences? Not liking any of these since they pull so heavily from the 360 original? We _could_ also use the pcb board idea for higher res (>~48px) and one of the simpler designs at lower res.

**Comment by DrChat** [comment]
@Xephorium Nice work! The first design actually looks great, and it scales very nicely!

@gibbed, what are your thoughts?

**Comment by DrChat** [comment]
@Xephorium Do you mind if I start using your icons under the MIT license?

**Comment by Xephorium** [comment]
@DrChat I don't mind at all! If you'd like, I can also open a PR on the project that replaces the originals in proper resolution and adds the source (.blend) file.

**Comment by Xephorium** [comment]
That's correct. Not the most common program for graphic design, but it's what I know and also freeware 🤷‍♂️

**Comment by DrChat** [comment]
Huh. Cool! Didn't know Blender was a good tool for designing icons.
